### ISSUE TITLE
Allow to change forward url

### ISSUE THREAD

**Issue by luckydonald** [muety/wakapi#105]
In the admin section there's an option to forward events to the original wakatime service.
One can enter a key, but not to another self hosted system.
It is missing a field to enter the URL.

**Comment by muety** [comment]
Didn't think about that use case, but why not. Only two concerns come to my mind at first sight:

* UI should be designed in a way that normal users are not confused or overwhelmed. WakaTime endpoint should be set as default and the field for changing it should not be too prominent.
* We need to think of a way to avoid loops. When Wakapi instance A forwards heartbeats to Wakapi instance B, which forwards heartbeats back to A, things are going to explode :boom:

**Comment by luckydonald** [comment]
Regarding UI

> `https://wakatime.com/api/current/heartbeats` <kbd>Reset</kbd>

**Comment by muety** [comment]
I like it 😃.

Regarding loops: the forwarding middleware would probably have to be extended to check whether an incoming heartbeat is already in the database and, if yes, drop it and don't forward it. Some kind of caching could be added, as such a forwarding loop will most likely occur within very short time.

**Comment by luckydonald** [comment]
I'm not sure if that kind of loop is really a problem. After all I can DDoS a server a lot simpler.
Feels like a over-engineered solution for the average self-hoster.
