### ISSUE TITLE
White background on pages

### ISSUE THREAD

**Issue by Syndamia** [muety/wakapi#118]
After I updated to 1.23.3, the background of the page seems to be just white, which messes up everything:
![image](https://user-images.githubusercontent.com/46843671/107147171-483c9a80-6955-11eb-80dd-7fc9ff16a705.png)

In the HTML, it seems that the background should have the class `bg-gray-850`, but I can't seem to find that CSS class anywhere, is it a bad name or something I missed out on my end?
![image](https://user-images.githubusercontent.com/46843671/107147226-918cea00-6955-11eb-991a-675528158b8c.png)

**Comment by muety** [comment]
Did you try to hard-refresh the page or even "disable cache" in the DevTool's network tab?
If that doesn't solve the issue, I'll investigate.

**Comment by YC** [comment]
I am unable to reproduce this. 
Tried both the Linux executable and Docker built off the latest commit on master. 
From the executable:

![Screenshot_2021-02-08_00-20-33](https://user-images.githubusercontent.com/5828744/107147693-7fd23380-69a3-11eb-92bf-55f7990908c2.png)

**Comment by Syndamia** [comment]
Yeah, I'm sorry, it was a browser caching problem. Thank you for your time!

**Comment by muety** [comment]
No worries, you're welcome.

I saw the same thing myself on my local dev instance after having changed the styles. Strangely enough, it didn't happen on the live system. Caching is weird.
