### ISSUE TITLE
Emoji icons not showing

### ISSUE THREAD

**Issue by muety** [muety/wakapi#119]
Currently, all icons are simply copy-and-pasted Unicode emojis. However, some browsers seem to not display them, but show [tofu](https://en.m.wikipedia.org/wiki/Noto_fonts#Etymology) instead. We should explicitly include icons. To keep things minimalist, I'm thinking of just adding individual SVGs. 

Btw, does someone actually have this problem in their browser? I only saw the phenomenon on screenshots occasionally.

**Comment by muety** [comment]
Any ideas what's a good choice here? I'd actually like to stick with colored icons and I want it as light-weight as possible.

**Comment by Atakku** [comment]
Take a look at material icons
https://github.com/material-icons/material-icons

**Comment by Atakku** [comment]
Also for colored ones you can use:
https://github.com/twitter/twemoji

**Comment by muety** [comment]
![image](https://user-images.githubusercontent.com/8978843/112649362-a8769580-8e4a-11eb-91d8-db05b8087378.png)

Might actually only be a font problem. Need to debug this further.

**Comment by muety** [comment]
Looks like it's not really a fonts problem. Here is some discussion: https://askubuntu.com/questions/1029661/18-04-color-emoji-not-showing-up-at-all-in-chrome-only-partially-in-firefox/1196561#1196561.

Either accept that some Chrome users will not see the icons or actually add an icon library (preferably [iconify](https://github.com/iconify/iconify)), which somewhat contradicts the minimalism paradigm of Wakapi.

**Comment by Lucas-M-G** [comment]
I have the same issue on my chromium (arch linux system). I think a icon lib was a good choice.

**Comment by muety** [comment]
Thanks for your feedback! I'll include a dedicated icon library soon.
