### ISSUE TITLE
[ERROR] migration '20210213_add_has_data_field' failed

### ISSUE THREAD

**Issue by bialad** [muety/wakapi#127]
Just upgraded from 1.23.6 to 1.24.0 and got this error during startup.

[ERROR] migration '20210213_add_has_data_field' failed – ERROR: argument of WHERE must be type boolean, not type integer (SQLSTATE 42804)

My database is postgres 13.1.

**Comment by muety** [comment]
Sorry, didn't test with Postgres for the last release. Should be fixed now. I'll push a new release soon. Thanks for bringing this up!

**Comment by bialad** [comment]
That was quick, it works now!

Thank you!
