### ISSUE TITLE
Does have helm chart for easy deploy to kubernetes cluster?

### ISSUE THREAD

**Issue by andreymaznyak** [muety/wakapi#134]
I want to deploy it to own private kubernetus cluster.

I can create it.

**Comment by muety** [comment]
I'm not experienced with Kubernetes, but if you are wiling to create a Helm chart go for it! I'd appreciate it.

**Comment by andreymaznyak** [comment]
I created config in https://github.com/andreymaznyak/wakapi-helm-chart

If you want, we can move this code to your repository.

Or add link to readme.

**Comment by muety** [comment]
Thanks for that contribution, I'll link to your project in Wakapi's README on my next commit. 
Does the Helm chart support to deploy a database (mysql or postgres) alongside Wakapi or does it only work with the embedded sqlite?

**Comment by andreymaznyak** [comment]
> Thanks for that contribution, I'll link to your project in Wakapi's README on my next commit.
> Does the Helm chart support to deploy a database (mysql or postgres) alongside Wakapi or does it only work with the embedded sqlite?

Thank you. Yes this chart support external db config. I use postgres. But it not automaticly deploy with wakapi helm chart. We can implement it. [I created issue for solve it](https://github.com/andreymaznyak/wakapi-helm-chart/issues/2).
