### ISSUE TITLE
Is it possible to use wakapi at the same time as wakatime?

### ISSUE THREAD

**Issue by nck974** [muety/wakapi#138]
Hello, I just installed wakapi in a raspberry pi and at first glance looks awesome, but I'd like to keep using wakatime at the same time. Is it possible to provide in the client config two keys and servers?

**Comment by muety** [comment]
Check out the settings page. You can connect your Wakatime account there.

**Comment by nck974** [comment]
Thanks, I did not think about it, sorry for the question :P.

**Comment by muety** [comment]
No worries, hope you'll enjoy using Wakapi :)
