### ISSUE TITLE
Invalid integrity hashses on a self hosted instance of Wakapi

### ISSUE THREAD

**Issue by arsenypoga** [muety/wakapi#141]
I have a self-hosted instance of Wakapi running on a windows machine. Accessing the site's index page yields the errors shown below.

Waterfox:
![image](https://user-images.githubusercontent.com/15068255/111676957-155bb100-87f5-11eb-8d36-1f3b60cc8209.png)
Brave:
![image](https://user-images.githubusercontent.com/15068255/111678905-29081700-87f7-11eb-9950-a03decac560d.png)

I tried to completely remove integrity hashes from the `foot.tpl.html` but that did nothing.

**Comment by muety** [comment]
After removing those hashes, did you recompile and restart the application? Also, what version of Wakapi are you using?

**Comment by arsenypoga** [comment]
This is what I have done. 
After all these steps the error still persists.  I am really not sure why editing the templates does nothing. 

```powershell
PS D:\software\wakapi> cat .\version.txt
1.24.7
PS D:\software\wakapi> rm .\wakapi.exe
PS D:\software\wakapi> git pull
Already up to date.
PS D:\software\wakapi> cat .\views\foot.tpl.html
<script src="assets/vendor/seedrandom.min.js" crossorigin="anonymous"></script><!--integrity="sha384-bFS5CG904xYIgxBcrDF4KFNXuM7KeSGsSvS/QTaDqMTEdbaaxjg2Y2TSU3Ygs7wG"-->
<script src="assets/vendor/Chart.bundle.min.js" crossorigin="anonymous"></script><!--integrity="sha384-mZ3q69BYmd4GxHp59G3RrsaFdWDxVSoqd7oVYuWRm2qiXrduT63lQtlhdD9lKbm3"-->
PS D:\software\wakapi> go build -o ./wakapi.exe
PS D:\software\wakapi> .\wakapi.exe
```

**Comment by muety** [comment]
Try running `go generate` before `go build`, that is going to help.
I'll investigate the actual cause of the problem tomorrow.

**Comment by arsenypoga** [comment]
Ok, so `go generate` did the trick. There are no errors while accessing the page now, with the integrity hashes commented out. Tested that on both MS edge and Waterfox.
