### ISSUE TITLE
Wakapi on Raspberri Pi 4

### ISSUE THREAD

**Issue by nck974** [muety/wakapi#150]
Hi, this i actually not an issue but I have no idea where else to put it, I just wanted to share some little documentation I did for myself to make the project work in a raspberry pi4 and it works wonderfully with a postgres database. There may be some typo as I just wrote it from the history of my bash after some weeks of trying it. There is nothing special that is not on some form in the documentation. But for people without much experience with go like me may help.

# Install wakapi in raspberri pi 4

## Setup
```bash
# Installing go for example in /usr/local/go
apt install build-essential
export GO111MODULE=on
go get github.com/markbates/pkger/cmd/pkger
wget https://golang.org/dl/go1.16.linux-armv6l.tar.gz
# or newest arm version from https://golang.org/dl/
tar xvf go1.16.linux-armv6l.tar.gz
rm go1.16.linux-armv6l.tar.gz
mv go/* .
rmdir go
vim ~/.profile
# add
# export GOPATH=$HOME/work
# export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
source ~/.profile
cd ..
```

## Download
```bash
git clone https://github.com/muety/wakapi.git
cd wakapi
```

# Compile
```bash
go get github.com/markbates/pkger/cmd/pkger
go generate
go build -o wakapi
cp config.default.yml config.yml
vim config.yml # setup your config
nohup ./wakapi > nohuput.out &
```

## Set apache config
Example running on port 80 without https for a local network
cd /etc/apache2/sites-available/
```bash
<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:3001/
    ProxyPassReverse / http://127.0.0.1:3001/

    CustomLog /var/log/apache2/wakapi.log common
    ServerName my-server
</VirtualHost>
```
```bash
a2enmod proxy
a2enmod proxy_http
a2enmod lbmethod_byrequests
a2ensite wakapi.conf

service apache2 restart
```

## Wakapi server config:
```bash
server:
  listen_ipv4: localhost    # leave blank to disable ipv4
  listen_ipv6: ::1          # leave blank to disable ipv6
  tls_cert_path:            # leave blank to not use https
  tls_key_path:             # leave blank to not use https
  port: 3001
  base_path: /
```

## Update
```bash
# Kill process
ps aux | grep wakapi
kill <give_here_pid>
# Download and reset to remove problems with go.sum
git reset --hard
git pull
go generate
go build
# Start again
nohup ./wakapi > nohuput.out &
```

**Comment by muety** [comment]
Thanks a lot for sharing your efforts! I'm sure this is going to help people. I'll pin the issue.

**Comment by muety** [comment]
Only one remark here: in the last section ("Update") you are missing the `go build` command after `go generate`.

**Comment by nck974** [comment]
Fixed.

**Comment by LoneDev6** [comment]
Works pretty fine, should be included in the wiki page, thanks a lot!

**Comment by muety** [comment]
Moved this to the Wiki: https://github.com/muety/wakapi/wiki/Setup-on-Raspberry-Pi-4
