### ISSUE TITLE
Configurable heartbeat offset / AFK timeout

### ISSUE THREAD

**Issue by muety** [muety/wakapi#156]
Current default is two minutes, however, this might be made configurable on a per-user basis. However, already generated summaries wouldn't be affected in retrospect. One would have to regenerate all their summaries. 

_Originally requested by @Lucas-M-G in https://github.com/muety/wakapi/issues/82#issuecomment-811866918_

**Comment by jsbrain** [comment]
Push!
This would be a great feature :)

**Comment by szczepaan** [comment]
Hi, it's been a while :)
any news when the 'keystroke timeout' param will be configurable per user ?

**Comment by muety** [comment]
After a lot of users have expressed their interest in this, I'll increase prio from B to A. Still can't give an estimate for when I'll get to this, sorry!

**Comment by szczepaan** [comment]
@muety how can I change the default value globally for all users?

**Comment by muety** [comment]
You can't, currently.

**Comment by alanhamlett** [comment]
Here's the code we use at WakaTime to combine Heartbeats into Durations based on Keystroke Timeout:

https://gist.github.com/alanhamlett/0d0c496fe40d977dbdbf0abf0b34ec57

**Comment by ariaieboy** [comment]
I imported my data from Wakatime to my instance of Wakapi and the total time reported on Wakapi is 300 hours less than the total hours that Wakatime reports.  
I think the reason behind it is that the AFK timeout between these 2 are different

**Comment by muety** [comment]
> I think the reason behind it is that the AFK timeout between these 2 are different.

Yes, correct.
