### ISSUE TITLE
[Suggestion] Keep track of GitHub issues closed per day

### ISSUE THREAD

**Issue by LoneDev6** [muety/wakapi#158]
I don't know if anyone is interested in this, but let me know if you like the idea:

I think would be nice to have a graph that shows how many Github issues were closed per project per day, to see how much time the user spent on fixing issues on a particular project that day.

**Comment by muety** [comment]
Hi @LoneDev6, thanks for your feature request. I generally don't like to reject user-requested features, however, in this case I would say it is out of scope of this project. Frankly, I wouldn't want to integrate statistics other than coding heartbeats. Sorry!
