### ISSUE TITLE
Add meta tags to enable for link previews

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#159]
Hey there, me again.

I think it would be a good idea to have a Link preview. Too often I send a link to my Wakapi instance to someone and their response is "What is this"?.

<img width="372" alt="They ask what is it" src="https://user-images.githubusercontent.com/25652765/113468975-c8442580-9417-11eb-8352-1ff335f814b8.png">

Having a simple link preview would probably help with this. The link preview could include a simple, 1-2 sentences description of what Wakapi does. It could be the same description that is located on the landing page.

If you think this is a good idea, I can take some time and PR it in :smiley: 

\* Update: I just updated my instance and it seem there is a link preview now :open_mouth: It's only missing and image and a description.

**Comment by muety** [comment]
Great idea, thanks! I'd appreciate if you looked into this and did a PR 😊. The official instance doesn't seem to have link previews, I tested it by pasting a link into a Telegram chat. Would you would probably have to do is add OpenGraph meta tags to the HTML head. Also make sure to include the screenshot on the frontpage as a preview image as it will look even nicer. Thank you!

**Comment by muety** [comment]
Btw, @notarock, I quickly checked your Wakapi instance. May I ask how you deploy it? Do you compile it from source or do you use the Docker image? Because although you have the latest version `1.24.5`, it looks like at least the fix for #141 is still missing. If you compile it yourself, you might have forgotten running `go generate`. If you use Docker though, I might have investigate if there's a problem with the build process.

**Comment by notarock** [comment]
I run mine with docker-compose file that looks like this:

``` yaml
wakapi:
    image: n1try/wakapi:latest
    container_name: wakapi
    networks:
      - proxy
    ports:
      - 3000:3000
    restart: always
```

I'm using the `latest` tag for the Docker image. Maybe it's missing a `go generate` in the Dockerfile?

**Comment by muety** [comment]
Never mind, I confused `1.24.5` with `1.25.4`. Everything's fine. You'll just have to update your container.
