### ISSUE TITLE
Postgres DB Support

### ISSUE THREAD

**Issue by staticvoidmaine** [muety/wakapi#16]
Hey there,

This looks like a wonderful project!

Is there any chance you would consider either:
- including postgres support
- accepting a merge request adding postgres support

**Comment by n1try** [comment]
Hi @staticvoidmaine, thanks for your request! 🙂 Probably I won't have the capacity to add Postgres support myself any time soon. But PRs are totally welcome!
This project uses GORM as a database interface, so it should be fairly easy to integrate Postgres in a uniform and clean way.

**Comment by muety** [comment]
I had time to add Postgres support. However, it's not yet tested extensively, so please let me know if you discover any issues.

**Comment by muety** [comment]
Resolved with 1510bcaa917a2cc90c80fd38c40f66e0bf105079.

**Comment by staticvoidmaine** [comment]
Fantastic, thank you so much! I'll be testing this out very soon. I'll be running it in docker and I'll make sure to report back with any success/failure
