### ISSUE TITLE
[Release] BetterDiscord compatibility plugin

### ISSUE THREAD

**Issue by LoneDev6** [muety/wakapi#162]
Hello, here is a working [plugin](https://github.com/LoneDev6/Wakapi-Discord/blob/main/Wakapi.plugin.js) for BetterDiscord.
I hope it will be useful to people that use a tickets bot to handle support requests of their softwares.
I coded this since I wanted to keep track of how much time I spend on giving support to my clients.

You can customize it on your needs, for now it keeps track of time spent on channels inside categories that contains "tickets" text.

**Comment by muety** [comment]
Thanks a lot! Although I'm not a Discord user, this looks like great work! You could even consider changing the project's name to "WakaTime" and try to submit it to WakaTime's [plugin catalog](https://wakatime.com/plugins), so it gets an even broader audience, i.e. not only Wakapi- but also WakaTime users.

**Comment by LoneDev6** [comment]
Thanks!
Actually this was tested only on Wakapi, same for the Unity3D plugin, so it may not work

**Comment by muety** [comment]
The `heartbeat` endpoints of Wakapi and WakaTime shouldbe identical, I would assume it will work. Anyway, thanks for sharign your plugins!
