### ISSUE TITLE
Weird summary when using "past 7 days"

### ISSUE THREAD

**Issue by Daste745** [muety/wakapi#168]
When checking the "past 7 days" summary I noticed my progress from April 9 missing completely.
Last 7 days (equivalent of `?from=2021-04-05&to=2021-04-13`) doesn't include my progress from April 9:
![2021 04 12_12:13:45](https://user-images.githubusercontent.com/25880357/114379504-2ea01500-9b89-11eb-9570-2b87d319a316.png)

Checking April 9 (`?from=2021-04-09&to=2021-04-10`) shows me 5 hours spent on a project:
![2021 04 12_12:08:47](https://user-images.githubusercontent.com/25880357/114379506-2fd14200-9b89-11eb-86c8-340e6b114a85.png)

I've been messing with the ranges and I can't figure out a pattern. I can provide my heartbeat data and API url if needed for testing.

**Comment by muety** [comment]
That's weird :thinking: Could you provide a (potentially pseudonymized) dump of your database (you can also send it to me via mail directly) and afterwards try to "Clear & Regeneration Summaries" on the settings page?

**Comment by Daste745** [comment]
I just tried using `&recompute=true` when requesting my summary and it seems to show everything correctly.
![2021 04 12_12:33:01](https://user-images.githubusercontent.com/25880357/114381390-5bedc280-9b8b-11eb-9f44-8fc77bd34166.png)

I'll create a dump and send it to you via email. Will it work if I remove other users and their corresponding heartbeats+summaries? I'm using this instance with two friends and don't want to share their data.

**Comment by muety** [comment]
Alright, it took me quite a while to figure out the cause of the problem. But I think I have fixed it now. Just for the record (and to speed up things in case something similar ever occurs again):

* Current summary computation assumes that a summary is generated for every single day in a year, no matter if that day actually has heartbeats or not.
* If a day doesn't have heartbeats, the summary's `from` and `to` dates correspond to start and end of that particular day respectively.
* If a day does have heartbeats, the summary ranges from first to last heartbeat, i.e. only a subset interval of the entire day.
* In your case, two unfortunate things fell together:
    * First, you didn't have any heartbeats in 04/08, i.e. the corresponding summary was from `2021-04-08 00:00:00` to `2021-04-09 00:00:00`
    * Second, for some reason, no summary at all was present for 04/09. I am still not sure how this could happen. Maybe there is still some bug about time zones or so, I have to check that again. 
* Both events combined revealed a bug in the logic that determines missing "gaps" between two summaries, that never took effect before. 

I'll still test the fix a bit more extensively on my own instance before I publish a new release.

Btw., the "Clear & Regenerate" thing should have fixed the problem anyway. Did you try it?

**Comment by muety** [comment]
Do you, by chance, keep log files on your server? And if yes, does the Wakapi logs contain an entry reading like `failed to generate summary ...` on 04/09 or 04/10?

**Comment by muety** [comment]
Found the reason why the summary was missing. There was another tiny :bug:.

**Comment by Daste745** [comment]
Thank you for your very fast follow up!

> Btw., the "Clear & Regenerate" thing should have fixed the problem anyway. Did you try it?

Yup, I used it just after creating the dump. It fixed my issue and the summary seams to be correct now.
If there is anything I could provide to further investigate this issue (if stuff happens to still break) I would be happy to do so!

Thanks again for the good work. I'm loving the project and it just keeps on giving.
