### ISSUE TITLE
Overlapping custom mappings can lead to wrong language assignments

### ISSUE THREAD

**Issue by tldev-de** [muety/wakapi#172]
Hi muety,

using your public instance at wakapi.dev I stumbled across the following problem:

When I create two overlapping custom mappings, the first match is used to assign the language. This leads to some unexpected behaviour, as I will show in the following example:

Let's assume the following custom mappings:
- `.php` -> PHP7
- `.blade.php` -> Blade

A file `sample.blade.php` will match the first custom mapping and will be assigned to the language "PHP7", while I would expect it to be assigned to the language "Blade".

A solution might be to sort the custom mappings by complexity (e.g. the count of dots in the file extension string).

I realise that this is probably not a common problem. Nevertheless, it might by unexpected for users.

**Comment by muety** [comment]
Thanks for bringing this up! Even more interestingly, as the order in which the mappings are resolved in case multiple matches exist is non-deterministic, there will be different total durations for "PHP7" and "Blade" every time you refresh the page. I'll fix this.
