### ISSUE TITLE
Prevent overlapping summaries

### ISSUE THREAD

**Issue by muety** [muety/wakapi#179]
Currently, nothing prevents the application or user from inserting two or more summaries for an identical or overlapping time span and they would be added up in `mergeSummaries()`.

First, the merging logic should be extended to take care of duplicates.

Second, duplicate summaries shall be prevented in the first place. A necessary, but not necessarily sufficient restriction would be to place a unique constraint on `summary.[user_id,from_time]` and specify an according `ON CONFLICT` clause for inserts to update the existing row.

Keep in mind that retroactively adding that constraint [won't work with SQLite](https://www.sqlite.org/omitted.html), so we can't strictly rely on it to be present.

**Comment by YC** [comment]
Steps to reproduce:
1. Start from normal state. 
2. Click Clear and Regenerate twice. 
3. Wait for CPU usage to die down. 
4. Summary page, All time. 
5. Total/project statistics is many times the normal.
6. Clear and Regenerate. Wait for CPU usage to die down. 
7. Total/project statistics is still abnormal.

**Comment by muety** [comment]
Ah, so you hit "Regenerate" twice immediately in a row? This probably kicked off two parallel aggregation processes, both of which independently inserted their results in the end.

**Comment by muety** [comment]
Alright so I was able to reproduce everything until step 5. However, after regenerating the summaries once again, total time was back to normal. Was your total time from step 7 different from step 5 or was it the same? And can you remember the the divergences between 1, 5 and 7?

**Comment by YC** [comment]
v1.26.5, SQLite
Step 1: 626 hours, 52 minutes
Step 5: 1870 hours, 34 minutes
Step 7: 1963 hours, 7 minutes
To be sure, I cleared and regenerated again. 
2589 hours, 10 minutes

**Comment by muety** [comment]
I changed a few things. First, no two aggregation jobs can run at the same time. Second, the set of summaries is made unique based on a summary's start date before merging, which is not entirely sufficient, but should help prevent most issues.

Besides, here are two queries you can run on your database to clean up duplicate summaries:

```sql
# Find all duplicates (jfyi)
SELECT from_time, to_time, user_id, COUNT(*) FROM summaries GROUP BY from_time, to_time, user_id HAVING COUNT(*) > 1;

# Delete all duplicates (make a backup first, just in case)
DELETE FROM summaries WHERE id NOT IN (
    SELECT MIN(id) as id FROM summaries GROUP BY from_time, to_time, user_id
);
