### ISSUE TITLE
🎨 Redesign (ideas?)

### ISSUE THREAD

**Issue by muety** [muety/wakapi#183]
**Any designers or creative devs here?**

Sooner or later the web interface needs to be redesigned, especially as new features like #166, #173 and #182 are added. What I personally like about the current UI is the fact that's it's fairly minimalist. However, with these additional features, some kind of navigation and different views need to be introduced.

In principle, I like _hakatime_'s user interface, but it looks somewhat too "standard" to me.

![](https://raw.githubusercontent.com/mujx/hakatime/master/img/overview.png)

So my wishes regarding a new UI include:
* Have some kind of navigation between different views
* Still keep it as simple, stupid and minimalist as possible
* Dark theme by default
* No standard Bootstrap or Material UI look
* Preferably realizable with nothing but Tailwind

If somebody has a cool idea for a new design, feel free to share your thoughts, mock-ups and links to other web apps that could serve as an inspiration! :unicorn:

**Comment by MeerBiene** [comment]
Maybe use the redesign as opportunity to seperate the coding stats backend and the web interface. I'd suggest going with something lightweight like [svelte](https://svelte.dev/) because it compiles a static "vanilla" webapp that can be serverd with any static file server like nginx.

**Comment by muety** [comment]
Fair point. I already considered turning Wakapi into a single-page application couple of times. However, this would make things more complex and would introduce quite a bit of development overhead at the interface between backend and frontend. I tend to more and more like the "traditional" approach of server-rendered web apps again – not least because of usually better performance – and only have separate backend and frontend (using tools like Vue or Svelte) if really needed.

**Comment by muety** [comment]
May also be inspired by https://codetime.datreks.com

**Comment by muety** [comment]
I kind of like the UI design of [gohornet/hornet](https://github.com/gohornet/hornet)

![image](https://user-images.githubusercontent.com/8978843/123597254-636c5180-d7f3-11eb-86a6-272f7c724c73.png)

**Comment by muety** [comment]
Definitely wanna for [tabler/tabler](https://github.com/tabler/tabler).

**Comment by MeerBiene** [comment]
^ I approve this. If you happen to decide to rewrite the frontend as SPA (and with svelte) I'd be happy to help

**Comment by muety** [comment]
Another design inspiration from Pirsch Analytics:

![Screenshot from 2021-09-29 15-45-56](https://user-images.githubusercontent.com/8978843/135281114-89cbb2f7-8ea2-4834-9f88-f8822c5b1189.png)
