### ISSUE TITLE
Built binary can't be used in other directories than project root

### ISSUE THREAD

**Issue by dashezup** [muety/wakapi#186]
OS: Void Linux (glibc) (same issue on musl)

I'm trying to package it but the binary I built looks like not "portable", it only works under the project root.

**compile**: (same output as just `go bulid -o wakapi`)
```
$ GO111MODULE=on go build -v .
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

**run after built**, before `cp config.default.yml config.yml`:
```
$ ./wakapi
2021-04-25T04:32:45.057836903Z [ERROR] failed to find config file at 'config.yml'
panic: failed to find config file at 'config.yml'

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00000e0d8, 0xccd1d1, 0x22, 0xc000198be0, 0x1, 0x1)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:59 +0x8e
github.com/emvi/logbuch.(*Logger).Fatal(0xc0000d6180, 0xccd1d1, 0x22, 0xc000198be0, 0x1, 0x1)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/config.mustReadConfigLocation(0xc000159980, 0xc000198bc0)
        /home/username/src/wakapi/config/config.go:309 +0xfc
github.com/muety/wakapi/config.Load(0xcb75b0, 0x7, 0x41bd97)
        /home/username/src/wakapi/config/config.go:343 +0xd7
main.main()
        /home/username/src/wakapi/main.go:92 +0x5
```

works fine after `cp config.default.yml config.yml`.

**throws error when I move the binary along with `config.yml` to another directory and run it**

```
2021-04-25T04:38:33.465365349Z [ERROR] unexpected end of JSON input
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0000a60c0, 0xcc85a9, 0x1c, 0x0, 0x0, 0x0)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:57 +0xc5
github.com/emvi/logbuch.(*Logger).Fatal(0xc0000f8180, 0xcc85a9, 0x1c, 0x0, 0x0, 0x0)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
        /home/username/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/config.readColors(0xcb75b0)
        /home/username/src/wakapi/config/config.go:301 +0x167
github.com/muety/wakapi/config.Load(0xcb75b0, 0x7, 0x41bd97)
        /home/username/src/wakapi/config/config.go:349 +0x265
main.main()
        /home/username/src/wakapi/main.go:92 +0x5e
```

**Comment by dashezup** [comment]
```
# Adapt config to your needs
$ cp config.default.yml config.yml
$ vi config.yml

# Build the executable
$ go build -o wakapi

# Run it
$ ./wakapi
```

And I'm a bit confused by this, `config.yml` file is not required at compile time, right? if so then maybe change the order to this in README

```
# Build the executable
$ go build -o wakapi

# Adapt config to your needs
$ cp config.default.yml config.yml
$ vi config.yml

# Run it
$ ./wakapi
```

**Comment by muety** [comment]
Thanks for your feedback. You're right, the config file is not required at compile time as this would contradict its whole purpose. However, a few other static assets are, one example being `data/colors.json` or `views/*.tpl.html`. Those files are compiled into the binary. However, to ease the development process, these files are still attempted to be loaded from your local file system while you are in `dev` mode. Switching to `env: prod` should resolve your issue and make the application boot up even if the binary is separated from its code.

> if so then maybe change the order to this in README

I'll update it.

**Comment by dashezup** [comment]
> Switching to env: prod should resolve your issue

Yes setting `ENVIRONMENT=prod` or `env: prod` solved the issue. I'll use `sed` to edit `config.yml` before build wakapi.

How does the GitHub workflow builds it as a production build instead of development build?

**Comment by muety** [comment]
> I got it. `ENVIRONMENT=prod` or `env: prod` does not make a difference on builds. but it changes the behavior of `wakapi` binary at runtime to load extra files or not.

Exactly! Glad you were able to figure it out.
