### ISSUE TITLE
Debug non-received/handled data

### ISSUE THREAD

**Issue by deurk** [muety/wakapi#187]
Is there a way to simulate an IDE client sent data to Wakapi ?
I've been trying to run Wakapi with podman and I don't seem to pinpoint where the issue lie.

Any way to debug from Wakapi and test with an direct API request ?

Thanks a lot.

**Comment by muety** [comment]
Hu @deurk! For debugging, you might want to check out [sample_data.py](https://github.com/muety/wakapi/blob/master/scripts/sample_data.py) to generate and insert fake heartbeats as well as [this Postman collection](https://github.com/muety/wakapi/tree/master/postman) as an example of how to manually make heartbeat requests.

**Comment by deurk** [comment]
Thanks a lot for your prompt answer, I will try this now and report :)

**Comment by deurk** [comment]
I am correctly able to send heartbeats from Postman using your collection (very convenient, thank you) and I can see it arrive on the pod instance (as a POST request). However, is a `{"responses":[[null,201]]}` response normal ?

The Wakapi instance does not show the example data (go project) when refreshed, even though it now displays empty graphs.

**Comment by deurk** [comment]
Nevermind, testing with today's timestamp works way better. So it seems issues does not lie with my instance, but rather with the VSCode plugin (although it works fine with Wakatime and your dev instance).

Any pointer for me?

**Comment by deurk** [comment]
I see an occasional message
`2021-04-25T13:06:47.030668182Z [ERROR] error while writing json response: json: unsupported value: +Inf`

**Comment by muety** [comment]
> However, is a `{"responses":[[null,201]]}` response normal ?

Yes, although it looks kinda weird, this is actually what _wakatime-cli_ [expects](https://github.com/wakatime/wakatime/blob/2e636d389bf5da4e998e05d5285a96ce2c181e3d/wakatime/api.py#L288).

> Any pointer for me?

Can you please tell me, what Wakapi version are you using (and when compiled from source, what's your latest commit hash) and with what database? Could you take a peek into your database and see what (if any) heartbeat was actually inserted? This would help me debug the issue.

**Comment by deurk** [comment]
Sure thing, I used the latest version of the docker image `n1try/wakapi` (1.26.5).

To be clearer: Postman heartbeats work as intended, they do appear in Wakapi. VSCode extension does not seem to add any heartbeats, although just by changing its `api_url` and `api_key` to your dev public Wakapi it works flawlessly.

I do not know when the message appears exactly, I'll try to monitor to correlate with any action I might have but so far have not found its origin.

**Comment by deurk** [comment]
You can also directly fiddle with the instance for tests if you want, I opened registration: https://wakapi.owndesign.net/

**Comment by muety** [comment]
That is weird. Can you check what's in your database? I assume you're using the SQLite, which you can best view with a [tool like this](https://sqlitebrowser.org/).

> I'll try to monitor to correlate with any action I might have but so far have not found its origin.

Keep me posted and maybe open another bug ticket here once you were able to figure out how to reproduce it.

Btw., if you had any kinds of issues running Wakapi with Podman, feel free to share your thoughts here, maybe someone finds it helpful.

**Comment by deurk** [comment]
Only the manually generated entries appear in there
![image](https://user-images.githubusercontent.com/498032/116004382-cc242b80-a602-11eb-91bb-16a591225c2b.png)

**Comment by muety** [comment]
Alright. The VSCode plugin can't be the problem as heartbeats are successfully sent to Wakapi.dev or WakaTime, right? Your instance itself can't be the problem as well (Firewall, etc.), as you're able to send heartbeats from Postman. What's left in between is only the `wakatime.cfg` config pointing to your instance, but I assume it is properly configured as well?

Maybe `~/.wakatime.log` (you'll need to figure out what's the Windows equivalent of that file) has something useful to tell?

**Comment by muety** [comment]
I configured your instance on my machine for testing and it looks like my heartbeats from GoLang and VSCode are properly sent. Must be some weird configuration issue on your machine.

**Comment by deurk** [comment]
Must be local to my VSCode instance indeed then, thanks for taking the time go try to troubleshoot. I'll keep digging.

**Comment by muety** [comment]
Sure, I'd suggest to check `wakatime-cli`'s logs.

**Comment by muety** [comment]
> I see an occasional message
> `2021-04-25T13:06:47.030668182Z [ERROR] error while writing json response: json: unsupported value: +Inf`

This should be resolved with the latest release.

Did you manage to solve your plugin problem?

**Comment by deurk** [comment]
> This should be resolved with the latest release.
Great to hear, thanks !

> Did you manage to solve your plugin problem?
Yup, trouble was a local DNS as I have a split view configuration of the domain name, forgot to update internal DNS (hence why it worked fine with your dev instance and Wakatime). All solved, thanks a lot for your help !
