### ISSUE TITLE
WakaTime compatible summaries API incorrectly reporting missing `start` parameter

### ISSUE THREAD

**Issue by devgianlu** [muety/wakapi#190]
Making the following request returns 400 `missing required 'start' parameter`:
```sh
curl -X GET "https://wakapi.dev/api/compat/wakatime/v1/users/current/summaries?start=2021-02-07&end=2021-02-08" -H  "accept: application/json"
```

There's probably an issue with the date parsing:
https://github.com/muety/wakapi/blob/5d8fc99b933c5caacfe842931414ca320d4df3f7/routes/compat/wakatime/v1/summaries.go#L102-L105

I am currently trying to add support for wakapi in my WakaTime app, see https://github.com/devgianlu/Timeless/issues/37 and https://github.com/devgianlu/Timeless/pull/38

**Comment by muety** [comment]
Hi @devgianlu!

> I am currently trying to add support for wakapi in my WakaTime app

Awesome! Let me know if you need any kind of help.

Regarding your issue: I recently changed the required format of date parameters to `RFC3339` to have time zone information included, but wasn't aware that this would break WakaTime compatibility. I'll push a fix soon, stay tuned!
