### ISSUE TITLE
Wakatime compatible summaries API returns no data for `start` and `end` on the same day

### ISSUE THREAD

**Issue by devgianlu** [muety/wakapi#192]
Requesting `https://wakapi.dev/api/compat/wakatime/v1/users/current/summaries?start=2021-04-29&end=2021-04-29` returns:

```json
{"data":[],"end":"0001-01-01T00:00:00Z","start":"2021-04-29T10:31:15.931236156+02:00"}
```

The official API will return one summary for the given day.

The problem definitely lies in this function:
https://github.com/muety/wakapi/blob/331ace3c1e78ebdc30bdc7cd1e9b24e708595373/utils/date.go#L70-L83

`end` is wrong probably because the list of summaries produced is empty and it's not updated, but it should fix itself with the above:
https://github.com/muety/wakapi/blob/331ace3c1e78ebdc30bdc7cd1e9b24e708595373/models/compat/wakatime/v1/summaries.go#L64-L73

This should also fix the CLI command `--today` used to show the status bar in IntelliJ IDEs (https://github.com/wakatime/wakatime/blob/e8deb156f1c2d26e5cf874da97f7b4354b3f5d20/wakatime/api.py#L165).

P.S. I am mainly pointing out where the problem is and not making PRs because I'd like to avoid setting up a development environment, but I might at some point to add some functionalities if you like.

**Comment by muety** [comment]
Thanks, I pushed an update that should have fixed the issue. Please check. However, we still do not have 100 % API compatibility with WakaTime, unfortunately. See #58.

> This should also fix the CLI command --today used to show the status bar in IntelliJ IDEs

No, unfortunately, the CLI still has hard-coded API endpoints, to the plugins' status bars won't work until https://github.com/wakatime/wakatime/issues/260 is resolved.

**Comment by muety** [comment]
> The other endpoint needed for the app to work properly would be the user endpoint

I'll have a look tomorrow!
