### ISSUE TITLE
Wakatime durations endpoint returns user data

### ISSUE THREAD

**Issue by devgianlu** [muety/wakapi#194]
Requesting `https://wakapi.dev/api/compat/wakatime/v1/users/current/durations?date=2021-04-30` will return the same as `https://wakapi.dev/api/compat/wakatime/v1/users/current` instead of `404`.

**Comment by muety** [comment]
Thanks, didn't notice that before. I pushed a fix. Please check.

**Comment by devgianlu** [comment]
It's fixed now.

Just published version 2.4.0 of [Timeless](https://github.com/devgianlu/Timeless) with Wakapi support! Thank you again for the fast fixes.

**Comment by muety** [comment]
Awesome! I'll give it try. Btw., it would be cool to have pre-built APKs as part of the GitHub releases of Timeless. Are you planning on including them?

**Comment by devgianlu** [comment]
I've spent the last our or so trying to get Github Actions to build the foss APK (which I am doing for other apps), but it refuses to compile... Will try again when possible.
