### ISSUE TITLE
Public API stats/today and stats/week returns empty data

### ISSUE THREAD

**Issue by dashezup** [muety/wakapi#199]
This works fine
`https://wakapi.dev/api/v1/users/{username}/stats/last_7_days`

But seems stats/today and stats/week always returns 405 with empty data
`https://wakapi.dev/api/v1/users/{username}/stats/today`
`https://wakapi.dev/api/v1/users/{username}/stats/week`

I've tried on my instance as well (wakapi `1.27.0`) , get the same result with "public data access range" set to 7 days or unlimited.

It's not implemented? btw I just noticed that wakatime does not have stats/today nor statas/week

**Comment by muety** [comment]
That is weird, I can't reproduce the error. I'm getting a 200 for those calls. All of these intervals should be supported:
https://github.com/muety/wakapi/blob/cf3d2936888893a3e9f06785bc37d8dcd1ab4756/models/interval.go#L5-L19

There actually was a different issue with the stats endpoint related to this potential division by zero.
https://github.com/muety/wakapi/blob/cf3d2936888893a3e9f06785bc37d8dcd1ab4756/models/compat/wakatime/v1/stats.go#L44

However, it didn't produce a 405 response for me.

Do you see some error message in your server's logs?

**Comment by dashezup** [comment]
URL: https://ezup.dev/wakapi/api/v1/users/dashezup/stats/today

yesterday's log on my instance (all of those are +Inf error)
```
2021-05-03_10:41:28.81828 2021-05-03T10:41:28.8181464Z [ERROR] error while writing json response: json: unsupported value: +Inf
2021-05-03_10:41:28.81842 2021-05-03T10:41:28.818400344Z [INFO ] [request] status=200, method=GET, uri=/api/v1/users/dashezup/stats/today, duration=13.40406ms, bytes=0, addr=**.***.***.**, user=dashezup
```
today's log (NaN error, I didn't have any stats yet)
```
2021-05-04_00:51:26.04225 2021-05-04T00:51:26.041976672Z [ERROR] error while writing json response: json: unsupported value: NaN
2021-05-04_00:51:26.04249 2021-05-04T00:51:26.042425328Z [INFO ] [request] status=200, method=GET, uri=/api/v1/users/dashezup/stats/today, duration=15.490884ms, bytes=0, addr=**.***.***.**, user=-
```

I just noticed that it returns 405 no matter if it returns data or not. (both on wakapi.dev and my instance), shouldn't it response with 200 instead when it response with data?

seems stats/today and stats/week works properly for wakapi.dev (returns data with 405), maybe I thought it didn't return data when I saw it return 405.

**Comment by dashezup** [comment]
With https://github.com/muety/wakapi/commit/f3b738b2509449d343113c3015e6a6dbfc93f2ea, stats/today and stats/week works on my instance now (returns 405 with proper json data).

**Comment by muety** [comment]
> shouldn't it response with 200 instead when it response with data?

Yes, it should and it actually does, at least for me. 

```bash
$ curl -s -i https://ezup.dev/wakapi/api/v1/users/dashezup/stats/today | head -1
HTTP/2 200
```

It's really weird.

**Comment by dashezup** [comment]
sorry, my bad, I tried `curl $URL` (get json data) and `curl -I $URL` (get HTTP code 405) and I thought it gots 405 and JSON data at the same time which is false.

`curl -i $URL` shows the response HTTP code is 200 with JSON data.

405 only occurs when it sends a header request. I just checked that with v1.27.0 it only returns 200 with empty data, not 405.
