### ISSUE TITLE
[Question] What is the unknown project?

### ISSUE THREAD

**Issue by hypervtechnics** [muety/wakapi#200]
See title.

![grafik](https://user-images.githubusercontent.com/10027956/117446943-20050d80-af3d-11eb-97b3-5a09f57f8217.png)

**Comment by muety** [comment]
What editor / IDE are you using? In general, "unknown" is set as a fallback if no project information was provided by the IDE. This happens, for instance, if you open a single file (e.g. `/tmp/file.go`) in VSCode, that is not part of a workspace or of a directory that has previously been opened as a whole folder in VSCode. Or, I believe, any file you edit with [micro](https://micro-editor.github.io/) is part of the "unknown" project, as no project context can be derived by the editor.

**Comment by hypervtechnics** [comment]
Must be the VS Code editor. Had some files opened there. Will keep an eye on it. Thank you for the reply! 😄
