### ISSUE TITLE
why is i try to intregrates  Wakapi with GitHub Readme Stats has this error?

### ISSUE THREAD

**Issue by jeffxjh** [muety/wakapi#202]
Something went wrong! file an issue at https://git.io/JJmN9
Wakatime user not found, make sure you have a wakatime profile

**Comment by muety** [comment]
Can you post the URL of your Readme Stats card which throws that issue?

**Comment by jeffxjh** [comment]
https://github-readme-stats.vercel.app/api/wakatime?username=xujh&api_domain=wakapi.jeffxjh.top&bg_color=2D3748&title_color=fafafa&icon_color=2F855A&text_color=ffffff&custom_title=My%20Stats%20%F0%9F%9A%80&layout=compact

**Comment by jeffxjh** [comment]
https://github-readme-stats.vercel.app/api/wakatime?username=xxx&api_domain=xxxxx&bg_color=2D3748&title_color=fafafa&icon_color=2F855A&text_color=ffffff&custom_title=My%20Stats%20%F0%9F%9A%80&layout=compact


what's the name is ,the wakatime username? or my host app username,i use deplay app regist username xxx confirm user not found why?

**Comment by muety** [comment]
Alright, so `username` must be the same which you use to log in to your Wakapi instance. `api_domain` must be the root URL of your Wakapi server, e.g. `wakapi.dev` in my case. Also, you need to have data sharing enabled in your settings. Set the interval to at least 7 days and enable to share languages, like this:

![image](https://user-images.githubusercontent.com/8978843/118351454-6b7e7380-b55c-11eb-9856-65bbe3452835.png)

If it doesn't help, also try to set the interval to `-1` (= unlimited).

**Comment by jeffxjh** [comment]
unfortunately,I did everything you said,still the same error.
![image](https://user-images.githubusercontent.com/44387640/118386099-7104b800-b647-11eb-8b02-08f207ff0143.png)
i login with username is correct my domain is correct ,i am hopeless.

**Comment by muety** [comment]
Would you mind sharing the full URL, without obfuscating username and API URL, so I can debug further?

**Comment by muety** [comment]
Did you manage to figure it out?

**Comment by jeffxjh** [comment]
after ask github-readme-stats author,i found  the domain mush has ssl. http://domain is not support! thank answer.
