### ISSUE TITLE
failed to insert imported heartbeat

### ISSUE THREAD

**Issue by SmallPepperZ** [muety/wakapi#206]
I'm setting up a wakapi instance and import data from wakatime, and I gave it a fresh database with no heartbeats, but when I tried to import my wakatime data with my wakatime api key, I get a slew of 
`[WARN ] failed to insert imported heartbeat, already existing? – too many SQL variables`
which is concluded with a 
```
[INFO ] downloaded 2084 heartbeats for user 'SmallPepperZ' (0 actually imported)
[INFO ] clearing summaries for user 'SmallPepperZ'
[INFO ] generating summaries
```
and the wakatime data is never actually imported to the wakapi database. When I tried doing the data import on https://wakapi.dev, it worked fine

**Comment by muety** [comment]
Thanks for bringing this up! I'll investigate as soon as possible and keep you posted. Sorry for the inconveniences.

I assume you are using an SQLite database?

**Comment by SmallPepperZ** [comment]
Yes, it is using a sqlite database, and the only things I changed in the config were disabling the email setup and adding a password salt

**Comment by muety** [comment]
Sorry, I'm super busy right now. I'll fix this at latest on Friday. Stay tuned.

**Comment by muety** [comment]
Alright, the problem was related to the amount of data SQLite can handle within one transaction. I set the default batch size for importing heartbeats from 100 to 50. You can either pull the latest version or simply adapt the `app.import_batch_size` in your config.
