### ISSUE TITLE
Status 401

### ISSUE THREAD

**Issue by Mte90** [muety/wakapi#208]
I added support for the kate plugin for wakatime to the `api_url` parameter https://github.com/Tatsh/kate-wakatime/pull/17/files

If I use the key and domain of wakatime works but with https://wakapi.dev is not working and I got that error.

```
wakatime: Status code: 401
wakatime: Request did not succeed, status code: 401
```

**Comment by muety** [comment]
Hi @Mte90, thanks for bringing this up. Can you tell which exact request is returning the aforementioned error code? And what did you set `api_url` to in your tests?

**Comment by muety** [comment]
Btw., I quickly checked your PR. I'm not familiar with the Kate code base at all and I barely speak C++, but are you sure about the following line? Isn't this rather supposed to be the heartbeats endpoint, instead of `/actions`? 

https://github.com/Tatsh/kate-wakatime/pull/17/files#diff-0a88dbe992275cd658f87a62b0de53f3a9956b598a3a320d5682e8f765964e8bR406

Shouldn't make a difference for your `401` error issue though.

**Comment by Mte90** [comment]
You are right I updated the PR with the original code for the heartbeat.
The issue is still there :-/

**Comment by muety** [comment]
> Hi @Mte90, thanks for bringing this up. Can you tell which exact request is returning the aforementioned error code? And what did you set `api_url` to in your tests?

Would be interesting to have these information.

**Comment by Mte90** [comment]
It was something that I was trying to get achieve too but I am not so expert with C++ too.
I will check again.

**Comment by muety** [comment]
`api_url` is supposed to be `https://wakapi.dev/api`.

I quickly checked the server logs. Looks like Wakapi.dev API didn't return a single `401` within the last couple of hours. Maybe your request's aren't even reaching through? 

Let me know how I can provide further assistance.

**Comment by Mte90** [comment]
Well I see that I set the domain off wakatime works, if I set this one is not working:
```
wakatime: Status code: 401
wakatime: URL: "https://wakatime.com/api/v1/users/current/heartbeats.bulk"
wakatime: Request did not succeed, status code: 401
```

**Comment by muety** [comment]
This doesn't even seem to use wakapi.dev, but wakatime.com instead, right? Since you still get a 401 here, something might be wrong with your API key or so?

**Comment by Mte90** [comment]
Now works, thanks for the help!
