### ISSUE TITLE
heartbeats (non-bulk) API does not match WakaTime

### ISSUE THREAD

**Issue by Tatsh** [muety/wakapi#212]
I have verified that my plugin Kate WakaTime works with the real WakaTime host on the `/api/v1/users/current/heartbeat` endpoint with a JSON object that is not an array. It appears your endpoint only accepts an array even though it's not the bulk API. As a result, my plugin is getting a 401 from my locally run instance of Wakapi.

- [Decode JSON into array object](https://github.com/muety/wakapi/blob/ee31212cdd69c160632532365956ff4e7a2b4725/routes/api/heartbeat.go#L67)
- [Iterate it. What does this do since you decoded pointing to an array but the value is not an array?](https://github.com/muety/wakapi/blob/ee31212cdd69c160632532365956ff4e7a2b4725/routes/api/heartbeat.go#L73)

Are you missing a step to insert the decoded JSON as a `models.Heartbeat` object into the array of them?

**Comment by Tatsh** [comment]
[The API docs](https://wakatime.com/developers#:~:text=Creates%20a%20heartbeat%20representing%20activity%20for%20a%20user.%20The%20bulk%20endpoint%20accepts%20an%20array%20of%20heartbeats%2C%20limited%20to%2025%20per%20POST%20request.) state that the bulk endpoint accepts an array, but does not say that about the non-bulk endpoint.

**Comment by muety** [comment]
You're absolutely right, currently, the endpoint only accepts an array of heartbeats. There used to be a single-heartbeat endpoint, but apparently got lost somewhere on the way. Nobody seems to have recognized, as even the WakaTime CLI itself only uses the bulk endpoint. 

I'll fix this asap. In the meantime, you could simply use the bulk endpoint and just send an array of length 1 as a quick fix.

Thanks for bringing this up!
