### ISSUE TITLE
[Question]How can i merge the editors?

### ISSUE THREAD

**Issue by mxarcher** [muety/wakapi#221]
![图片](https://user-images.githubusercontent.com/44336929/126683054-13f8da18-5c4b-40c9-bfbb-9238e18fd095.png)
after importing my data from wakatime, this happened. So how can i merge these.

**Comment by muety** [comment]
Go to _Settings_ -> _Aliases_ and add a mapping from one editor to the other.

**Comment by mxarcher** [comment]
OK, it works. thank you. I didn't use it carefully
