### ISSUE TITLE
Getting 404 not found on /api address

### ISSUE THREAD

**Issue by AlexandroPerez** [muety/wakapi#224]
So I got my own server running, but then I found out I couldn't connect my VS Code Waka time plugin to it. Started seeing `404 page not found` messages in `~/.wakatime.log`, and when I tried to access the /api address but I get the same 404 response.

Thinking is a problem on my server setup, I tried creating an account on wakapi.dev, but even there I can't get things to work.  And https://wakapi.dev/api also gives me a 404 error.

The plugin in VS code keeps saying is working offline. This is what my `.wakapi.cfg` looks like:

```
[internal]
cli_version = v1.18.9
cli_version_last_modified = Tue, 06 Jul 2021 00:43:45 GMT
[settings]
debug = true
api_url = https://wakapi.dev/api
api_key = ********-****-****-****-************
```

I also noticed that the logs keep trying to use `api.py`, which I'm not sure if this has something to do with another [issue having to do with hardcoded api urls](https://github.com/muety/wakapi/issues/153#issuecomment-811836233) found in older version of the wakatime cli, but this is what the latest VS Code plugin is using for me. I don't know how to get their latest golang cli

This is the output of the log, which keeps repeating every now and then, which means the cli is trying to connect, but it keeps repeating the 404 warning, I'm guessing:

```json
{
  "now": "2021/07/31 22:20:28 -0500",
  "version": "13.0.7",
  "plugin": "vscode/1.58.2 vscode-wakatime/14.0.3",
  "time": 1627788027.9304605,
  "caller": "wakatime/api.py",
  "lineno": 45,
  "file": "/home/alex/playground/index.ts",
  "level": "DEBUG",
  "message": "Sending heartbeats to api at https://wakapi.dev/api"
}

{
  "now": "2021/07/31 22:20:28 -0500",
  "version": "13.0.7",
  "plugin": "vscode/1.58.2 vscode-wakatime/14.0.3",
  "time": 1627788027.9304605,
  "caller": "wakatime/api.py",
  "lineno": 51,
  "file": "/home/alex/playground/index.ts",
  "level": "DEBUG",
  "message": "[{'time': 1627788027.9304605, 'entity': '/home/alex/playground/index.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'playground', 'branch': 'main', 'language': 'TypeScript', 'dependencies': [], 'lines': 3, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.4) Python3.8.0.final.0 vscode/1.58.2 vscode-wakatime/14.0.3'}]"
}

{
  "now": "2021/07/31 22:20:28 -0500",
  "version": "13.0.7",
  "plugin": "vscode/1.58.2 vscode-wakatime/14.0.3",
  "time": 1627788027.9304605,
  "caller": "wakatime/api.py",
  "lineno": 339,
  "file": "/home/alex/playground/index.ts",
  "level": "WARNING",
  "message": "{'response_code': 404, 'response_content': '404 page not found\\n'}"
}
```

**Comment by YC** [comment]
#214 might help

**Comment by muety** [comment]
Hi @AlexandroPerez! Firstly, the config file's name is supposed to be `.wakatime.cfg` instead of `.wakapi.cfg`. Apart from that, it seems like you are using the "legacy" Python-based WakaTime CLI (at version 13.0.7). In this case, please try to set `api_url = https://wakapi.dev/api/heartbeats`. Let me know if this helps.

**Comment by AlexandroPerez** [comment]
Thanks @muety! That actually worked. About the file name, you're right is `.wakatime.cfg`, I miswrote it here.

Spent 2 days trying to get wakapi to work on a shared server (so no sudo) getting it to work with an nginx configuration in a separate namespace (no localhost), and then when I finally got it to work, it failed me with this, so was tired. I learned the hard way the difference between backend and frontend.

I left it running with `sqlite`, but since it's going to be used only by me I hope there are now drawbacks. Is possible to install `mysql`, but I don't know if there are any advantages to do it for only one user. Also, I was thinking of just graving a copy of the `db` file every now and then, and I've got a backup. What do you think? , 

I hope the VS Code plugin updates to the new CLI, and when it does I know what to change.

With these the issue can be closed, but should something be written on the README or docs about the way to deal with this if any plugin still uses the "legacy" wakatime cli?

**Comment by muety** [comment]
> Is possible to install mysql, but I don't know if there are any advantages to do it for only one user.

For a single-user instance I'd just stick with SQLite for the sake of simplicity. There won't be any noticeable performance drawbacks.

> Also, I was thinking of just graving a copy of the db file every now and then, and I've got a backup. What do you think?

Absolutely recommendable!

> I hope the VS Code plugin updates to the new CLI, and when it does I know what to change.

Actually, please try changing `/api/heartbeats` into `/api/heartbeat`, because then the stripping mentioned in https://github.com/muety/wakapi/issues/203#issuecomment-858009349 will take place, i.e. this API URL should work for legacy and new CLI version likewise.

> [...] should something be written on the README or docs about the way to deal with this if any plugin still uses the "legacy" wakatime cli?

Fair point, I'll think about it as you're not the first one to face this issue.
