### ISSUE TITLE
Interface visual bug(s)

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/wakapi#232]
# Bug
The Interface looks broken

### How it should look (Firefox)
![image](https://user-images.githubusercontent.com/66328166/131228680-b1e525c7-4d6a-4057-92e4-f1160a2f0c68.png)

### How it looks on Brave
![image](https://user-images.githubusercontent.com/66328166/131228700-d34bfacb-5622-4939-9d49-919bf0a304a3.png)

Both browsers give me an error:
```js
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at summary:228
```
Browsers are both up-to-date (with Manjaro-repo)

# System information
Version `v1.29.4` on Docker
Database isn't important

**Comment by mawoka-myblock** [comment]
Btw: Why is the time displayed in seconds, not in minutes or hours?

**Comment by muety** [comment]
Thanks for bringing this up, @mawoka-myblock. Console errors and the wrongly formatted x-axis should be fixed now. I couldn't reproduce the distorted chart legend labels. This is probably an issue with Chart.js and might get resolved with #235.

**Comment by mawoka-myblock** [comment]
The bug is from ChartsJs. I experiencing the same issue with plausible. Do you think, @muety I should open an issue in the ChartsJs-repo?

**Comment by muety** [comment]
If you are able to reproduce it in a minimal example code definitely file an issue there.

**Comment by mawoka-myblock** [comment]
https://github.com/chartjs/Chart.js/issues/9623

**Comment by mawoka-myblock** [comment]
@muety It is the Brave-AdBlocker
