### ISSUE TITLE
Upgrade to Chart.js 3.x

### ISSUE THREAD

**Issue by muety** [muety/wakapi#235]
We are currently using 2.9.4, which is the latest 2.x version. To benefit from the very latest changes to the library, we should consider upgrading to 3.x. However, I assume there have been breaking changes, so the upgrade will probably take non-trivial refactoring effort.

**Comment by mawoka-myblock** [comment]
I'm having a look at the migration and I'll note which things have to be changed/which I have changed:
- [x] default colors: https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#defaults
- [ ] Chart-tpye removed: https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#defaults

**Comment by muety** [comment]
Done with #236
