### ISSUE TITLE
Exposing git branch data through RESTful API

### ISSUE THREAD

**Issue by emansom** [muety/wakapi#240]
Hi! Awesome project! Appreciate you didn't pay the $9.

I'd like to use this project for synchronizing what I've done daily, to a internal company time sheet system.
To be able to accurately determine what ticket was worked on, I need access to what branches were worked on in which projects.
We use branch naming schemes tied to Redmine tickets. e.g. `feat-23453` as branch name.

Is exposing raw heartbeats within the summary endpoint a possibility?

**Comment by muety** [comment]
Hi, thanks for your input! Right now, this is not possible. But I created #241 and #242 to keep track of your feature requests. Hopefully, I'll have time to jump onto this soon.

**Comment by muety** [comment]
I'm closing this issue, if it's ok for you? Please just subscribe to the two new ones instead.
