### ISSUE TITLE
Branch statistics 

### ISSUE THREAD

**Issue by muety** [muety/wakapi#242]
Support summaries per Git branch.

**Comment by muety** [comment]
Requires #262

**Comment by muety** [comment]
Branch statistics are shown per project. To view them, you need to click on a specific project in the projects chart on the dashboard. Hope that helps.

**Comment by mikkel1156** [comment]
> Branch statistics are shown per project. To view them, you need to click on a specific project in the projects chart on the dashboard. Hope that helps.

Was checking out the feature today, but it doesn't seem to be showing the other branch. I can see that it shows _2_, if I decrease it to _1_, the main branch seen below disappears.
![image](https://user-images.githubusercontent.com/36984522/154751405-22b46dcc-4b3b-4b04-94d7-f8b603411f71.png)

Don't know much about the backend, but I checked the database and can see that there are heartbeats with the other branch name. The time indicator under the project title is also showing correctly.

**Comment by muety** [comment]
Good catch, this is a bug with the user interface! I'll fix asap.
