### ISSUE TITLE
`Error: Unauthorized` when logging in

### ISSUE THREAD

**Issue by NickAcPT** [muety/wakapi#25]
I've updated to 1.2.5 and I'm getting this error after trying to log in:
![error](https://i.imgur.com/R2p18hZ.png)

<details>
<summary>Console log on prod=dev</summary>

```
PS D:\Software\WakAPI> .\wakapi.exe                                                                              2020/05/28 03:34:41 main.go:152: Applied 0 migrations!

[35m(D:/wakapi/services/user.go:60)[0m
[33m[2020-05-28 03:34:41][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE "users"."id" = 'admin' AND (("users"."id" = 'admin')) ORDER BY "users"."id" ASC LIMIT 1
[36;31m[1 rows affected or returned ][0m
2020/05/28 03:34:41 main.go:194: default user 'admin' already existing

[35m(D:/wakapi/main.go:172)[0m
[33m[2020-05-28 03:34:41][0m  [36;1m[0.00ms][0m  UPDATE "heartbeats" SET "language" = 'Vue'  WHERE (language = '') AND (entity LIKE '%.vue')
[36;31m[0 rows affected or returned ][0m
2020/05/28 03:34:41 aggregation.go:84: Generating summaries.
2020/05/28 03:34:41 main.go:137: Listening on 127.0.0.1:3000

[35m(D:/wakapi/services/heartbeat.go:73)[0m
[33m[2020-05-28 03:34:41][0m  [36;1m[0.00ms][0m  DELETE FROM "heartbeats"  WHERE (time <= '2020-05-26 00:00:00')
[36;31m[0 rows affected or returned ][0m

[35m(D:/wakapi/services/user.go:43)[0m
[33m[2020-05-28 03:34:41][0m  [36;1m[0.99ms][0m  SELECT * FROM "users"
[36;31m[2 rows affected or returned ][0m
2020/05/28 03:34:41 heartbeat.go:85: Successfully cleaned up heartbeats older than 2020-05-26 00:00:00 +0100 BST

[35m(D:/wakapi/services/summary.go:154)[0m
[33m[2020-05-28 03:34:42][0m [31;1m sql: Scan error on column index 1, name "to_time": unsupported Scan, storing driver.Value type string into type *time.Time [0m

[35m(D:/wakapi/services/summary.go:154)[0m
[33m[2020-05-28 03:34:42][0m  [36;1m[0.99ms][0m  SELECT user_id, max(to_time) as to_time FROM "summaries"   GROUP BY user_id
[36;31m[1 rows affected or returned ][0m
2020/05/28 03:34:42 aggregation.go:94: sql: Scan error on column index 1, name "to_time": unsupported Scan, storing driver.Value type string into type *time.Time
127.0.0.1 - - [28/May/2020:03:34:44 +0100] "GET / HTTP/1.1" 200 3275
127.0.0.1 - - [28/May/2020:03:34:44 +0100] "GET /assets/app.css HTTP/1.1" 200 89
127.0.0.1 - - [28/May/2020:03:34:44 +0100] "GET /assets/app.js HTTP/1.1" 200 7812

[35m(D:/wakapi/services/user.go:25)[0m
[33m[2020-05-28 03:34:51][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE ("users"."id" = 'nickac') ORDER BY "users"."id" ASC LIMIT 1
[36;31m[1 rows affected or returned ][0m
127.0.0.1 - - [28/May/2020:03:34:51 +0100] "POST /login HTTP/1.1" 401 3218
127.0.0.1 - - [28/May/2020:03:34:52 +0100] "GET /assets/app.css HTTP/1.1" 200 89
(base) PS D:\Software\WakAPI> .\wakapi.exe                                                                              2020/05/28 03:35:31 main.go:152: Applied 0 migrations!

[35m(D:/wakapi/services/user.go:60)[0m
[33m[2020-05-28 03:35:31][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE "users"."id" = 'admin' AND (("users"."id" = 'admin')) ORDER BY "users"."id" ASC LIMIT 1
[36;31m[1 rows affected or returned ][0m
2020/05/28 03:35:31 main.go:194: default user 'admin' already existing

[35m(D:/wakapi/main.go:172)[0m
[33m[2020-05-28 03:35:31][0m  [36;1m[0.00ms][0m  UPDATE "heartbeats" SET "language" = 'Vue'  WHERE (language = '') AND (entity LIKE '%.vue')
[36;31m[0 rows affected or returned ][0m
2020/05/28 03:35:31 aggregation.go:84: Generating summaries.
2020/05/28 03:35:31 main.go:137: Listening on 127.0.0.1:3000

[35m(D:/wakapi/services/heartbeat.go:73)[0m
[33m[2020-05-28 03:35:32][0m  [36;1m[0.00ms][0m  DELETE FROM "heartbeats"  WHERE (time <= '2020-05-26 00:00:00')
[36;31m[0 rows affected or returned ][0m
2020/05/28 03:35:32 heartbeat.go:85: Successfully cleaned up heartbeats older than 2020-05-26 00:00:00 +0100 BST

[35m(D:/wakapi/services/user.go:43)[0m
[33m[2020-05-28 03:35:32][0m  [36;1m[1.99ms][0m  SELECT * FROM "users"
[36;31m[1 rows affected or returned ][0m

[35m(D:/wakapi/services/summary.go:154)[0m
[33m[2020-05-28 03:35:32][0m [31;1m sql: Scan error on column index 1, name "to_time": unsupported Scan, storing driver.Value type string into type *time.Time [0m

[35m(D:/wakapi/services/summary.go:154)[0m
[33m[2020-05-28 03:35:32][0m  [36;1m[0.99ms][0m  SELECT user_id, max(to_time) as to_time FROM "summaries"   GROUP BY user_id
[36;31m[1 rows affected or returned ][0m
2020/05/28 03:35:32 aggregation.go:94: sql: Scan error on column index 1, name "to_time": unsupported Scan, storing driver.Value type string into type *time.Time

[35m(D:/wakapi/services/user.go:25)[0m
[33m[2020-05-28 03:35:37][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE ("users"."id" = 'nickac') ORDER BY "users"."id" ASC LIMIT 1
[36;31m[0 rows affected or returned ][0m
127.0.0.1 - - [28/May/2020:03:35:37 +0100] "POST /login HTTP/1.1" 404 3217
127.0.0.1 - - [28/May/2020:03:35:37 +0100] "GET /assets/app.css HTTP/1.1" 200 89
127.0.0.1 - - [28/May/2020:03:35:46 +0100] "GET /signup HTTP/1.1" 200 4182
127.0.0.1 - - [28/May/2020:03:35:46 +0100] "GET /assets/app.css HTTP/1.1" 200 89
127.0.0.1 - - [28/May/2020:03:35:46 +0100] "GET /assets/app.js HTTP/1.1" 200 7812

[35m(D:/wakapi/services/user.go:60)[0m
[33m[2020-05-28 03:36:00][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE "users"."id" = 'nickac' AND (("users"."id" = 'nickac')) ORDER BY "users"."id" ASC LIMIT 1
[36;31m[0 rows affected or returned ][0m

[35m(D:/wakapi/services/user.go:60)[0m
[33m[2020-05-28 03:36:00][0m  [36;1m[0.99ms][0m  INSERT  INTO "users" ("id","api_key","password") VALUES ('nickac','9afd5aa7-317e-4776-ba65-33dfae31d5b3','$2a$10$0dU6ANzVi.T6xZpt5XE5Ke1qXetFWSaY18QKaRXOcG06ftjRLmJve')
[36;31m[1 rows affected or returned ][0m
127.0.0.1 - - [28/May/2020:03:36:00 +0100] "POST /signup HTTP/1.1" 302 0
127.0.0.1 - - [28/May/2020:03:36:00 +0100] "GET /?success=account+created+successfully HTTP/1.1" 200 3025
127.0.0.1 - - [28/May/2020:03:36:00 +0100] "GET /assets/app.css HTTP/1.1" 200 89

[35m(D:/wakapi/services/user.go:25)[0m
[33m[2020-05-28 03:36:11][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE ("users"."id" = 'nickac') ORDER BY "users"."id" ASC LIMIT 1
[36;31m[1 rows affected or returned ][0m
127.0.0.1 - - [28/May/2020:03:36:11 +0100] "POST /login HTTP/1.1" 401 3218
127.0.0.1 - - [28/May/2020:03:36:11 +0100] "GET /assets/app.css HTTP/1.1" 200 89

[35m(D:/wakapi/services/user.go:25)[0m
[33m[2020-05-28 03:36:19][0m  [36;1m[0.00ms][0m  SELECT * FROM "users"  WHERE ("users"."id" = 'nickac') ORDER BY "users"."id" ASC LIMIT 1
[36;31m[1 rows affected or returned ][0m
127.0.0.1 - - [28/May/2020:03:36:19 +0100] "POST /login HTTP/1.1" 302 0
127.0.0.1 - - [28/May/2020:03:36:19 +0100] "GET /summary HTTP/1.1" 302 43
127.0.0.1 - - [28/May/2020:03:36:19 +0100] "GET /?error=unauthorized HTTP/1.1" 401 3211
127.0.0.1 - - [28/May/2020:03:36:19 +0100] "GET /assets/app.css HTTP/1.1" 200 89
```

</details>

The user exists on the database
![user on database](https://i.imgur.com/qAbIdFq.png)

**Comment by muety** [comment]
Hey @NickAcPT, sorry for the inconveniences! I made changes to the authentication logic recently, which are apparently causing problems in your case. To any other Wakapi users reading this, do you face similar problems as well? Please comment :slightly_smiling_face:.

From what I've seen from the logs, you have create a new `nickac` user and try to log in as it, right? Was that user existing before and you deleted it or did you use the `admin` user prior to the upgrade?

Please also let me how:
* Which database are you using?
* Did you set the `WAKAPI_PASSWORD_SALT` variable in `.env`?

Let's try to get this fixed, so you can keep using Wakapi asap :wink: 

Btw., I'm planning to offer a free, cloud-hosted Wakapi server soon. Would you be interested in using such?

**Comment by NickAcPT** [comment]
First of all, @muety thanks for the fast reply.

> From what I've seen from the logs, you have create a new `nickac` user and try to log in as it, right?

Yes, that is correct.


> Was that user existing before and you deleted it or did you use the `admin` user prior to the upgrade?

This user did not exist before and I was using the `admin` user, like you mentioned.

> * Which database are you using?

I am using an SQLite database 
[(sample database where the error occurs: wakapi_db.zip)](https://github.com/muety/wakapi/files/4696770/wakapi_db.zip)


> * Did you set the `WAKAPI_PASSWORD_SALT` variable in `.env`?

I have actually, otherwise the application would tell me that it has not been set previously.

> Btw., I'm planning to offer a free, cloud-hosted Wakapi server soon. Would you be interested in using such?

Currently I'll have to stay with the self-hosted alternative because I sometimes need to work on stuff while offline, but I can see that other might enjoy this one.

But, if you actually do this, please don't pull a WakaTime and have special features for paid users only. Otherwise someone would need to do an alternative to WakAPI 😂

**Comment by muety** [comment]
Hey @NickAcPT, I just set up a clean Wakapi installation locally, using your config and database. Since I don't know your password (and I shouldn't!), I could not test with your specific user. However, I was able to sign up, create a new user and log in. I can't reproduce your problem right now, sorry!

Probably you have already tried to delete that user account from the database and sign up once again?

**Comment by NickAcPT** [comment]
> However, I was able to sign up, create a new user and log in. I can't reproduce your problem right now, sorry!

That's weird.

> Probably you have already tried to delete that user account from the database and sign up once again?

Yes I have. Could it be the build executable is not functioning correctly?

**Comment by muety** [comment]
> I've updated to 1.2.5

I guess you mean 1.5.1?

**Comment by NickAcPT** [comment]
> > I've updated to 1.2.5
> 
> I guess you mean 1.5.1?

Yes, I mixed them up. I built the project and the last commit was 6c2f0cb1ec5b83151ebc88dc40e6e93bcdeaad14 when I cloned

**Comment by muety** [comment]
I just added a bit of code to trim accidental white spaces and blank lines from passwords, but I don't think that is related to your problem.

I'm sorry, I can't figure out your issue. It might be some strange kind of encoding problem, since you're on Windows, but I didn't managed to sort it out. I tried the code version you mentioned on both Linux and Windows with Go 1.14 and was able to successfully create to users. 

Please let me know if you somehow manage to solve it.

**Comment by NickAcPT** [comment]
This only started occuring once I started building the project myself.

Would it be possible for you to use GitHub Actions for building the project and having artifacts ready to use?

Maybe give a look at https://github.com/marketplace/actions/go-cross-build

**Comment by NickAcPT** [comment]
I've tried rebuilding it again, to no avail. I still get "Unauthorized" for the accounts. Tried with a Postgres DB, but didn't work either.

**Comment by NickAcPT** [comment]
Finally was able to build it from Windows on a fork of mine.. Still does not work..

**Comment by muety** [comment]
> Could it be a problem on Windows?

At least not a general one, as it works when I compile it.

What you could try is use this binary, that I just compiled on 64-bit Windows 10. Also, I included your database again, but containing another `nickac2:nickac` user that you could try to log in as.

[wakapi.zip](https://github.com/muety/wakapi/files/4699888/wakapi.zip)

**Comment by NickAcPT** [comment]
![Error](https://i.imgur.com/7j1kLdf.png)

It mentions a cookie, but I don't have any that get stored

**Comment by muety** [comment]
> It mentions a cookie, but I don't have any that get stored.

As an explanation to the code snippet you posted: there are two ways to authenticate against Wakapi. First one is using an API Key. This is the authentication method used by your local WakaTime client. Second one is using a cookie, that is sent upon logging in to the web interface.

> While logging in, I saw a cookie named `pga4_auth`

Never heard of that, shouldn't be related to Wakapi by any means.

It's very weird that Firefox works for you, but Chrome doesn't. I mainly use Firefox, but tested sign up and login with both of them. 

After hitting "Login", there should be a request like this. The important part here is the `Set-Cookie` header in the response.

![wakapi](https://user-images.githubusercontent.com/8978843/83323704-d3ab4b00-a260-11ea-8379-3a784aafb43e.png)

Probably you already tried signing up / logging in in an incognito tab or by clearing all your `localStorage` and cookies for that specific host before?

**Comment by NickAcPT** [comment]
> After hitting "Login", there should be a request like this. The important part here is the Set-Cookie header in the response.

I see the /login request with that auth cookie, but the /summary one has the cookie, but with no content.

> Probably you already tried signing up / logging in in an incognito tab or by clearing all your `localStorage` and cookies for that specific host before?

Yeah, I already did.

But I'm not crazy. Tried with the latest Edge Dev version (`84.0.522.5 (Official build) dev (64-bit)`) on Incognito and still didn't work

**Comment by muety** [comment]
I'm pretty sure I found the problem. See https://github.com/muety/wakapi/issues/27. There's gonna be a fix soon.

But it's strange that Firefox just seems to ignore the `Secure` flag for cookies, while Chrome and Edge strictly respect it :thinking:.

**Comment by muety** [comment]
@NickAcPT Please try this: https://github.com/muety/wakapi/issues/27#issuecomment-636309687

**Comment by NickAcPT** [comment]
@muety You nailed it! Thanks for that.
Closing this since it worked. :+1:
