### ISSUE TITLE
Getting error unauthorized on every link

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/wakapi#254]
**Describe the bug**
Can't log in anymore because I get redirected to `/` and get the error unauthorized, but I am not signned in. That also happens if I visit `/login`. The api still works.

**System information**
Please provide information on:
* v1.29.6 @ sqlite3 in Docker

**Comment by muety** [comment]
So if you try to log in, you get an unauthorized error? Can you please send corresponding server logs?

**Comment by mawoka-myblock** [comment]
> So if you try to log in, you get an unauthorized error? Can you please send corresponding server logs?

Somehow my browser fcked something up, so it was the problem of my browser, not your awesome work!
