### ISSUE TITLE
Support `api_key` query parameter authentication

### ISSUE THREAD

**Issue by muety** [muety/wakapi#258]

**Comment by muety** [comment]
According to the [official docs](https://wakatime.com/developers#authentication), the parameter is supposed to be named `api_key`, but apparently `token` works as well, so we should support both.

![image](https://user-images.githubusercontent.com/8978843/136748980-22d3827f-9386-4ca2-9c83-92bd06b0a9dc.png)

**Comment by gaocegege** [comment]
When we use an empty string as a key here, a user will be returned. I will just check if the key is empty in the auth middleware, we can open a new issue to keep track of the issue.

WDYT

```go
func (r *UserRepository) GetByApiKey(key string) (*models.User, error) {
	u := &models.User{}
	if err := r.db.Where(&models.User{ApiKey: key}).First(u).Error; err != nil {
		return u, err
	}
	return u, nil
}
```
