### ISSUE TITLE
Wakapi Dashboard Timeout Preference

### ISSUE THREAD

**Issue by chikko80** [muety/wakapi#268]
Hey,
in the original wakatime dashboard there is a timeout preference which is adjustable. this significantly changes the time you work on a project.
example:
timeout preference 15 minutes: heartbeat 1 - 1:30pm, heartbeat 2 - 1:50pm
This would not add to the summary, but if i adjust the timeout preference to 20-25 minutes, it would!

Whats the default setting and is there a possibilty to change that?

![Bildschirmfoto 2021-11-02 um 09 22 47](https://user-images.githubusercontent.com/58805871/139812835-eed59364-68c4-4bea-abf5-ae1344a71644.png)

Sorry if i missed it but i can't find any information about that

**Comment by muety** [comment]
Hi, thanks for your feedback! We already have this as a ticket, see #156. However, it doesn't have highest priority.
