### ISSUE TITLE
"avatarUrlTemplate" not defined after update to version 1.30.1

### ISSUE THREAD

**Issue by nck974** [muety/wakapi#269]
**Describe the bug**
I had version 1.30.0 and I updated to version 1.30.1, during the startup I'm finding this exception:

> 2021-11-08T16:05:04.715830414+01:00 [INFO ] dropped table 'gorp_migrations'
> 2021-11-08T16:05:04.715855839+01:00 [INFO ] potentially running migration '20210806-remove_persisted_project_labels'
> 2021/11/08 16:05:04 /usr/local/wakapi/migrations/20210806_remove_persisted_project_labels.go:21
> [0.580ms] [rows:1] SELECT * FROM "key_string_values" WHERE key = '20210806-remove_persisted_project_labels' ORDER BY "key_string_values"."key" LIMIT 1
> 2021-11-08T16:05:04.716714916+01:00 [INFO ] no need to migrate '20210806-remove_persisted_project_labels'
> 2021-11-08T16:05:04.721130688+01:00 [INFO ] generating summaries
> 2021-11-08T16:05:04.721359221+01:00 [INFO ] initializing report service
> 2021/11/08 16:05:04 /usr/local/wakapi/repositories/user.go:74
> [10.242ms] [rows:2] SELECT * FROM "users"
> panic: template: summary.tpl.html:52: function "avatarUrlTemplate" not defined
> 
> 
> goroutine 1 [running]:
> github.com/muety/wakapi/routes.loadTemplates()
>         /usr/local/wakapi/routes/routes.go:86 +0x134
> github.com/muety/wakapi/routes.Init(...)
>         /usr/local/wakapi/routes/routes.go:20
> main.main()
>         /usr/local/wakapi/main.go:170 +0xce4
> 

I did the update with [the entry in the wiki.](https://github.com/muety/wakapi/wiki/Setup-on-Raspberry-Pi-4#update)

**System information**
Please provide information on:
* Wakapi version 1.30.0 to 1.30.1
* Operating system: Raspbian GNU/Linux 10 (buster)
* Database: psql (PostgreSQL) 11.13 (Raspbian 11.13-0+deb10u1)

**Comment by muety** [comment]
This is weird :thinking: Did you recompile the binary using `go build`?

**Comment by nck974** [comment]
Sorry for my late response. I actually forgot to rebuild it, after failing to build do to missing dependencies.

It got fixed after trying to build again with the dependencies installed.
