### ISSUE TITLE
Error: Resource not found showed after login

### ISSUE THREAD

**Issue by skykk0128** [muety/wakapi#270]
Hi all. This is Steven. 
When I logged in with my email and password. It showed that "Error: Resource not found"
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/62049107/141677774-535c6fdd-407e-4ed2-8c6d-2ac5b5bc1bbe.png">
I was pretty sure that I entered the correct email and password. Not sure what does this error mean. Need some help, many thanks.

**Comment by YC** [comment]
The code (and my testing) suggests that this error is raised when the username is not found.  

https://github.com/muety/wakapi/blob/3aacd3461dc14c6a2138d24c652630d5f33b32dd/routes/login.go#L78-L89

**Comment by muety** [comment]
Hi @skykk0128, thanks for bringing this up. You need to log in with username, instead of email, as email is only optional.

**Comment by skykk0128** [comment]
Sorry, my bad. Problem solved. Many thanks
