### ISSUE TITLE
Add an option to map all names to lower case

### ISSUE THREAD

**Issue by ouuan** [muety/wakapi#273]
I suggest adding an option to map all names to lower case, and additionally, users can add aliases to map lower case to the correct name.

_Originally posted by @ouuan in https://github.com/muety/wakapi/issues/234#issuecomment-965394551_

Some possible advantages are:

1. If there are more than two possible cases for a single language (e.g. `javascript`, `Javascript` and `JavaScript`), or two different cases of the same spelling need to be mapped to another spelling (e.g. map `cpp` and `Cpp` to `C++`), this can save some aliases.
2. If a language is split into multiple different names, some of its names may not appear in the ranking, thus the user won't notice the incorrect names of the language and some coding time will be missing.

**Comment by muety** [comment]
Thanks for your elaborate suggestion! However, as already hinted in #234, I don't want to introduce additional complexity for the purpose of mapping between lower / upper case entity names. I'll close this, sorry!
