### ISSUE TITLE
"Regenerate summaries" duplicates the data

### ISSUE THREAD

**Issue by jabra98** [muety/wakapi#277]
**Describe the bug**
I noticed that there were some entries saved as "python" and "Python", therefore I tried to use the "Regenerate summaries" function exposed on the webinterface, which just duplicated my data. Luckily I saved the database file before doing it and everything is back to normal by replacing the new one with the old one, so no damage was done.

**System information**
* Wakapi version: 1.30.1
* OS: Debian
* Database (SQLite, MySQL, ... ?): SQLite (the default option)

**Comment by muety** [comment]
Thanks for bringing this up! I was able to reproduce the error. It only seems to happen on SQLite (again... :roll_eyes:). I'll fix this as soon as possible.

**Comment by muety** [comment]
I think I figured out the problem and did some code changes (see latest version 1.30.2). However, you will have to manually migrate your SQLite database in order for it to respect foreign key constraints, see [Enabling SQLite foreign key constraints](https://github.com/muety/wakapi/wiki/Enabling-SQLite-foreign-key-constraints). Sorry for the inconveniences.

**Comment by jabra98** [comment]
Hi, I did what was described on the link and it seemed to work. It threw some errors though: https://pastebin.com/n4BiWA00.
But regenerating the summaries worked as expected. Thanks

**Comment by muety** [comment]
These errors most likely relate to summary items that don't have a corresponding summary anymore, i.e. are orphans, caused by the broken cascading before. I'd say you can smoothly ignore them.
