### ISSUE TITLE
question regarding setting up HTTPS

### ISSUE THREAD

**Issue by jabra98** [muety/wakapi#286]
I've been trying to setup wakapi to use https and by using a self-signed certificate I've come so far where I can access the web interface (https://hostname:8000). This worked after generating the certificate and key, pointing to them in the `config.yml` and trusting the certificate on the client machine. But when trying to send heartbeats through the editor plugin ([vim-wakatime](https://github.com/wakatime/vim-wakatime/) in my case) this error pops up on server-side:
```
2021/12/24 19:52:20 http: TLS handshake error from 192.168.208.93:47148: remote error: tls: bad certificate
```
where `192.168.208.93` is the client machine. (I also changed the `~/.wakatime.cfg` configuration to talk to `https` instead of `http` URL)
I haven't really bothered around much with HTTPS stuff so I don't know why the certificate is considered _bad_ and I don't know if the problem is on client or server side..

**Comment by YC** [comment]
From my testing `tls: bad_certificate` does arise when a self signed certificate is used.

**Comment by muety** [comment]
Yep, this is a client side issue. Wakapi CLI by default doesn't trust self-signed certificates (which is a good thing), but setting `no_ssl_verify = true` should most likely solve it.

**Comment by jabra98** [comment]
That worked, thanks.
