### ISSUE TITLE
Swagger /api/api duplication

### ISSUE THREAD

**Issue by YC** [muety/wakapi#289]
**Describe the bug**
Due to `@BasePath /api` defined in `main.go`, routes are called by `/api/api` in Swagger documentation, resulting in 404. 

2 possible solutions: 
- Remove /api prefix from inline annotation comments
- Remove basepath

![Screenshot_2022-01-01_19-31-55](https://user-images.githubusercontent.com/5828744/147847010-7ccd4ce3-7001-4407-a18f-3ce5708615ac.png)

What do you think @muety?

**System information**
Please provide information on:
* Wakapi version: 1.30.1
* Operating system: N/A
* Database (SQLite, MySQL, ... ?): N/A

**Comment by muety** [comment]
Good catch. I'd rather remove the prefixes and keep base path. Want to do a PR? :wink: Happy new year btw :v:

**Comment by YC** [comment]
Happy new year to you too!
