### ISSUE TITLE
Build `armv7` Docker images

### ISSUE THREAD

**Issue by cnichte** [muety/wakapi#292]
Love it. Would be great if this could run on Raspbberry Pi via Docker.

**Comment by YC** [comment]
Raspberry Pis are of [several different](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) arm architectures. 
Which arm version are you looking for?

**Comment by muety** [comment]
Check the following Wiki article, maybe that's for you?
https://github.com/muety/wakapi/wiki/Setup-on-Raspberry-Pi-4

**Comment by cnichte** [comment]
> Raspberry Pis are of [several different](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) arm architectures.
> Which arm version are you looking for?

Cortex-A72  - Raspberry P4 / P400

**Comment by cnichte** [comment]
> Check the following Wiki article, maybe that's for you?
> https://github.com/muety/wakapi/wiki/Setup-on-Raspberry-Pi-4

Thank you. May be :-) that points in the right direction, but a hassle-free ready-made docker / compose package would be my preference,  as it fits perfectly into my little server environment.

**Comment by muety** [comment]
Actually, providing an image for Raspberry Pi's armv7 architecture should be fairly easy. Shouldn't be much more than extending [this line](https://github.com/muety/wakapi/blob/15c8838fead796305c7c259a04fa060322631a95/.github/workflows/docker.yml#L48).

Available platforms: https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#platform

Some background info: https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

@YC Wanna have a look at this? No rush, it's not too urgent, I'd say.

**Comment by YC** [comment]
> > Raspberry Pis are of [several different](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) arm architectures.
> > Which arm version are you looking for?
> 
> Cortex-A72 - Raspberry P4 / P400

A bit confused, since A72 is armv8 32/64, which I think is covered by arm64 and our current Docker image. 
@cnichte If you don't think that this is the case, can you please provide the output of `$ uname -a`?

**Comment by YC** [comment]
> Actually, providing an image for Raspberry Pi's armv7 architecture should be fairly easy. Shouldn't be much more than extending [this line](https://github.com/muety/wakapi/blob/15c8838fead796305c7c259a04fa060322631a95/.github/workflows/docker.yml#L48).
> 
> Available platforms: https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#platform
> 
> Some background info: https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/
> 
> @YC Wanna have a look at this? No rush, it's not too urgent, I'd say.

Yes, we already compile to both `amd64` and `arm64` via buildx. 
I'm just wondering whether we should add v6 or v7 or both.

**Comment by muety** [comment]
Thanks for investigating! @cnichte is v7 actually what you need? I'd only want to add it if someone actually has a need for it.

**Comment by cnichte** [comment]
Ja, das wäre klasse. 

> > > Raspberry Pis are of [several different](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) arm architectures.
> > > Which arm version are you looking for?
> > 
> > 
> > Cortex-A72 - Raspberry P4 / P400
> 
> A bit confused, since A72 is armv8 32/64, which I think is covered by arm64 and our current Docker image. @cnichte If you don't think that this is the case, can you please provide the output of `$ uname -a`?

The output on the 400 is:
`Linux raspberrypi-400 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l GNU/Linux`

Ive tried the existing docker image a few days ago, but it failed with a "not supported" error, or similar.

**Comment by muety** [comment]
That looks like `armv7` to me. Thanks to @YC, Docker images are built for that architecture now. However, I want to do some more testing of `2.0.0-RC1` before releasing final version. Official Docker image for `2.0.0` is about to come in the next two or three days.
