### ISSUE TITLE
Projects with period '.' in name can't be queried in api

### ISSUE THREAD

**Issue by Atakku** [muety/wakapi#301]
**Describe the bug**
While attempting to get a badge working for a new project that has a `.` in its name, I get 0 hours, and other projects without `.` are queried just fine
Query link: `/api/compat/shields/v1/Atakku/interval:any/project:cool.name`

**System information**
Please provide information on:
* Wakapi version - v2.0.0-RC1
* Operating system
    * If Linux: which distro? - Arch Linux
    * If Docker: which image and tag? - built from github (checked out the v2.0.0-RC1 tag)
* Database (SQLite, MySQL, ... ?) - MySQL

**Comment by YC** [comment]
For reference, was resolved in bcbd6236df54359e4b517f462122fb1f085b0cd1
