### ISSUE TITLE
Project overview

### ISSUE THREAD

**Issue by muety** [muety/wakapi#302]
A list of all projects in current timespan

**Comment by muety** [comment]
Just went over the backlog and came across this feature request, but can't really remember what it is about. How is this new project overview different from the "Projects" bar chart on the summary page? :thinking:

**Comment by GioPan04** [comment]
A projects page would be really useful.
For example: If I haven't worked in a project for a while and I want to get stats for that project I have to set a specific filter to show that project in the projects bar chart, and that's really inconvenient.

**Comment by muety** [comment]
@GioPan04 Thanks, I definitely see the need for this!
