### ISSUE TITLE
Only the top nine legends are shown

### ISSUE THREAD

**Issue by ouuan** [muety/wakapi#303]
**Describe the bug**

In 2.0.0, only the top nine legends are shown. All legends were shown in v1.

Because of the reason described in #273, I want to know the names of all languages in case some languages need aliases. Without the legends, it's hard to get the language names, especially the ones with a very small percentage.

**Comment by muety** [comment]
I pushed a fix, but I'll wait for a few more changes to pile up before doing the next release.
