### ISSUE TITLE
Emacs is not recognized as editor during heartbeat processing 

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#306]
**Describe the bug**
Since mid-december (in my experience), Emacs (using wakatime-mode) is no longer recognized as Editor when heartbeats are processed.
Here is the last entry that worked:
```
notarock | /nixos-configuration/notarock/default.nix                                                | file |          | nixos-configuration | master | Nix      | t        | emacs  | Linux            | Zonnarth | 2021-11-26 08:24:24.92  | fe698fefb0c9f9d4 |           |        | 2021-11-26 08:24:25.583 | wakatime/13.0.7 (Linux-5.15.0-x86_64-with-glibc2.33) Python3.9.6.final.0 emacs-wakatime/1.0.2
```
Here's an entry that is newer, but "Emacs" was not set as the editor properly:
```
notarock | [redacted]/ci.yml         | file | coding   | rdamour-hello | master | YAML     | t        |        |                  | [redacted] | 2022-01-11 20:09:21.109 | f868b5b8b010e9a  |           |        | 2022-01-11 20:09:21.294 | wakatime/unset (linux-5.11.0-44-generic-x86_64) go1.16.13 emacs-wakatime/1.0.2
```
I think this was caused by the usage of the newer go rewrite of the CLI tool by wakatime-mode, `wakatime-cli`, seen [here](https://github.com/wakatime/wakatime-mode/commit/0f94ac2dd4fa125fc5f152700779edce75a6b03b). It looks like the user-agent have changed in the mean time. 

I can look into it in the following days. The fix might be similar to the one for https://github.com/muety/wakapi/issues/53 

**System information**
* Wakapi version: v2.0.0 @ postgres 
* Running in docker on a debian vm
* Wakatime-cli version [1.18.7](https://github.com/NixOS/nixpkgs/blob/0ecf7d414811f831060cf55707c374d54fbb1dec/pkgs/tools/misc/wakatime/default.nix#L5) (but `wakatime-cli --version` yield "unset" :thinking: )

**Comment by muety** [comment]
Thanks for reporting this! It's indeed about the user agent parser regex again. This is the UA string sent by your client:

```
wakatime/unset (linux-5.11.0-44-generic-x86_64) go1.16.13 emacs-wakatime/1.0.2
```

The problem is with the `unset`. Wakapi expects the user agent to start with `wakatime/`, followed by a number version code. The updated regex will have to look something like [this](https://regex101.com/r/h1Vp3T/3). Feel free to do a PR, otherwise I'll have a look as soon as possible.
