### ISSUE TITLE
Tag images with major versions

### ISSUE THREAD

**Issue by mikkel1156** [muety/wakapi#307]
I find it's best when using containers to tag the image to a specific release, mostly the major release. That way people choose when to upgrade their instance, and can read the changelogs etc.

Right now we only have the exact version and the latest tag, so I propose tagging new images with the major version as well.

**Comment by muety** [comment]
Great suggestion! It would make sense to also include minor version, though. Wakapi follows [semantic versioning](https://semver.org), i.e. major version will only change very rarely, specifically, only when breaking, backwards-incompatible changes are made. So if you only upgraded major version, you'd miss a lot of great features. Would `<major>.<minor>` tags still help you?

**Comment by mikkel1156** [comment]
I'd suggest both if you're up for it. The idea behind it is that the major version includes the latest minor and patch, so only the major version is "pinned".

Example:
Using a `n1try/wakapi:2` would match the latest minor and patch.
`n1try/wakapi:2.0` would only match the latest patch for the `0` minor
`n1try/wakapi:2.0.1` matches the exact patch.

I'm mostly interested in the first one, since you can avoid breaking changes in the future this way.

**Comment by muety** [comment]
Got it now, sorry for the confusion. Let's do that. Sounds like a perfect task for @YC, doesn't it? 😃

**Comment by muety** [comment]
New tags will be available with next release :heavy_check_mark:
