### ISSUE TITLE
Data Mapping

### ISSUE THREAD

**Issue by Averyyyyyyyy** [muety/wakapi#316]
I noticed that there were options for mapping projects and languages. Still, I would like to see this for the operating system and code editor since when I switched from wakatime to wakapi, my operating system and editor have two sections now even tho it's the same ones.

this is the issue I'm referring too
![image](https://user-images.githubusercontent.com/92644634/151584980-523c6f27-15c0-43b7-8990-0b52df148daf.png)
![image](https://user-images.githubusercontent.com/92644634/151584996-3f1da1b9-77b0-47ce-b3f5-0af2b6feeca9.png)

**Comment by muety** [comment]
Please refer to the workaround described at #234.
