### ISSUE TITLE
Use WakaTime's data dump API for heartbeat import

### ISSUE THREAD

**Issue by muety** [muety/wakapi#323]
We recently added a `type` param to the data dumps api:
https://wakatime.com/developers/#data_dumps

Using `type` of `heartbeats` allows exporting all raw heartbeats for an account over all time. The heartbeats api is better for syncing, but just wanted to point out another option for backing up all heartbeats.

_Originally posted by @alanhamlett in https://github.com/muety/wakapi/issues/87#issuecomment-1049266880_

**Comment by muety** [comment]
Add import progress indicator (using data provided by WakaTime API) as well. Requested by @IgnisDa.

**Comment by muety** [comment]
Data dump API does not have any time range restrictions :heavy_check_mark:.

**Example `POST` request:**
```bash
curl --location --request POST 'https://wakatime.com/api/v1/users/current/data_dumps' \
--header 'Authorization: Basic d2FrYV9<redacted>zODM0Y2QK' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "heartbeats",
    "email_when_finished": false
}'
```

**Example `GET` request response body:**
```json
{
    "data": [
        {
            "id": "176d02ad-2543-48b0-b8c6-1dc52843498f",
            "type": "heartbeats",
            "download_url": "https://wakatime.s3.amazonaws.com/coding-activity-exports/27e1f935-1f96-4751-8e81-4a7c99508bc4/<redacted>&Expires=1689447276",
            "status": "Completed",
            "percent_complete": 100.0,
            "expires": "2023-07-15T18:54:35Z",
            "created_at": "2023-07-08T18:52:58Z",
            "has_failed": false,
            "is_stuck": false,
            "is_processing": false
        }
    ],
    "total": 1,
    "total_pages": 1
}
```

**Comment by muety** [comment]
Will be released soon.

**Comment by Innei** [comment]
How to import wakatime dumped data, is there a example to do?

**Comment by muety** [comment]
Go to _Settings_ -> _Integrations_, put your WakaTime API Key and hit _Import_.
