### ISSUE TITLE
Test mail configuration

### ISSUE THREAD

**Issue by shyim** [muety/wakapi#328]
Hey,

I am trying to setup Mail and have no idea if its working 😅 . It would be nice to have someway option to send a test mail

**Comment by muety** [comment]
Try the "forget password" feature. That one sends a mail for resetting your password, you can use it for debugging SMTP config.

**Comment by shyim** [comment]
ahh nice.

I would like to create a PR to wrap all errors here with a single message: like `dial failed to smtp host: %s` 
https://github.com/muety/wakapi/blob/master/services/mail/smtp.go#L28-L77

I just always got `Bad parameter` and didn't knew which was producing that

**Comment by muety** [comment]
Sure, feel free! PRs are always welcome.
