### ISSUE TITLE
OAuth 2 login

### ISSUE THREAD

**Issue by muety** [muety/wakapi#33]
Log in with:
* GitHub
* GitLab
* ... ?

**Comment by muety** [comment]
* https://godoc.org/github.com/markbates/goth
* https://godoc.org/github.com/markbates/goth/gothic

**Comment by alexanderadam** [comment]
It would be nice to use external auth services like [Authelia](https://www.authelia.com/), [Keycloak](https://www.keycloak.org/), [Authentik](https://goauthentik.io/) or [GitLab](https://docs.gitlab.com/ee/integration/openid_connect_provider.html).

And I guess OpenID Connect (OIDC) /OAuth2 is pretty much standardized and supports, so this could be a good solution.
Most projects allow to set the URLs and secrets via ENV variables. This way users have the full flexibility what kind of provider they want to use.

**Comment by muety** [comment]
See https://github.com/muety/wakapi/issues/94#issuecomment-1366855621 for additional thoughts on this.

**Comment by theredditbandit** [comment]
Hi @muety,

I read the discussion surrounding this issue and saw that you mentioned in [a comment](https://github.com/muety/wakapi/issues/94#issuecomment-1367196193) on #94:
> OAuth 2 / OIDC authentication for Wakapi itself is planned as well, see https://github.com/muety/wakapi/issues/33. I didn't get to implementing that, yet, because it's quite a big one (requires refactorings to current auth. logic). But I see how it will be a huge benefit for users, so please stay tuned!

I'd love to contribute to implementing the OAuth 2 / OIDC authentication feature. Would you be open to accepting a pull request for this enhancement?

To help me get started, could you provide some guidance on the specific areas of the authentication logic that need refactoring? I'd appreciate any pointers to relevant files or architectural considerations you have in mind.
