### ISSUE TITLE
 Error: Invalid credentials

### ISSUE THREAD

**Issue by roj1512** [muety/wakapi#341]
I deleted my Wakapi container and started running a new version with a different password salt, and now I cannot login to my account.

**Comment by muety** [comment]
Do you still have access to the old salt somehow?

**Comment by muety** [comment]
Otherwise the only way to work around this and recover your data is:
1. Create a new user with some password
2. In the database, copy the new user's `password` column to your old one
3. Log in with password of the new user

**Comment by roj1512** [comment]
Thanks, @muety! I got my problem resolved.

I would also like to share the things I’ve done so this issue will be possible for other people.

1. I installed the CLI SQLite.
2.
```bash
docker volume inspect --format '{{ .Mountpoint }}' wakapi-data
```
3.
```bash
cd <mountpoint>
```
4.
```bash
sqlite3 wakapi.db
```
5.
```sql
SELECT password FROM users WHERE id="<the_username_of_the_new_user>";
```
6.
```sql
UPDATE users SET password="<the_password_hash_of_the_new_user_from_the_above_query>" WHERE id="<the_username_of_the_problematic_user>";
```
