### ISSUE TITLE
Option to switch on vibrant colors for editors and OS'

### ISSUE THREAD

**Issue by bdeshi** [muety/wakapi#343]
Hi @muety, are there any plans to bring back colorful editor and os charts? any particular reason for changing these into generic green gradients?

ref: https://github.com/muety/wakapi/commit/44a2e609fb83414d4532182772d4ce3f2fb6d10e

**Comment by muety** [comment]
Hi @bdeshi, thanks for your feedback! Yes, as you already found, we once had colors for editors and operating systems, but that was with the old design. With the new one, I found it to look way calmer and cleaner and not so "messy" with fewer colors. Languages are an exception in that many developers intrinsically associate languages with their GitHub color coding. So in short, we won't add colors for other entities again to keep the design visually appealing.

**Comment by bdeshi** [comment]
oh. any possibility of an option to choose between calm and messy colors?

**Comment by muety** [comment]
I'll add this as a feature request, but with low prio.

**Comment by waaeel** [comment]
Hi @muety, the dashboard design is amazing, I love it! My favourite feature is the ability to add labels to projects, I use it to distinguish between work and hobby projects. Are there any plans to set specific colors in HEX for the labels?

**Comment by muety** [comment]
> Are there any plans to set specific colors in HEX for the labels?

Now there are, I guess :wink: With low prio, though.

Thanks for your feedback!
