### ISSUE TITLE
feat: File statistics for prometheus

### ISSUE THREAD

**Issue by syrm** [muety/wakapi#344]
Hello,

I know you will not add File statistics in wakapi, but can you add it to prometheus export ?
So anyone can graph it like they want.

Ref : https://github.com/muety/wakapi/issues/80

**Comment by muety** [comment]
Hi @syrm, thanks for your feature requests. However, file names are the wrong thing to be represented as part of Prometheus metrics. As stated in the docs (https://prometheus.io/docs/practices/naming/#labels):

> Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

In a strict sense, even projects and languages are unbounded value sets, too, however cardinality is not expected to be so high with them.

**Comment by syrm** [comment]
We don't need label.
We can do this : ```
wakatime_heartbeats_file{name="my/awesome/file.go", type="Go", project="Toto"}
wakatime_heartbeats_file{name="my/awesome/file2.go", type="Go", project="Toto"}
wakatime_heartbeats_file{name="my/awesome/file3.go", type="Go", project="Toto"}
```

**Comment by muety** [comment]
These things (`name`, `type`, `project`) are called labels in Prometheus.
