### ISSUE TITLE
Migration to 2.3.2 fails with "duplicate column name: id"

### ISSUE THREAD

**Issue by YC** [muety/wakapi#346]
**Describe the bug**

```
2022-03-26T09:02:34.632888706Z [WARN ] with sqlite, only a single connection is supported
2022-03-26T09:02:34.658063536Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2022-03-26T09:02:34.659944581Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2022-03-26T09:02:34.659965181Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2022-03-26T09:02:34.659967501Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2022-03-26T09:02:34.659970141Z [INFO ] not attempting to drop and regenerate constraints on sqlite
2022-03-26T09:02:34.678247352Z [ERROR] duplicate column name: id
panic: duplicate column name: id

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x40000e2000?, {0x4000454440?, 0x4000454440?}, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x44
github.com/emvi/logbuch.(*Logger).Fatal(0x40000e2000, {0x4000454440, 0x19}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x78
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
	/src/migrations/migrations.go:39 +0x84
github.com/muety/wakapi/migrations.Run(0x40000eaf70?, 0x1?)
	/src/migrations/migrations.go:33 +0x34
main.main()
	/src/main.go:141 +0x594
exit code: 0
```

**System information**
Please provide information on:
* Wakapi version: 2.3.2 Docker
* Database (SQLite, MySQL, ... ?): SQLite

**Comment by muety** [comment]
Thanks for bringing this up. I was able to reproduce the error. It occurs while attempting to migrate the `heartbeats` schema, although it hasn't changed whatsoever since the previous release.

Some digging led to the following GORM issue, which describes the exact same scenario: https://github.com/go-gorm/gorm/issues/5175. There seems to be a bug in GORM which we'll have to wait for to get fixed.

In the meanwhile, you should be able to work around this by setting `WAKAPI_DB_AUTOMIGRATE_FAIL_SILENTLY` to `true` (or `db.automigrate_fail_silently` in `config.yml` respectively.

**Comment by phanirithvij** [comment]
@muety setting `db.automigrate_fail_silently` does not affect it but setting the environment variable works.

**Comment by oasido** [comment]
> In the meanwhile, you should be able to work around this by setting `WAKAPI_DB_AUTOMIGRATE_FAIL_SILENTLY` to `true` (or `db.automigrate_fail_silently` in `config.yml` respectively.

Sorry for the stupid question, how can I run customized config.yml when using Docker?

**Comment by muety** [comment]
> Sorry for the stupid question, how can I run customized config.yml when using Docker?

Use the respective environment variable (with `-e` in `docker run` command).

**Comment by muety** [comment]
I found that the mentioned upstream bug is not actually the cause for this issue, instead it's related to https://github.com/go-gorm/sqlite/issues/87. I'll push a fix soon.

**Comment by roj1512** [comment]
This is not fixed for me.

**Comment by muety** [comment]
What exact errors do you get?

**Comment by muety** [comment]
Can you please post the result of running the following query on your SQLite database?

```sql
select * from sqlite_schema
```

**Comment by muety** [comment]
Can't reproduce this. Are you on version 2.3.4?

**Comment by roj1512** [comment]
How should I check the version?

**Comment by roj1512** [comment]
Oh, no. It is 2.3.2.

**Comment by roj1512** [comment]
I fixed it, thanks for being with me @muety!
