### ISSUE TITLE
Incorrect data for long time intervals

### ISSUE THREAD

**Issue by jabra11** [muety/wakapi#350]
**Describe the bug**
I'm running my own local instance (v2.3.3 on ARM) and I noticed that for long time intervals the data displayed is incorrect.
Here two screenshots showcasing the issue:

Here everything seems fine, the time interval is set from 2019-07-13 to 2022-04-08.
https://imgur.com/a/sdLFcoV 

But only a day before (2019-07-12 to 2022-04-08) everything except the "Total Heartbeats" section seems to be messed up.
https://imgur.com/a/9cEQLRt

The same issue arises when using the "All time" interval. The weird thing is that about weeks ago this didn't happen. I also checked earlier releases (2.3.1, 2.3.2) which have the same problem. The data comes from a wakatime import.

**System information**
Please provide information on:
* Wakapi version: 2.3.3
* Operating system: Tried on Arch Linux x86, Debian 11 ARM and Debian 11 x86
* Database (SQLite, MySQL, ... ?): MariaDB

**Comment by muety** [comment]
Hi @jabra11, thanks for reporting this. Look weird! Can you try to regenerate summaries (Settings -> Danger Zone), please? Please make sure to first backup your database, though!

**Comment by muety** [comment]
Actually, before regenerating summaries, first try to add `&recompute=true` to the URL for the page were stats are messed up and see if that will change anything.

**Comment by jabra11** [comment]
Hi, the `&recompute=true` flag fixed it.

**Comment by muety** [comment]
Good to hear. But you probably don't want to pass `&recompute=true` every time, so I'd recommend to do the regeneration (which does essentially the same, but persists the results to the database).

**Comment by jabra11** [comment]
Hi, I tried doing that and looking at the wakapi logs the regeneration seemed successful (a bunch of `successfully generated summary <date>` entries), but the problem still persists.

**Comment by muety** [comment]
Could you maybe send me the result of running the following SQL query as a CSV or SQL file? No personal information will be included.

```sql
select from_time, to_time, num_heartbeats, num_items
from summaries
         right join (
    select summary_id, count(*) as num_items
    from summary_items
    group by summary_id
) s on s.summary_id = summaries.id
order by from_time asc;
```

**Comment by muety** [comment]
Thanks! I'll have a look soon and get back to you then.

**Comment by muety** [comment]
What happens for days before 2019-07-12? Is everything before 2019-07-13 broken or only specific dates?

**Comment by muety** [comment]
Also, what's the result if you select 2019-07-11 to 2019-07-14, for instance?

**Comment by jabra11** [comment]
Hey, the data looks sound for these intervals and I don't see anything unusual in the server's logs. 
But I noticed is the following:
The interval 2019-04-23 to 2022-01-17 is exactly 1000 days long (2019-04-23 being the date of the first heartbeat in the database).
For those 1000 days the data looks correct, but going one day further (2019-04-23 to 2022-01-18, 1001 days) it breaks.

Similarly, the interval I gave initially which reported correct data (2019-07-13 to 2022-04-08) also consists of exactly 1000 days, again going one day longer (2019-07-12 to 2022-04-08, 1001 days) it breaks.

Looking at the data today, I observe again that only that last 1000 days can be reported correctly (2019-07-17 to 2022-04-12). So the problem seems to arise when the chosen interval is longer than 1000 days.

**Comment by jabra11** [comment]
Also, while the data looks sound when choosing intervals that are shorter than 1000 days, they are not consistent with the data I get when choosing the same interval but passing the `recompute=true` flag. For example, when choosing 2019-04-23 to 2022-01-01, it first shows 1076 hours. And when passing the flag it recomputes with 1101 hours it seems to save it somewhere (because when revisiting the site without the flag it keeps showing 1101 hours).

**Comment by muety** [comment]
Good find with the 1000 days! I did some more digging. Wakapi uses an [`IN` statements](https://github.com/muety/wakapi/blob/a1f6c2884b9dd1deed63d0f3d9229027b46ccf02/repositories/summary.go#L94) as part part of the select query to fetch summary items for a given set of summaries. Apparently, MariaDB has an [optimization mechanism in place for the `IN` operator](https://mariadb.com/kb/en/conversion-of-big-in-predicates-into-subqueries/) that kicks in after exactly 1000 items by default. That can't be a coincidence. Can you please try to increase [`in_predicate_conversion_threshold`](https://mariadb.com/kb/en/server-system-variables/#in_predicate_conversion_threshold) of your MariaDB server and see if the problem persists?

In addition to that, I'll do a small change to de-duplicate the list of IDs in the `IN` clause to make it shorter in the first place.

The second issue you mentioned, the difference between pre-aggregated coding time vs. recomputed, is a different one and already known. It is related to the simplification made [here](https://github.com/muety/wakapi/blob/1a47243f700e925707c5923361272689aa3f7e89/services/summary.go#L394). I'll have to revisit the aggregation logic at some point, as there seem to be minor flaws that add up.

**Comment by jabra11** [comment]
Hi, increasing the `in_predicate_conversion_threshold` limit (I set it to 10000 now) does indeed fix this problem. Great catch!

**Comment by muety** [comment]
Great to hear! Would be interesting to learn more about the underlying issue, i.e. what that optimization of MariaDB is supposed to do and why it fails in this case :thinking:.

For the second problem, stay tuned for #354.
