### ISSUE TITLE
Incorrect Instructions on first login to wakapi.dev (possible solution)

### ISSUE THREAD

**Issue by justEstif** [muety/wakapi#351]
I thought I should inform you that the instructions in the wakapi.dev on first login were wrong. I had followed its instructions, but it wasn't receiving any heartbeats. 
The problem was that it said set: 
api_url = https://wakapi.dev/api

It should say
api_url = https://wakapi.dev/api/heartbeat

**Comment by muety** [comment]
Both should work. If you add `/heartbeat` it will simply be cut off by the CLI again, see [here](https://github.com/wakatime/wakatime-cli/blob/0d5c0ad3a26ae4bb903f3d5fbdbd2a21ecfef980/cmd/params/params.go#L177).

I'm personally using `https://wakapi.dev/api` in my `.wakatime.cfg` and it works.

**Comment by justEstif** [comment]
Thanks for the quick reply. I tested it out the original instructions but it didn't not work. The heartbeat count didn't go up, nor did anything else. Once I went back to my suggestion, it appears to work. I can't really offer any more reasoning as I am ill equipped, but thought I should share it here.

**Comment by muety** [comment]
Can you try to set it back to `/api`, do a bit of coding, and then explicitly invoke the CLI?

```bash
~/.wakatime/wakatime-cli --verbose --sync-offline-activity 1000
```

Also, are there any related log messages in `~/.wakatime.log`?

**Comment by justEstif** [comment]
I didn't find anything in the logs that suggested something recent. I think I might have changed some settings when I was setting up wakatime for vim and/or emacs. Thanks for the help any way.
