### ISSUE TITLE
Update wiki go dependey from 1.16 to 1.18

### ISSUE THREAD

**Issue by nck974** [muety/wakapi#353]
Hello,
I had issues with one of the last updates where the dependencies where not available anymore for the go version I had installed `1.16`.

So I updated to go `1.18`.

I would suggest updating the [raspberry wiki](https://github.com/muety/wakapi/wiki/Setup-on-Raspberry-Pi-4)
To have `https://go.dev/dl/go1.18.linux-armv6l.tar.gz` instead of the current `go1.16.linux-armv6l`

Thank you!

**Comment by YC** [comment]
Fixed.
Please let me know if there're any issues.
