### ISSUE TITLE
Docker Secrets

### ISSUE THREAD

**Issue by muety** [muety/wakapi#356]
Refactor Docker instructions and docker-compose file to read sensitive variables from Docker Secrets.

https://hub.docker.com/_/nextcloud (section "_Docker Secrets_") can be used as an examples.

**Comment by muety** [comment]
Never mind, this only seems to work with Docker Swarm, which we don't want to depend on.

**Comment by 1fexd** [comment]
Secrets can be used with [Docker Compose](https://docs.docker.com/compose/use-secrets/), so it would be great if you could reconsider ([Vaultwarden](https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview#loading-individual-values-from-files) also supports using secrets in this way, for example)

**Comment by 1fexd** [comment]
I think this can be closed :smile:
