### ISSUE TITLE
Initial API Key setup to connect

### ISSUE THREAD

**Issue by azoller1** [muety/wakapi#360]
EDIT: Ugh, I know why. It is becasue of my caddy-security plugin. Nevermind lol

I am trying to get my api key to work with my hosted instance of wakapi, but it keeps failing to authenticate when I know I am using the correct api key. I get this error constantly. My wakatime logs:

```
{"caller":"cmd/run.go:239","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) later due to api error: won't send heartbeat due to backoff","now":"2022-04-20T13:45:22+08:00","version":"v1.42.1"}
{"caller":"cmd/run.go:239","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: invalid api key... find yours at wakatime.com/api-key. authentication failed at \"https://codestats.mydomain.xyz/api/users/current/statusbar/today\". body: \"{\\\"error\\\":true,\\\"message\\\":\\\"Access denied\\\",\\\"timestamp\\\":\\\"2022-04-20T05:45:22.988238087Z\\\"}\"","now":"2022-04-20T13:45:22+08:00","version":"v1.42.1"}
{"caller":"cmd/run.go:239","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) later due to api error: won't send heartbeat due to backoff","now":"2022-04-20T13:45:35+08:00","version":"v1.42.1"}
{"caller":"cmd/run.go:239","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) later due to api error: won't send heartbeat due to backoff","now":"2022-04-20T13:45:42+08:00","version":"v1.42.1"}
```
I am confused as to why its authenticating at "https://codestats.mydomain.xyz/api/users/current/statusbar/today"

wakatime cfg file:
```
[settings]
api_url = https://codestats.mydomain.xyz/api  (have tried /api/heartbeat too)
api_key = my-api-key
```

I have tried multiple IDEs to test and get the same error. I am running wakapi in a container in docker. I can access my instance at my domain name no problem, so I think nothing is wrong on my sever in regards to connection. Reverse proxying behind caddy. Do I need to set some ENV variables in docker perhaps for the api to work? Here is my compose file
```
services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    volumes:
      - /home/alexz/docker/wakapi/data:/data
    environment:
      WAKAPI_PASSWORD_SALT: my_secret_salt
      WAKAPI_PUBLIC_URL: https://codestats.mydomain.xyz
    ports:
      - 85:3000
    restart: unless-stopped
```

My Caddyfile block for wakapi
```
@wakapi host codestats.mydomain.xyz
        handle @wakapi {
            route {

                    encode zstd gzip
                    authorize with mypolicy
                    reverse_proxy localhost:85

                    @api path_regexp "^/api.*"
                    @notapi not path_regexp "^/api.*"

                    push @notapi /assets/vendor/source-sans-3.css
                    push @notapi /assets/css/app.dist.css
                    push @notapi /assets/vendor/petite-vue.min.js
                    push @notapi /assets/vendor/chart.min.js
                    push @notapi /assets/vendor/iconify.basic.min.js
                    push @notapi /assets/js/icons.dist.js
                    push @notapi /assets/js/base.js
                    push @notapi /assets/images/logo.svg
                  }
        }
```

I am stumped on what to do.

**Comment by azoller1** [comment]
Figured out my issue.

**Comment by muety** [comment]
What was the issue? I'd have assumed that it's something about the reverse proxy, since the `Access denied` message doesn't look like anything returned by Wakapi itself.

**Comment by azoller1** [comment]
I am using plugin for caddy, caddy-security which is a plugin for authorization/authentication/SSO like portal. It seemed I was authorized to access my domain through the plugin as I was already authorized, but for the API calls themselves were not authorized or something, so I couldn't access my server to make the API calls. It is definitely something to do with the caddy-security plugin I am using. I will need to mess with it more. Anyways, it was unrelated to wakapi itself and related to my caddy setup. It works now when I don't have it authorize through the caddy-security plugin.

**Comment by muety** [comment]
Great to hear! Thanks for sharing.
