### ISSUE TITLE
Internal Server Error when Regenerating Summaries

### ISSUE THREAD

**Issue by YC** [muety/wakapi#361]
**Describe the bug**
1. Settings, Clear and regenerate
2. Visit "All Time" on dashboard
```
2022/04/20 07:31:48 runtime error: index out of range [0] with length 0
2022-04-20T07:31:48.767913728Z [INFO ] [request] status=500, method=GET, uri=/summary?interval=any, duration=293.503503ms, bytes=0
```
3. It works eventually, presumably after summaries have finished generating. 

**System information**
Please provide information on:
* Wakapi version: n1try/wakapi:2.3.4
* Database (SQLite, MySQL, ... ?): SQLite

**Comment by muety** [comment]
Good catch! I'll fix this asap.
