### ISSUE TITLE
Change badge-text from wakapi.dev to a customizable one

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/wakapi#366]
For now, the text on the badge says `wakapi.dev`: `[coding-time]`, but I think it should be customizable, or if that's not possible, at least change it from `wakapi.dev` to `Wakapi` (for custom instances).

:heart: Thank you for your great work!

**Comment by muety** [comment]
You can do so by passing `&label=<your-label>` in the URL. Let me know if that works for you.
