### ISSUE TITLE
Unique key constraint (`users.api_key`) duplicated on MariaDB

### ISSUE THREAD

**Issue by jabra11** [muety/wakapi#367]
Hi, I'm getting the following log when trying to start the server (using any release later than 2.3.1)
```
2022-05-05T15:54:21.050711045+02:00 [INFO ] potentially running migration '20201103-rename_language_mappings_table'
2022-05-05T15:54:21.052938583+02:00 [INFO ] potentially running migration '20201106-migration_cascade_constraints'
2022-05-05T15:54:21.056297881+02:00 [INFO ] no need to migrate '20201106-migration_cascade_constraints'
2022-05-05T15:54:21.056338695+02:00 [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
2022-05-05T15:54:21.059205149+02:00 [INFO ] no need to migrate '20210202-fix_cascade_for_alias_user_constraint'
2022-05-05T15:54:21.05924913+02:00 [INFO ] potentially running migration '20220403-drop_user_project_idx'
2022-05-05T15:54:21.062063084+02:00 [INFO ] no need to migrate '20220403-drop_user_project_idx'
2022-05-05T15:54:21.077097674+02:00 [ERROR] Error 1069: Too many keys specified; max 64 keys allowed
panic: Error 1069: Too many keys specified; max 64 keys allowed
```

with the following stack backtrace
```
goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x40000a0000?, {0x4000126640?, 0x4000126640?}, {0x0?, 0x0?, 0x0?})
	/home/joerg/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x44
github.com/emvi/logbuch.(*Logger).Fatal(0x40000a0000, {0x4000126640, 0x38}, {0x0, 0x0, 0x0})
	/home/joerg/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x78
github.com/emvi/logbuch.Fatal(...)
	/home/joerg/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
	/home/joerg/prod/wakapi/migrations/migrations.go:39 +0x84
github.com/muety/wakapi/migrations.Run(0x40000eaea0?, 0x2?)
	/home/joerg/prod/wakapi/migrations/migrations.go:33 +0x34
main.main()
	/home/joerg/prod/wakapi/main.go:142 +0x59c
```
Seems like this is again mariadb related.

**System information**
* Wakapi version: 2.3.4
* Operating system: Debian aarch64 (latest stable)
* Database:  mariadb 10.5.15

**Comment by jabra11** [comment]
Hi, I've been using 2.3.4 since it released and didn't have any problems up until I restarted the server yesterday. MariaDB didn't update either so I'm not sure what could have caused it. 

I ran the following bash command
```
for i in aliases diagnostics heartbeats key_string_values language_mappings project_labels summaries summary_items users; do echo "use wakapi; show create table $i" | sudo mariadb > $i.txt; done
```
and uploaded the outputs [here](https://gist.github.com/jabra11/8c503bd65d23992d0fc8b50011d46986), I hope the formatting isn't too bad :D. I suppose something has gone wrong with the users table.

**Comment by muety** [comment]
Thanks for your support with this! Might be a bug with GORM's MySQL driver. I opened https://github.com/go-gorm/mysql/issues/74 in the upstream repo. In the meanwhile, the only workaround I can think of is manually dropping the duplicate keys:

```sql
alter table users drop index api_key_2;
```

**Comment by muety** [comment]
Did some more digging. See https://github.com/go-gorm/gorm/issues/5324. A quick workaround would be to add `default:NULL` to the `gorm` field tag [here](https://github.com/muety/wakapi/blob/master/models/user.go#L17).

**Comment by mehalter** [comment]
@muety could this be released in a patch release? I am also running into this issue as well. Thanks for all your work!

**Comment by muety** [comment]
Sorry, release is out now!
