### ISSUE TITLE
can not display main page

### ISSUE THREAD

**Issue by jeffxjh** [muety/wakapi#371]
can not display main page

logs 

[INFO ] [request] status=500, method=GET, uri=/summary?interval=today

centos7.6
last version
Docker
SQLite
![image](https://user-images.githubusercontent.com/44387640/167861792-cc59fc5c-a8af-4a9e-bee5-d53eee7b5c71.png)

**Comment by jeffxjh** [comment]
![image](https://user-images.githubusercontent.com/44387640/167869382-335c8f00-272e-4323-97b6-815e570f1b4b.png)
when i rm container restart app got this message.

**Comment by muety** [comment]
Hi @jeffxjh, to help me further debug this, can you please do what is described in comment https://github.com/muety/wakapi/issues/346#issuecomment-1103895854 and post the results?

**Comment by muety** [comment]
@jeffxjh ?

**Comment by jeffxjh** [comment]
Hi@muety 
i connect wakapi.db 
`select * from sqlite_schema` 
no such table: sqlite_schema

**Comment by muety** [comment]
That is strange. Could be that your database file is corrupt. Would you mind sending me the file? Of course, only if you don't feel uncomfortable with regard to sensitive information, etc.!

**Comment by jeffxjh** [comment]
Sorry, I have used the old version, this DB file can be used normally for the old version.
