### ISSUE TITLE
Latest Release didn't Trigger Docker Build/Publish

### ISSUE THREAD

**Issue by YC** [muety/wakapi#383]
https://github.com/muety/wakapi/pkgs/container/wakapi
https://hub.docker.com/r/n1try/wakapi/tags
https://github.com/muety/wakapi/releases/tag/2.3.5
https://github.com/muety/wakapi/actions/workflows/docker.yml

Unclear why this happened, since the tag seems to be present. 
Deleting/overwriting the 2.3.5 tag may be problematic, given that the Github release is associated with the tag.

**Comment by muety** [comment]
I honestly have no idea, why the Docker build wasn't triggered last time :man_shrugging:. This time seems to be working again.
