### ISSUE TITLE
How to run with systemd on port 80

### ISSUE THREAD

**Issue by Amarettini** [muety/wakapi#384]
_Runs fine when executed from the shell as root user with wakapi user and group configured on port 3000 as well as 80. The problem is how the wakapi.service file is configurred, which is probably not the right place to ask here but I couldn't find any simple (no big overhead) working solution on the web._

Been sitting here for some hours now trying to figure out how to get the wakapi service to be able to bind to port 80 (or in general to lower ports). For the application to be able to bind to lower ports it requires root privileges but the wakapi.service preset defaults to the wakapi user which is fine too me but not for binding to port 80 I guess.

Adding a socket service did not work as described here:
https://liquidat.wordpress.com/2018/01/04/howto-run-programs-as-non-root-user-on-privileged-ports-via-systemd/

---

Maybe I am fundamentally wrong with my approach, but I am really astonished by the fact that such a common requirement has no simple solution, since it is commonly advised to run applications on the server as non-root user for security.

If this question should be moved to stackoverflow, let me know.

**Comment by muety** [comment]
> [...] I am really astonished by the fact that such a common requirement has no simple solution

Me too! I did some research and there indeed doesn't seem to be a straightforward way with systemd to allow non-root owned processes to bind to privileged ports. 

The only possible solution I found is the `socket` unit thing. [This](https://unix.stackexchange.com/a/453643) is the example you posted, but slightly modified (note the `Requires=`), so maybe that works? Also, you could try what is mentioned [here](https://stackoverflow.com/a/9128979/3112139). 

If you don't get it to work, maybe post the exact errors you're getting? Also, don't forget to `sudo systemctl daemon-reload` after each change.

**Comment by muety** [comment]
Not exactly sure what it does, but `AmbientCapabilities=CAP_NET_BIND_SERVICE` might also help.

**Comment by muety** [comment]
Any updates here?
