### ISSUE TITLE
Summary time inaccurate after 2.3.6 upgrade

### ISSUE THREAD

**Issue by YC** [muety/wakapi#385]
**Describe the bug**
After upgrade from 2.3.4 to 2.3.6, the summary time seems to have gone down significantly. 
e.g. For "yesterday", it went from 2 hr 7 min to 1 second. 

**System information**
Docker 2.3.6
SQLite

**Comment by muety** [comment]
Sorry for that! And thanks for reporting. I think [this](https://github.com/muety/wakapi/commit/d5a85639b18fabc0bca124716d75053e6b5cbd61) tiny change should fix the issue.
