### ISSUE TITLE
Docker Method: Client Setup Instructions. API key required? 

### ISSUE THREAD

**Issue by zach-is-my-name** [muety/wakapi#389]
Sorry I'm very lost.  I'm here because I want to use Wakatime and keep everything local (at least for now... I'd consider a remote if I were given Proton-reputation-level privacy assurances). 

I followed the Docker instructions, but the setup instructions broke down for me at the required Client Setup when being instructed to create `~/.wakatime.cfg`.  I'm prompted for an API key which doesn't seem related to the Docker setup (if it is, I never received/generated one).  

Next and finally, even with an api key I'm not sure what I should be doing because after Client Setup phase the instructions either seem to end or digress into the long config readout, something about generating docs, or pointers to outside packages for rendering the stats... That's what I thought I the instructions were leading to: "Fancy statistics and plots" and "Self Hosted".  _What steps would I take to accomplish this? picking up where I left off from Docker Installed,_ `touch ~/.wakatime.cfg`

I hope I can get this off the ground, I'm really excited to track my stats

**Comment by YC** [comment]
You'll need to visit the web interface of Wakapi, which if you follow `Option 3: Use Docker` will be at `http://localhost:3000`. 
Then, you'll need to register a user, and view the API key (at top right, profile icon), before placing it into `.wakatime.cfg`. 
Finally, install the corresponding Wakatime plugin for your editor and it should start tracking time.

**Comment by zach-is-my-name** [comment]
Thank you.  I was late and I wasn't thinking it through. I might submit a PR to make everything explicit though
