### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by SConaway** [muety/wakapi#39]
Hi @muety,

I love the idea of this project. I am using on my own server and would like to integrate it with some other Wakatime "tools". These rely on the presence of the `/api/summary` route. I see that there is one, but, as I am unfamiliar with `go` (and servers in `go`), I can't seem to understand it. If you could give me a pointer as to how to use that route, I would be very grateful.

**Comment by muety** [comment]
Hi @SConaway, thanks for your feedback! I created #40 to to add structured API documentation in the near future.

Unfortunately, while `/api/heartbeat` is "compatible" with Wakatime's API, the response returned by `/api/summary` currently looks much different and misses a lot of information that is provided by Wakatime.

Requests like this:
```bash
curl -X GET \
  'https://localhost:8080/api/summary?interval=week' \
  -H 'Authorization: Basic GDQ2NDhkMTQtMTVjNS00PDJiLWI5MYEtZmJlZWM3MGQ7Y2FnCr==' 
```

The auth token in the headers is a Base64-encoded version of your API key, which you get when logging in to the web interface. 

Will result in a response like this:
```json
{
    "user_id": "n1try",
    "from": "2020-07-27T00:00:00+02:00",
    "to": "2020-07-29T00:00:00+02:00",
    "projects": [
        {
            "key": "lp-frontend",
            "total": 7756
        },
        {
            "key": "backup",
            "total": 1105
        },
        {
            "key": "web",
            "total": 499
        }
    ],
    "languages": [
        {
            "key": "Vue",
            "total": 5351
        },
        {
            "key": "TypeScript",
            "total": 2135
        },
        {
            "key": "Java",
            "total": 1080
        },
        {
            "key": "JSON",
            "total": 730
        },
        {
            "key": "unknown",
            "total": 405
        },
        {
            "key": "Markdown",
            "total": 139
        },
        {
            "key": "Go",
            "total": 120
        },
        {
            "key": "CSS",
            "total": 47
        },
        {
            "key": "Bash",
            "total": 21
        },
        {
            "key": "Text only",
            "total": 2
        },
        {
            "key": "XML",
            "total": 1
        },
        {
            "key": "YAML",
            "total": 0
        }
    ],
    "editors": [
        {
            "key": "VSCode",
            "total": 8427
        },
        {
            "key": "IntelliJ",
            "total": 1604
        }
    ],
    "operating_systems": [
        {
            "key": "Linux",
            "total": 10031
        }
    ]
}
```

(I manually removed a few project entries from the above output).

I hope that helps you.

Also, I'm really curious what kind of "Wakatime tools" you are building! :slightly_smiling_face:
