### ISSUE TITLE
Partition database by users

### ISSUE THREAD

**Issue by muety** [muety/wakapi#395]
Data is always queries by user, so it will make a lot of sense to partition the `heartbeats` table (potentially also `summaries` and `summary_items`) by user. This could potentially result in tremendous performance improvements on multi-user instances (like the official wakapi.dev). See [this slide set](https://www.slideshare.net/PerconaPerformance/boost-performance-with-my-s-q-l-51-partitions) for a benchmark of using partitions. Only applies to Postgres and MySQL, as there is no such thing as partitions in SQLite.

* MySQL: https://dev.mysql.com/doc/mysql-partitioning-excerpt/8.0/en/partitioning-hash.html
* Postgres: https://www.postgresql.org/docs/current/ddl-partitioning.html

[Here](https://stackoverflow.com/a/1580029/3112139) is another great explanation of how partitioning works.

**Comment by muety** [comment]
In MySQL, partitioning by a foreign key is not yet supported, see https://dev.mysql.com/doc/mysql-partitioning-excerpt/8.0/en/partitioning-limitations.html. So partitioning by user is not an option. 

Alternative would be to (range-) partition by `time`, e.g. using `to_days()` (see [example](https://stackoverflow.com/a/11901031/3112139)). For the "average" self-hosting Wakapi user, who don't have hundreds of users on their platform, this would probably anyway make more sense. I'd assume that the "today" interval is used most frequently.

I'm only unsure about how to best realize this. With MySQL, first option would be to use a `RANGE` index with a fixed set of dates as "buckets", just like in the example above. But then we would have to regularly re-partition, to adjust the `MAXVALUE` bucket, which I'm not sure is a good practice. Second option would be a `HASH` index on `to_days(date)` with a fixed number of partitions (N). I'm not sure how to best choose N here then.

**Comment by muety** [comment]
Turns out not only partitioning on a column, that is a foreign key, is not supported, but also partitioning on a table that has foreign keys whatsoever. That kills the option for using partitioning with MySQL here.

**Comment by muety** [comment]
Here's a very interesting article on how to migrate from a single table to partitions in Postgres: 

https://rodoq.medium.com/partition-an-existing-table-on-postgresql-480b84582e8d

The gist here is:
1. Temporarily rename old table (`heartbeats` in our case)
2. Create new master table with multiple partition tables, according to the partitioning criterion (`time` in our case)
3. Attach old table as a "legacy" partition

Partition management seems way more "explicit" with Postgres. 

I'd be curious to implement something like that. But I doubt it's worth the effort, especially it would be a Postgres-only solution and not affect users with other DBMS. We might reconsider this when perhaps, some time in the future, dropping MySQL and SQLite support and fully committing to Postgres only.

**Comment by alexanderadam** [comment]
I'm just curious: why not ditching support for MySQL and SQLite right now?

**Comment by muety** [comment]
Because a lot of users especially depend on SQLite. The main reason for supporting SQLite in the first place was to make getting started as easy as possible - without the need to host one's own database server in addition to Wakapi. I wanted Wakapi to be plug & play and be people to be able to run it with a single command.

That's the reason why I'm still struggling to ditch it. There's a trade-off between ease of use for the user on the one hand and maintainability and  performance optimization on the other.

If Wakapi wasn't for self-hosting, we would probably already have committed to either MySQL or Postgres all the way.

**Comment by alexanderadam** [comment]
I see. But query-wise this probably won't make any difference since partitions would just look for certain conditions in `WHERE` clauses, right?
So this would be just about a check in a migration — or am I missing something?

**Comment by alexanderadam** [comment]
Yes, I know that they have an performance impact but that's not the point I was trying to make.
I was just going to ask about compatibility between Postgres and SQLite.
At runtime I don't see any incompatibilities syntax-wise.

**Comment by muety** [comment]
Ah, I see. Yeah, would only be the migrations.

**Comment by alexanderadam** [comment]
So in this case it would be possible to have partitions on Postgres without ditching SQLite — hence having the best of both worlds?
