### ISSUE TITLE
Add Swagger / OpenAPI documentation

### ISSUE THREAD

**Issue by muety** [muety/wakapi#40]

**Comment by gazconroy** [comment]
Hi @muety 

Is the aim to build [declarative comments](https://github.com/swaggo/swag#declarative-comments-format) into the Go code or to develop an independent OpenAPI specification?

**Comment by muety** [comment]
Yes, I'd love to have declarative comments from which OpenAPI / Swagger docs are generated automatically.

**Comment by emansom** [comment]
@muety Are you open to PRs for OpenAPI 3.0 compatibility?
