### ISSUE TITLE
Quick-Run a release: unable to detect platform

### ISSUE THREAD

**Issue by GreenJ84** [muety/wakapi#400]
**Describe the bug**
"We couldn't automatically detect your operating system. You can file a
bug here"
This was the statement given when trying to Quick-Run a release of the program. I am working on the New M1 Chip from Apple running on macOS

**System information**
Please provide information on:
* Wakapi version
    * current version? Just tried right now. 
* Operating system
    * macOS
* Database (SQLite, MySQL, ... ?)

**Comment by muety** [comment]
Thanks for bringing this up! I'll push a fix soon.
