### ISSUE TITLE
Version 2.3.8 shows version release-arch-fix-test

### ISSUE THREAD

**Issue by xgugeng** [muety/wakapi#409]
On 2.3.8, the version shown in the footer is release-arch-fix-test. And `dev` is still in [version.txt](https://github.com/muety/wakapi/blob/2.3.8/version.txt).

System info:

* Ubuntu 20.04
* Got release by `curl -L https://wakapi.dev/get | bash`

```
❯ md5sum wakapi
213d98de815b6ecc1493265cab0db09a  wakapi
```

![image](https://user-images.githubusercontent.com/5053603/191907457-1a775d2e-2f88-4e22-9991-865799b715ca.png)

**Comment by YC** [comment]
Thanks for the report. 
We've recently had some build issues after adding some target architectures. 
I believe the zips were directly taken from [#404](https://github.com/muety/wakapi/pull/404#issuecomment-1240355350). 
This should be resolved by the next proper release, given that the version is [automatically replaced](https://github.com/muety/wakapi/blob/master/.github/workflows/release.yml#L55) in the release pipeline.

**Comment by YC** [comment]
Resolved by 2.4.0 Release
