### ISSUE TITLE
Swagger UI not working with different WAKAPI_BASE_PATH+reverese-proxy

### ISSUE THREAD

**Issue by hatkidchan** [muety/wakapi#412]
**Describe the bug**
I'm running wakapi on my home server accessible via Yggdrasil and wakapi is accessible via nginx reverse proxy at `/wakapi` endpoint (`WAKAPI_BASE_PATH=/wakapi`). It works fine, but I wanted to learn a bit more about wakapi... API part, so I opened Swagger UI and wanted to try some methods only to see 404 page from nginx. Turns out, it's ignoring `WAKAPI_BASE_PATH` variable while constructing base URL.

![image](https://user-images.githubusercontent.com/35804000/193118601-b2223ddf-a400-47ab-8f82-e2190243f6f7.png)

Is it using `WAKAPI_PUBLIC_URL` for that? Am I missing something in my configuration?

I was using `docker run --restart=always -d -e "WAKAPI_PASSWORD_SALT=$SALT" -e "WAKAPI_BASE_PATH=/wakapi" -e WAKAPI_EXPOSE_METRICS=true -e WAKAPI_MAIL_ENABLED=false -v wakapi-data:/data --name wakapi ghcr.io/muety/wakapi:latest` to install wakapi, if that helps, and my nginx config looks like that:
```nginx
        location /wakapi/ {
            rewrite ^/wakapi/(.*) /$1 break;
            proxy_pass http://172.17.0.4:3000;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

**System information**
Please provide information on:
* Wakapi version: v2.3.8
* Operating system: Docker on Arch Linux
    * image: `ghcr.io/muety/wakapi:latest`
* Database: SQLite

**Comment by muety** [comment]
Good catch! Thanks for bringing this up. You didn't miss anything, it's actually a bug. I'll push a fix soon.

**Comment by muety** [comment]
Pushed a fix :heavy_check_mark: Will be included in the next release (coming hopefully quite soon).

**Comment by hatkidchan** [comment]
Wow, that was quick! Thank you so much! I'll make sure to check it out on next release

Oh also, kinda related question.. is there a way to update docker container with latest version once it comes out? Sure, I can `docker rm --force wakapi && docker run blah blah blah`, but is there a way to do it without removing it?

**Comment by muety** [comment]
I don't know of any way to update a Docker container without re-creating it. It's even the [officially proposed](https://github.com/nextcloud/docker#update-to-a-newer-version) way of upgrading Nextcloud. What you can do is use tools like [Watchtower](https://hub.docker.com/r/containrrr/watchtower) to automate this.
