### ISSUE TITLE
Exporting to other Wakapi instance does not work

### ISSUE THREAD

**Issue by Subtixx** [muety/wakapi#420]
**Describe the bug**
The integrations settings say the following:

> You can connect Wakapi with the official WakaTime (**or another Wakapi instance, when optionally specifying a custom API URL**) in a way that all heartbeats sent to Wakapi are relayed. This way, you can use both services at the same time. To get started, get [your API key](https://wakatime.com/developers#authentication) and paste it here.

However this does not work. It tries to call an API that does not exist:
`[INFO ] [request] status=404, method=GET, uri=/api/users/current, duration=12.293µs, bytes=19, addr=*********, user=-`

This results in the API URL and the key not saving. Also when I enter only a custom API URL it says:

> Wakatime API Key updated successfully 

but doesn't actually do anything. The API URL is empty and the key is also empty (since I didn't fill it of course)

EDIT:
I traced the issue that the current system has. The file here [config.go](https://github.com/muety/wakapi/blob/1e9d3f9e80d9dcc9c144371be422259fd51b4203/config/config.go#L45) contains a hardcoded API endpoint for Wakatime: `/users/current` which seems to be missing on Wakapi (**Couldn't verify because the current SwaggerUI Docs are offline!**)? Which in turn then get used in [settings.go](https://github.com/muety/wakapi/blob/1e9d3f9e80d9dcc9c144371be422259fd51b4203/routes/settings.go#L640) to verify the API key.

EDIT2:

Okay I've generated the docs myself and the URL for wakapi seems like its ´/compat/wakatime/v1/users/current´ instead of just `users/current`

EDIT3:

Workaround: Added the following to my nginx configuration:

```
    location /api/users/current {
        proxy_pass http://api/compat/wakatime/v1/users/current;
        break;
    }
```

Importing however results in a hard-crash:

```
goroutine 6965 [running]:
github.com/muety/wakapi/services/imports.(*WakatimeHeartbeatImporter).fetchRange(0x1?, {0xc000fdeea0, 0x25})
	/src/services/imports/wakatime.go:164 +0x145
github.com/muety/wakapi/services/imports.(*WakatimeHeartbeatImporter).Import.func1(0xc0005c76c0, 0xc0010462a0)
	/src/services/imports/wakatime.go:47 +0x125
created by github.com/muety/wakapi/services/imports.(*WakatimeHeartbeatImporter).Import
```

**System information**
Please provide information on:
* Wakapi version: v2.5.1 @ sqlite3 on the sending side and v2.5.1 @ postgres on the receiving one.
* Operating system: Both run in a docker container: docker.io/ghcr.io/muety/wakapi
* Database SQLite on sending site, postgres on receiving.

**Comment by muety** [comment]
Thanks a lot for bringing this up! Also thanks for the detective work you already did :-) I'll push a fix soon (hopefully this weekend still)!

**Comment by muety** [comment]
I had another look into this again. The correct thing to do would be to configure `https://<some-url>/api/compat/wakatime/v1` as the WakaTime API URL, if you want to relay your heartbeats to a second Wakapi instance. Everything at `/api/*` is Wakapi's own API endpoints, all at `/api/compat/wakatime/v1` is compatible with [WakaTime's API v1](https://wakatime.com/developers). Since the feature's original purpose is to forward data to WakaTime, it also required a WakaTime-compatible API. Hope that helps!

**Comment by Subtixx** [comment]
Sounds reasonable. However a more helpful error message would be great. And also some sanity checks. The hard crash isn't something I'm comfortable with. (Maybe also write it somewhere which api endpoint to use).
