### ISSUE TITLE
Can not import data from another wakapi instance

### ISSUE THREAD

**Issue by SuperFola** [muety/wakapi#428]
**Describe the bug**
When trying to import data with URL `https://<wakapiserver>/api/compat/wakatime/v1/` and token, we have a panic and the server crashes:
```
[0/0]0x1fd7cd8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd1dba5]

goroutine 1391 [running]:
github.com/muety/wakapi/services/imports.(*WakatimeHeartbeatImporter).fetchRange(0xc001289520?, {0xc00052d6c0, 0x36})
        /src/services/imports/wakatime.go:164 +0x145
github.com/muety/wakapi/services/imports.(*WakatimeHeartbeatImporter).Import.func1(0xc0006cb860, 0xc000167200)
        /src/services
```

**Receiving System information**
Please provide information on:
* Wakapi version: 2.5.1
* Operating system
    * If Docker: latest
* Database: SQLite 3

**My own System information**
Please provide information on:
* Wakapi version: 2.5.1
* Operating system
    * If Docker: latest
* Database: MySQL

Both servers are behind NginxProxyManager and have SSL enabled.

**Comment by muety** [comment]
Thanks for bringing this up! Which of the both server crashes? And are there any error messages on the other Wakapi instance, respectively?

**Comment by SuperFola** [comment]
Only the receiving server, the one where I want to import data to (SQLite). I don't have any errors in the logs of my Wakapi instance.

The goal was to make something like this:
```
me  -->  friend server 1 (sqlite)  --> my own server  -->  wakatime
```

So I imported wakatime data on my own server, then I wanted to import my data to my friend server.

**Comment by muety** [comment]
Ok cool, will investigate this tomorrow and push a fix soon :+1:

**Comment by muety** [comment]
Fixed it! New release coming soon...

**Comment by SuperFola** [comment]
Thanks a lot!
