### ISSUE TITLE
Allow connecting using MySQL socket

### ISSUE THREAD

**Issue by shyim** [muety/wakapi#433]
This line forces the client to use TCP https://github.com/muety/wakapi/blob/master/config/db.go#L57

It looks like you can do also unix see https://stackoverflow.com/questions/67867424/how-to-connect-with-mysql-using-a-unix-socket

**Comment by shyim** [comment]
tested and works for me like described in stackoverflow. https://github.com/shyim/nixcfg/commit/928e1c5706433008d85c717f445c932626c8cb34

I will provide an PR :)

**Comment by muety** [comment]
Awesome, looking forward to the PR!
