### ISSUE TITLE
Cannot disable listing on ports

### ISSUE THREAD

**Issue by shyim** [muety/wakapi#434]
**Describe the bug**
I disabled like described in the README the listing for ipv4 and ipv6 but they still listen

https://github.com/shyim/nixcfg/blob/0bfb2d62d0d3bfbd6b7730938a33524b0669b963/systems/shea/services/wakapi.nix#L16-L18

**System information**
Please provide information on:
* Wakapi version
* Operating system
    * If Linux: which distro?
    * If Docker: which image and tag?
* Database (SQLite, MySQL, ... ?)

**Comment by muety** [comment]
I can't reproduce this. If I unset `WAKAPI_LISTEN_IPV4` and `WAKAPI_LISTEN_IPV6` and set `WAKAPI_LISTEN_SOCKET` instead, the server will only listen on the Unix socket, and not on TCP :thinking:.

**Comment by YC** [comment]
I believe there is an issue where if you specify a config file with `listen_ipv4`/`listen_ipv6` and you tried to overwrite that with `WAKAPI_LISTEN_IPV4` or `WAKAPI_LISTEN_IPV6`, it retains the value from the file.

**Comment by shyim** [comment]
Maybe because I pass an empty file as config file?

```nix
 ExecStart = "${pkgs.wakapi}/bin/wakapi -config ${pkgs.writeText "wakapi.yaml" ""}";
```

Created an issue to run without config #435
