### ISSUE TITLE
Connect with Github Project

### ISSUE THREAD

**Issue by wyatt-herkamp** [muety/wakapi#443]
So a feature in Wakatime is you can connect a Github project to your wakatime project and it will tell you how much time per commit. 

![image](https://user-images.githubusercontent.com/11785959/208099957-3e6344b4-d577-4b43-80e7-48fcbe72e426.png)

It would be cool to add this to wakapi. 

It might be smart to wait for https://github.com/muety/wakapi/issues/33 because to connect a repository it would require you to login to Github.

**Comment by muety** [comment]
Hi @wyatt-herkamp, thanks for your feature request! However, that's not something I'm planning to add to Wakapi, sorry!
