### ISSUE TITLE
Import progress

### ISSUE THREAD

**Issue by IgnisDa** [muety/wakapi#449]
Awesome project!

As the title says, I would like to see an import progress in the runtime logs and the UI. I was surprised when I could not see the progress even in the logs. 

This is all the information that comes up:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/60938164/209852143-9000cf00-bfd6-4954-97c6-8cf6e22e70a3.png">

It is very difficult to know if the import process failed or succeeded.

**Comment by muety** [comment]
Hi @IgnisDa, thanks for your feedback! The import process is about undergo a refactoring anyway, see #323. In that context, it will be easy to add a progress indicator as well, as WakaTime's API already provides according functionality. I'll close this ticket and include your feature request in #323.

Did your import succeed in the end?

**Comment by IgnisDa** [comment]
@muety Yes it did, it took over 30 minutes though since I have a lot of data.

**Comment by muety** [comment]
Should be a lot faster after using the dump endpoint is implemented.

**Comment by IgnisDa** [comment]
Is there ETA for this feature?
