### ISSUE TITLE
Data dump / exporting functionality

### ISSUE THREAD

**Issue by boehs** [muety/wakapi#453]
Before the change where old data is deleted, I would like to export my data, but I can't find an option in the settings. It's very likely I'm blind, but I could use a little bit of guidance :)

**Comment by boehs** [comment]
I saw

> To forward data to another Wakapi instance, use https://<your-server>/api/compat/wakatime/v1 as a URL.

I just want to download this data locally. Not use another instance.

**Comment by muety** [comment]
Hi @boehs, downloading data locally is not supported, only migrating to another (local) Wakapi instance.

**Comment by boehs** [comment]
So does that make this a feature request?

**Comment by muety** [comment]
A "workaround" would be to (temporarily) host your own Wakapi instance, run the import and then just export your database's `heartbeats` table to CSV. Would that help?

I'm considering to add dumping / exporting functionality as a feature, but would like to spend a bit more time on planning this out. Best would be to simply mimic WakaTime's [`/dump`](https://wakatime.com/developers/#data_dumps) endpoint, but I'll have to investigate to what extent their data format is compatible with Wakapi's data model. 

Relates to #323.

**Comment by muety** [comment]
Here's an example for a heartbeats dump from WakaTime: [`sample_dump.json`](https://pastr.de/p/3id98k2t1usw5k4da6sn5k0b).

Looks quite straightforward. We won't have most of the `user` attributes, but that's not a problem. Instead of `machine_name_id`, and `user_agent_id`, well have the actual plain string instead, respectively. 

And here's an example for the "daily totals" export: [`sample_daily_dump.json`](https://pastr.de/p/3b7f2z8cngaggcode08al32p).

We're not tracking `dependencies` at all, but apart from that, the export could probably be computed from daily summaries for the most parts.

Note: large parts of the original data in the above samples was removed / redacted for brevity.

**Comment by boehs** [comment]
I feel like this is important to do before the data is deleted from past years

**Comment by boehs** [comment]
Sounds good

**Comment by muety** [comment]
> Agree, but won't promise I'll get to this before end of month. Spinning up your own Wakapi instance and importing data to there would be a safer bet for now.

I'll try my best, though! Maybe a temporary solution would be a script to run locally, that just pulls data from Wakapi's standard API endpoints. I'll keep you posted!

**Comment by boehs** [comment]
Thanks for all the thought man ❤️

**Comment by muety** [comment]
I created [this script](https://github.com/muety/wakapi/blob/master/scripts/download_heartbeats.py) to download raw heartbeats from Wakapi. Hope that helps!

**Comment by theAkito** [comment]
> I created [this script](https://github.com/muety/wakapi/blob/master/scripts/download_heartbeats.py) to download raw heartbeats from Wakapi. Hope that helps!


I took the liberty of translating [this script into Nim](
https://github.com/theAkito/mini-tools-nim/tree/master/generic/web/wakapiexporter).

**Comment by muety** [comment]
I decided to not build exporting functionality into Wakapi directly, but instead have the above mentioned download script as the official way to dump heartbeats. Will add instructions to the readme.

**Comment by PukPukov** [comment]
The script works horribly slow, probably because of downloading heartbeats one-by-one and via http requests. If true, server-side dump preparation could significantly speed it up and even reduce server load (http overhead kills not only clients).

**Comment by muety** [comment]
The script downloads day by day, in accordance with the WakaTime heartbeats API.

I'll consider implement server side exports again. However, I'd like to better understand what the use cases for this are. Why do people need these exports?

**Comment by theAkito** [comment]
> However, I'd like to better understand what the use cases for this are. Why do people need these exports?

I don't exactly remember what the exact reasons were back then, when I tried to use this and thought about exporting data, however there are many obvious reasons one might want to export anything. The following points apply to any app handling data. The larger the data set, the more important or useful the export.

* Processing with other tools. Exporting into a neutral formats, like JSON, CSV or something similar allows you to process the raw data in any app whatsoever. These formats work virtually everywhere.
* Backup. Backup. Backup. Backup. Backup. You don't want to rely on an app always working, being maintained and being able to process the data. You need a backup.
* Importing data into other apps for migration purposes. People try out different apps doing more or less the same thing and then settle for one.
* Data Sovereignty. If I can have my data in a neutral format and process it any way I want, it is my data. The more sensitive and personal the data, the more logical and self-explanatory this notion is. If I cannot or if the difficulty is relatively high to extract the data, then I don't own my data, which is not a good thing. (I personally think, that the product of this project may aggregate extremely personal/private/confidential data, depending on how much you do the things you track and for what purposes.)

These are some general points. Not saying, that some of those 100% apply to this project or that this project does not offer any export functionality. I just provided these general points, as you asked for the use cases. I hope this helps. 🙂
