### ISSUE TITLE
/summaries ignoring user path

### ISSUE THREAD

**Issue by jsbrain** [muety/wakapi#455]
**Describe the bug**

Requesting data from `/compat/wakatime/v1/users/{user}/summaries` always returns data for the `current` user.

**System information**
Please provide information on:
* Wakapi version: 2.6.0
* Operating system
    * Docker: 2.6.0
* Database: Postgres

**Comment by muety** [comment]
Good spot! Will fix that.

**Comment by muety** [comment]
Wanna wait for #454 (and potentially #452) to be fixed before publishing a new release.
