### ISSUE TITLE
API tests failing randomly

### ISSUE THREAD

**Issue by muety** [muety/wakapi#457]
@YC Any idea why this is happening? See https://github.com/muety/wakapi/actions/runs/3932705883/jobs/6725583293 for example. Retrying once or twice usually fixes the issue.

**Comment by YC** [comment]
If you're referring to the network socket disconnected error, it's about retrieving `worldtimeapi`. 
```
  GET https://worldtimeapi.org/api/timezone/Europe/Berlin [errored]
     Client network socket disconnected before secure TLS connection was established
```
We could potentially change to http. 

If you're referring to the 400 Bad Request, I think we need verbose logging to determine why that's the case. 
See "test-fail" branch. 
From looking at it briefly, I think that the first register fails with 400, and the second register which is supposed to 409 Conflict succeeds.

**Comment by muety** [comment]
Ah sorry, my bad. The worldtimeapi error is an obvious one. But I thought I also saw tests more or less randomly failing recently, where the first (or first few) request made from newman to the API raised an error because of the server not yet being reachable or something. Anyway, I'll keep having an eye on this and keep you posted!

**Comment by YC** [comment]
https://github.com/muety/wakapi/actions/runs/3963068833/jobs/6791216275
The error is "Error: Invalid parameters".

**Comment by muety** [comment]
I suspect the [`CheckEmailMX()`](https://github.com/muety/wakapi/blob/master/models/user.go#L196) to be the bad guy here, because I think that's the only potential cause for running into the [`invalid parameters`](https://github.com/muety/wakapi/blob/master/routes/login.go#L171) error. Maybe the GitLab runner has problems performing DNS queries, but I'm wondering why it's sometimes working and sometimes failing then :shrug:

**Comment by YC** [comment]
I added some logging. 
https://github.com/muety/wakapi/actions/runs/3972433471/jobs/6810614077#step:6:91

**Comment by muety** [comment]
https://github.com/muety/wakapi/actions/runs/4518167692/jobs/7957855302

**Comment by muety** [comment]
Why closed? I think the issue is still occurring sometimes and I'd really want to get it fixed eventually.

**Comment by YC** [comment]
I think this issue is perhaps an issue with the ci infrastructure. 
For now, I don't see this in recent runs. 
Please reopen if there's another occurrence.
