### ISSUE TITLE
[Feature Request] merge alias for editors and OS

### ISSUE THREAD

**Issue by xxchan** [muety/wakapi#459]
e.g., VS Code and vscode, Mac and darwin

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/37948597/213581572-f0c2e19e-6184-4d12-8db8-9ebbc30e4c96.png">

**Comment by muety** [comment]
You can define aliases under _Settings_ -> _Data_ -> _Aliases_, if that helps?
