### ISSUE TITLE
Disable Homepage on self hosted instances

### ISSUE THREAD

**Issue by GioPan04** [muety/wakapi#460]
When you self host an instance of wakapi the main page when you are not logged in is the "default" homepage.
It would be nice if you can disable the homepage and directly redirect to the login page.
Other services like plausible do this.

**Comment by GioPan04** [comment]
I think I can make a PR if needed.

**Comment by muety** [comment]
Not sure what would be the exact benefit of this, but sure, go for it! Should be quite straightforward. Can be another config parameter besides `allow_signup`.

**Comment by Mayuresh0072** [comment]
@muety Hello, I want to work on this issue. Please Assign me this issue. Thanks.

**Comment by muety** [comment]
Hey @Mayuresh0072, thanks for offering your support on this! Unless @GioPan04 wants to tackle this, feel to give it a go.

**Comment by Mayuresh0072** [comment]
@GioPan04 Hello, can I work on this issue , if you are not doing it. Thanks.

**Comment by GioPan04** [comment]
Yeah, sure. Go for it

**Comment by Mayuresh0072** [comment]
Can You please guide me on where should me make changes for solving this issue?

**Comment by YC** [comment]
Hi @Mayuresh0072, this might not be comprehensive, but at minimum:

Add configuration value, next to `allow_signup` as mentioned above. 
https://github.com/muety/wakapi/blob/master/config/config.go#L89
Make it default to false as to not break backwards compatibility. 
Document this in `README.md` and `config.default.yml`. 

Modify https://github.com/muety/wakapi/blob/master/routes/home.go#L40-L51
The current code shows an example of checking for cookie and redirecting to login. 
You'll need to extend this such that if the user's not logged in and the configuration value is true (which can be read from `h.config`), redirect to the login page.

**Comment by Mayuresh0072** [comment]
@YC Thank you for the guidance. I have set the configuration value to false. Now, In home.go file, what I need to do exactly? Actually I am new to Go language, So I need your help . Thank you.

**Comment by YC** [comment]
@Mayuresh0072 You will probably want to split Line 46 `cookie.Value != ""` into another conditional. 
So roughly:

```
if cookie, err := ...; err == nil
    if cookie is not set and disable homepage is enabled
        redirect to login, return
    if cookie is set
        redirect to summary, like before
```

**Comment by Mayuresh0072** [comment]
@YC thank you so much. Is the "disable homepage" defined?  i am not able to find disable homepage variable. Please guide. Thank You.

**Comment by muety** [comment]
> i am not able to find disable homepage variable

I think this is what you signed up for implementing 😃. I appreciate your motivation to help out here! But, frankly, if you'd need instructions for every required step, maybe someone with a bit more experience might take over instead? Please don't take this as offense by any means!

**Comment by GioPan04** [comment]
@muety could you assign me to this?

**Comment by muety** [comment]
@GioPan04 Any updates on this?

**Comment by GioPan04** [comment]
I haven't been able to work on this. School and work are keeping me busy
