### ISSUE TITLE
Mapping files with no extensions

### ISSUE THREAD

**Issue by IgnisDa** [muety/wakapi#466]
I work on bash scripts that do not have any extensions. Is there a way I can set the language association for such files? Right now they show up as "unknown" on the dashboard.

**Comment by muety** [comment]
See https://github.com/wakatime/wakatime-cli/issues/821.

Changing the language for certain files in retrospect is not something that Wakapi supports. When self-hosting your own instance, you'd probably have to run a manual database query.
