### ISSUE TITLE
After Attempting To Sync Upstream, Fails to record to local Wakapi

### ISSUE THREAD

**Issue by LAX18** [muety/wakapi#468]
**Describe the bug**
After I attempted to add Wakatime upstream integration, all heartbeats would only be recorded to Wakatime and now, after disabling the integration, heartbeats will not be recorded to local database at all.

**System information**
* Ubuntu Server - Proxmox LXC Container
* Wakapi version: v.2.6.1

Below is from the systemd log as the only warning:
```Feb 17 15:40:58 ubuntu-server-13 wakapi[529]: 2023-02-17T15:40:58.339939425-10:00 [WARN ] summary from 2023-02-16 19:00:19.083 -1000 HST to 2023-02-17 15:39:31.942 -1000 HST (user 'LAX18') was attempted to be processed more often than once```

**Comment by muety** [comment]
Hi @LAX18, thanks for reporting this issue. Never saw that happening before and can't reproduce it locally, though. Can you give a couple more details, please? 

So you enabled to relay heartbeats to WakaTime on the Settings page, by pasting your WakaTime token and setting the endpoint URL to `https://wakatime.com/api/v1`, correct? From that moment on, no more coding data were appearing in your local Wakapi? Did it appear on WakaTime, though? Then, you disconnected from WakaTime again and still couldn't see new data flowing in to Wakapi? What time interval were you looking at? Can you see the heartbeats in your database's `heartbeats` table?

Also, could you potentially post a full log of the above process (connect WakaTime, do coding to send heartbeats, disconnect WakaTime, do coding again to send more heartbeats), including `INFO` log messages?

**Comment by LAX18** [comment]
I've set the relay information correct and the heartbeats properly show up in Wakatime. I imported from Wakatime as well on first connect. Then it would only pass through packets to Wakatime and not record them locally. I have the interval set to today where no heartbeats would show.  Then I attempted creating a new prpject and sending heartbeats that way to check it against the all time interval.  I'll send a full log tonight and if you have the capability, I could send a backup of the LXC container it is running on. It's a proxmox LXC ubuntu server container

**Comment by muety** [comment]
Thanks for the update. A full log could potentially be helpful, so could a backup of your container - but, of course, only if it doesn't contain any sensitive information or the like that you wouldn't wanna disclose to me. If you want to share the container, send it my way via e-mail (see my GitHub profile) and I'll have a look! 

What could be helpful in addition is a a heartbeats dump from WakaTime, using their [`/heartbeats` endpoint](https://wakatime.com/developers#heartbeats). If you like, call that endpoint for a single day for which you have missing data in your Wakapi and send the JSON file my way as well.

**Comment by LAX18** [comment]
I found a solution by rolling back to a previous version of the container from a week ago. I almost wonder if my attempted sync confused the database hence the 'attempted to be processed more than once.'. Im going to take a look at both containers and see if there's any glaring security issues, otherwise I will package and email them to you!

**Comment by muety** [comment]
@LAX18 Any updates on this after my last e-mail message?

**Comment by LAX18** [comment]
@muety Must have missed your email! I rolled back to my previous container version, let me see if I can reproduce the issue

**Comment by LAX18** [comment]
I am unable to reproduce, so i'm willing to write it off as a database corruption error.
