### ISSUE TITLE
Support for .astro files

### ISSUE THREAD

**Issue by qhantom** [muety/wakapi#469]
Currently, there's no support for `.astro` files. [Astro](https://astro.build/) is one of the most popular SSG/SSR frameworks. In my opinion, it makes sense to support it.

Thanks a lot!

**Comment by muety** [comment]
Thanks for bringing this up! I'll have a look soon. Also, PRs are always welcome :-)

**Comment by muety** [comment]
Added support for Astro! However, this will only apply to newly inserted data. If you want to change historic data retroactively, you'll have to _Clear & Regenerate Summaries_ under _Settings -> Danger Zone_.

**Comment by qhantom** [comment]
> Added support for Astro! However, this will only apply to newly inserted data and data inserted _today_. If you want to change historic data retroactively, you'll have to _Clear & Regenerate Summaries_ under _Settings -> Danger Zone_.

Thanks for the fast implementation, I do appreciate it 🥳
