### ISSUE TITLE
SMTP: Missing required header field: "Date"

### ISSUE THREAD

**Issue by cestoliv** [muety/wakapi#472]
I think there is a problem with sending email. It seems that the Date header is missing.

Link to the 2822 mail RFC: https://www.rfc-editor.org/rfc/rfc2822#section-3.6.1

Here is the problem at the mail server level:
```
The message WAS NOT relayed to:
  <my@email.address>:
   554 5.6.0 Bounce, id=08126-11 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
mail.server.fr. Our internal reference code for your message is
08126-11/wjbTaPo6cqYm

INVALID HEADER

  Missing required header field: "Date"

Return-Path: <wakapi@server.fr>
From: Wakapi <wakapi@server.fr>
Subject: Wakapi - Password Reset
```

And the sent header (where the Date is missing)
```
Return-Path: [<wakapi@server.fr>](mailto:wakapi@server.fr)
To: [my@email.address](mailto:my@email.address)
DKIM-Signature: ...
From: Wakapi [<wakapi@server.fr>](mailto:wakapi@server.fr)
Subject: Wakapi - Password Reset
Content-Type: text/html; charset=UTF-8
```

**System information**
* Wakapi version: `2.6.2`
* Operating system: Docker, `n1try/wakapi:latest`
* Database: `PostgreSQL`

**Comment by muety** [comment]
Thanks for reporting this! I'll fix this as soon as possible!

**Comment by muety** [comment]
Fixed, will be released soon!

**Comment by cestoliv** [comment]
Many thanks!
