### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by CMiksche** [muety/wakapi#475]
**Describe the bug**
All the badges on https://wakapi.dev are not being displayed anymore. They return `404 page not found`

**System information**
Cloud service wakapi.dev

**Comment by muety** [comment]
Hi @CMiksche, can you give an example? Everything seems to be working fine for me.

**Comment by CMiksche** [comment]
Yes, see for example: https://wakapi.dev/api/badge/Wronnay/interval:week/project:frontend

I get a `404 page not found` back even though it shows on the GUI that I worked multiple hours on that project in the last days...
