### ISSUE TITLE
Docker Image for 2.7.0

### ISSUE THREAD

**Issue by YC** [muety/wakapi#476]
Hi @muety, the 2.7.0 action for Docker doesn't seem to have triggered. 
Edit: I have created docker-release branch with a commit to make the docker release action consistent with release.

**Comment by muety** [comment]
Thanks for this! Any clues about why the action didn't trigger? Also, do you know of a convenient way to manually trigger that action retroactively, while "simulating" a release-publish event?

**Comment by YC** [comment]
My guess is that it's related to `[skip ci]`. 
Now that it's consistent, hopefully it will work in the future with my change to the actions file. 

A method may be to delete the tag and retag it, but that's probably not the best idea from a traceability perspective. 
So yes, perhaps a manual push?

**Comment by sdvcrx** [comment]
@muety @YC Hello! I wanted to bring to your attention that the current docker image version `2.7.0` lacks multi-platform support, which is causing issues when running it on an ARM-based machine.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/5170232/227839303-df25ef0b-7208-4bbf-b26a-6f6fb2c2cbd3.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/5170232/227839331-411250b8-de27-429e-9141-272afd11063f.png">

**Comment by YC** [comment]
Thanks @sdvcrx. 
@muety Sorry that I didn't anticipate this.
I've tried `workflow_dispatch`, but it wouldn't trigger via web or api since the event was not present in 2.7.0. 
![image](https://user-images.githubusercontent.com/5828744/227919666-166edf54-5198-4179-8cce-09ccde19bb27.png)
Perhaps a minor release, if it's not too much trouble?

**Comment by muety** [comment]
@sdvcrx Thanks for bringing this up!

@YC Thanks for looking into this!

I never really got in touch with multi-platform Docker images, but looks like "cross-compilation" is supported (see [here](https://docs.docker.com/build/building/multi-platform/)). Instead of creating a new release (without any actual changes contained), I'd probably rather prefer to just push manually built images for `arm64` and `armv7` as well.

I'll give it a shot and keep you posted.

**Comment by muety** [comment]
Please try again!

For the record, this is the command I used: 

```bash
docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 \
	-t ghcr.io/muety/wakapi:latest \
	-t ghcr.io/muety/wakapi:2.7.0 \
	-t ghcr.io/muety/wakapi:2.7 \
	-t ghcr.io/muety/wakapi:2 \
	-t ghcr.io/muety/wakapi:alpine \
	-t n1try/wakapi:latest \
	-t n1try/wakapi:2.7.0 \
	-t n1try/wakapi:2.7 \
	-t n1try/wakapi:2 \
	-t n1try/wakapi:alpine \
	.
```
