### ISSUE TITLE
Migrate from `logbuch` to `slog`

### ISSUE THREAD

**Issue by muety** [muety/wakapi#480]
* For general logging: https://pkg.go.dev/log/slog
* For Sentry integration: https://github.com/samber/slog-sentry
* For request logging: https://github.com/samber/slog-http

Other logging packages considered: 
* ~~https://github.com/uber-go/zap~~
* ~~https://github.com/TheZeroSlave/zapsentry~~

**Comment by muety** [comment]
Btw., interesting talk: https://www.youtube.com/watch?v=tC4Jt3i62ns

**Comment by muety** [comment]
https://www.reddit.com/r/golang/comments/16ebwk4/how_you_are_using_slog_your_experience_pls/

**Comment by muety** [comment]
Alternatively: https://github.com/rs/zerolog

**Comment by finnng** [comment]
Hi @muety, I can help work on this issue. 
I'm going to use the packages as you mentioned.
- https://pkg.go.dev/log/slog
- https://github.com/samber/slog-sentry
The ticket was created a year ago. Do you have any more suggestions?

**Comment by muety** [comment]
As we're trying to use as few external dependencies as possible in Wakapi, I'd vote for building the structured logging part all around `slog`. Didn't do any further research about potentially helpful companion packages since opening this ticket, though. 

Switching to structured logging requires a bit of a mind shift in how to phrase log messages. The above Reddit post explains it quite well. So be aware that there's probably more to this ticket than simply replacing all log statements with `slog` method calls. It's probably quite a bit of refactoring work, with no - unfortunately - no benefit to the user whatsoever. Just keep that in mind before jumping onto this. If you think this is worth you're time nonetheless, I'd be super happy the help, of course! :raised_hands:.

**Comment by finnng** [comment]
Hi @muety , the PR is ready to review here https://github.com/muety/wakapi/pull/667

**Comment by muety** [comment]
Reopening this issue as migration to `slog-sentry` and `slog-http` (see [here](https://github.com/muety/wakapi/pull/667#discussion_r1723857057) and above) are still pending.

**Comment by muety** [comment]
@finnng You wanna take this for round two?

**Comment by finnng** [comment]
> @finnng You wanna take this for round two?

Yeah, I will find the time for it. Can you assign this ticket to me?

**Comment by muety** [comment]
Any updates on this? Don't feel pressure, just wanted to hear about the current status.

I plan to implement #607 some time in the next days and intend to push a big new release then. Would be cool to have the full logging refactoring included by then. But again, no stress still!

**Comment by finnng** [comment]
@muety I'm having a busy week. I probably will have some time this weekend. Regarding the slog-sentry and slog-http, I'm not so sure how to integrate them into Wakapi and how they will improve the logging. I mean, I don't have a big reason for it. Can you give some direction on this?

**Comment by muety** [comment]
Regarding Sentry: we currently log plain strings to Sentry, even though we already have structured information present after your refactorings. Migrating to slog-sentry would result in the individual properties / key-value pairs be passed to Sentry as such as well. This way we can directly work on those fields in Sentry, instead of dealing with plain text.

Regarding http logging: so far, we rolled our own, custom build request logging middleware [here](https://github.com/muety/wakapi/blob/master/middlewares/logging.go). Now that we have structured logging, we could instead benefit from already existing, well-tested, well-maintained request logging code, where we can simply pass in a request and have the library extract all useful information in a structured way.

**Comment by muety** [comment]
Closed by #673.

Regarding request logging: I had a quick look at this and, firstly, figured that [slog-chi](https://github.com/samber/slog-chi) would be the right pick for us instead of [slog-http](https://github.com/samber/slog-http). Replacing our custom `LoggingMiddleware` with that library is literally a one-liner. But I decided to keep things as is, mainly because (a) the package would pull in another couple of dependencies (related to OpenTelemetry, which we don't need at this time) and (b) I actually like our less verbose, more "minimal" request logging style even better.

slog integration is done, I'd say! :raised_hands: Thanks, @finnng.
