### ISSUE TITLE
Can't import/migrate data from hakatime

### ISSUE THREAD

**Issue by phamleduy04** [muety/wakapi#482]
Hi, I have using hakatime for a while and I want to migrate data from hakatime to wakapi.

I have tried 
`https://<your-server>/api/compat/wakatime/v1` and `https://<your-server>/api/v1` but still showing error below:

![image](https://user-images.githubusercontent.com/32657584/233819554-63b61145-be0a-4e10-a31e-36eb85b925a5.png)

I'm using docker version

Image: `ghcr.io/muety/wakapi:alpine` and `postgres:12.3`

**Comment by muety** [comment]
Hi @phamleduy04, it looks like Hakatime doesn't have an endpoint for fetching heartbeats, see [here](https://github.com/mujx/hakatime/blob/master/src/Haka/Handlers/Heartbeats.hs). You may try to file an issue with them. Unfortunately, nothing that could be done on Wakapi's side.
