### ISSUE TITLE
SMTP error not sending emails

### ISSUE THREAD

**Issue by chopanovv** [muety/wakapi#483]
Hello i am running wakapi container in Kubernetes cluster! i have smtp mail at yandex!
```[ERROR] failed to send password reset mail to vchopanov - tls: first record does not look like a TLS handshake``` error is like this!
SMTP mail is working checked with grafana or other mail services!

**Comment by muety** [comment]
Can you show the SMTP-related section of your config, please (without password, of course)?

**Comment by chopanovv** [comment]
of course 
WAKAPI_MAIL_SMTP_HOST=smtp.yandex.ru
WAKAPI_TLS_CERT_PATH=
WAKAPI_INSECURE_COOKIES=false
WAKAPI_DB_MAX_CONNECTIONS=2
WAKAPI_DB_TYPE=
WAKAPI_BASE_PATH=/
WAKAPI_DB_SSL=false
WAKAPI_MAIL_SMTP_TLS=true
WAKAPI_DB_PASSWORD=mypassword
WAKAPI_DB_PORT=
WAKAPI_EXPOSE_METRICS=true
WAKAPI_ALLOW_SIGNUP=true
WAKAPI_DB_NAME=
WAKAPI_DB_CHARSET=
WAKAPI_MAIL_SMTP_USER=wakapi@test.com ("edited")
WAKAPI_DB_USER=
WAKAPI_COOKIE_MAX_AGE=172800
WAKAPI_PASSWORD_SALT=
WAKAPI_MAIL_SMTP_PASS=
WAKAPI_DB_HOST=
WAKAPI_MAIL_SMTP_PORT=587
WAKAPI_LISTEN_IPV4=0.0.0.0
WAKAPI_LISTEN_IPV6=
WAKAPI_PORT=3000
WAKAPI_TLS_KEY_PATH=
WAKAPI_MAIL_PROVIDER=smtp

when i do forgot password here is logs. 
<img width="1072" alt="Screenshot 2023-04-29 at 10 14 17" src="https://user-images.githubusercontent.com/96824080/235285123-a4ce8b4f-544c-4285-a7b0-3a6bacd00b7e.png">

**Comment by muety** [comment]
Looks correct. Potentially wrong port? You're using 587, but the [docs](https://yandex.com/support/mail/mail-clients/others.html#smtpsetting) say it's 465.

**Comment by chopanovv** [comment]
No port is correct i checked in other services!

**Comment by muety** [comment]
587 is usually the port to be used for STARTTLS connections, while 465 is for TLS / SSL connections. So I'd assume either set `WAKAPI_MAIL_SMTP_TLS=false` and keep port as 587, or set port to 465 and keep `WAKAPI_MAIL_SMTP_TLS=true`. The latter is recommended.

**Comment by chopanovv** [comment]
<img width="605" alt="Screenshot 2023-05-05 at 12 23 09" src="https://user-images.githubusercontent.com/96824080/236399152-69038028-9dc6-4c43-904f-f15e445a44d5.png">

**Comment by muety** [comment]
Is it always the exact same error message, no matter what settings you use?

**Comment by chopanovv** [comment]
in the latest configuration there no error! but emails are not coming! when use 587 there is TLS handshake error

**Comment by muety** [comment]
So e-mails are not arriving even though there is no error message? Not even in spam / junk folder?

**Comment by chopanovv** [comment]
yes not even in spam / junk folder! also i checked with different emails! same thing!

**Comment by muety** [comment]
What are your latest configuration?

**Comment by chopanovv** [comment]
https://github.com/muety/wakapi/issues/483#issuecomment-1535840355 this my latest conf

**Comment by muety** [comment]
Did you try `smtp.yandex.com` instead of `smtp.yandex.ru`, as mentioned in the docs?

**Comment by chopanovv** [comment]
just tried not working!

**Comment by muety** [comment]
Very weird. `smtp.yandex.com` with port 465 and TLS should be working. Unfortunately, can't reproduce this, since I don't have a Yandex account (and not willing to pay tbh).

**Comment by muety** [comment]
Hi @uniform641,

when using port 587 (intended for STARTTLS), you'll have to set `tls: false`. For details, see [here](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040).

**Comment by uniform641** [comment]
@muety Thanks for your reply! I didn't map `StartTLS` correctly to `tls:false` in config. 

Maybe it's better to add a comment for `tls` in config file to specify how to config `StartTLS`?

**Comment by uniform641** [comment]
@muety Sorry I didn't notice that. Thanks very much!
