### ISSUE TITLE
Expose per-user coding stats as Prometheus metrics

### ISSUE THREAD

**Issue by chopanovv** [muety/wakapi#484]

**Comment by muety** [comment]
If the user, that you're requesting the `/metrics` endpoint with, is an admin user (`is_admin` flag on the user object), all metrics, including such prefixed with `wakatime_admin_*`, should be included.

**Comment by chopanovv** [comment]
User that i request is admin! in prometheus i am getting wakatime_admin_*
<img width="493" alt="Screenshot 2023-04-29 at 10 31 35" src="https://user-images.githubusercontent.com/96824080/235285492-62260fbe-3d7d-4917-8036-a121af83edf8.png">
assume that i have small team! i and i want to make dashboard in grafana for metrics 
-- all spent time for each language for all team
-- all user that how many time spent 
and so on
 how can i do that in `wakapi_admin_*` just 4 labels

**Comment by muety** [comment]
Per-user coding stats (languages, editors, etc.) are indeed not exposed through the metrics endpoint. You can always only get the ones for the current user, who is doing the request. So currently, you would have to have a separate Prometheus scrape job for every member of your team, including their respective API keys.

I can add this as a feature request, but with low prio, though. So please don't expect me to get to implementing this any time soon.

**Comment by muety** [comment]
We won't expose entity-specific data (languages, projects, editors, etc.) as part of Prometheus metrics, because it would blow up [cardinality](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels) way too much. 

Total coding time per user will be included from the next release on.
