### ISSUE TITLE
Github Readme Stat error

### ISSUE THREAD

**Issue by phamleduy04** [muety/wakapi#485]
I have a problem with my Wakapi instance and GitHub-readme stats.

URL: 
```
https://github-stats.agentbot.xyz/api/wakatime?username=phamleduy04&api_domain=wakatime.agentbot.xyz&bg_color=2D3748&title_color=2F855A&icon_color=2F855A&text_color=ffffff&custom_title=Wakapi%20Week%20Stats&layout=compact)
```
Error:
![image](https://user-images.githubusercontent.com/32657584/236646140-9a5b1815-f97b-40ef-87d1-3163e799e742.png)

I also enabled Public Data: 

![image](https://user-images.githubusercontent.com/32657584/236646154-eb33c8f1-2271-4e5f-99c2-3730352ced76.png)

**Comment by muety** [comment]
Hi @phamleduy04, you set your maximum data range to 10 days, while the default range requested by Readme Stats is `all_time`. Either set you time range setting to `-1` or add `&range=last_7_days` to the image URL. That should help.

**Comment by phamleduy04** [comment]
I just set my time range to -1 and the error still popping up

<img width="1023" alt="Screen Shot 2023-05-08 at 2 24 15 PM" src="https://user-images.githubusercontent.com/32657584/236914214-31a2e587-0d01-4a65-9886-9cd5355857e7.png">


![](https://github-readme-stats.vercel.app/api/wakatime?username=phamleduy04&api_domain=wakatime.agentbot.xyz&bg_color=2D3748&title_color=2F855A&icon_color=2F855A&text_color=ffffff&custom_title=Wakapi%20Week%20Stats&layout=compact)

**Comment by muety** [comment]
At least the error is a different one now ("user not found"). API domain and username seem to be correct, though. The only thing I could imagine as a potential issue is the fact that you seem to have CloudFlare protection in front of your Wakapi instance. Maybe that causes problems with Readme Stats. Could you try to temporarily disable it and try again? 

Also, do you see the request from Readme Stats coming through to your Wakapi instance? There you be an incoming request in the logs.

**Comment by phamleduy04** [comment]
Found the issue. After checking events on cloudflare I see github stats being set as "bot" and got blocked.

Turn off Bot Fight Mode will fix the issue since there is no way to bypass this using firewall rule.
![image](https://github.com/muety/wakapi/assets/32657584/70d2d0ed-06a7-44d9-9870-2f05b026194b)

**Comment by muety** [comment]
Very interesting! Thanks for reporting back.
