### ISSUE TITLE
Add missing hours

### ISSUE THREAD

**Issue by IThundxr** [muety/wakapi#489]
Basically I’ve got 282 hours of coding time from wakatime last year but I don’t wanna import my wakatime stats cause that messes up the projects a lot and shows a bunch of redundant ones so is it possible to add all this time but not have it show under unknown? So like it exists but under no project

**Comment by IThundxr** [comment]
Actually I'm fine with it showing up as unknown as I've made unknown remap to Master

**Comment by muety** [comment]
Hi @IThundxr, there is no way to add coding time into Wakapi other than heartbeats. Would be interesting to know where these importing issues originate from. Can you give an example of a project that was display properly on WakaTime, but not anymore in Wakapi? Maybe a few exemplary heartbeats as JSON for that project from both instances? Or at least a couple of screenshots? Would love to debug this issue!

**Comment by IThundxr** [comment]
> Hi @IThundxr, there is no way to add coding time into Wakapi other than heartbeats. Would be interesting to know where these importing issues originate from. Can you give an example of a project that was display properly on WakaTime, but not anymore in Wakapi? Maybe a few exemplary heartbeats as JSON for that project from both instances? Or at least a couple of screenshots? Would love to debug this issue!

I’ve got 281 hours in wakatime but if I import them I get a lot of old redundant projects that I don’t want to show in the projects area maybe a toggle for hiding projects there would be helpful

**Comment by IThundxr** [comment]
> But those projects are not showing on WakaTime? Why not?

They don't show in wakatime because I don't have premium so I can't see all time and stuff but in wakapi I can see all time stats so a lot of my old projects show is there anyway to add 281 hours to the total but in a hidden way?

**Comment by muety** [comment]
> is there anyway to add 281 hours to the total but in a hidden way?

No, there isn't. All coding time tracked in Wakapi must correspond with actual heartbeats data. 

Would it have helped if there was an option to choose which projects or what time span to import? Or if there was a way to retroactively delete all data for a given project from Wakapi?

**Comment by IThundxr** [comment]
> > is there anyway to add 281 hours to the total but in a hidden way?
> 
> 
> 
> No, there isn't. All coding time tracked in Wakapi must correspond with actual heartbeats data. 
> 
> 
> 
> Would it have helped if there was an option to choose which projects or what time span to import? Or if there was a way to retroactively delete all data for a given project from Wakapi?

I feel like the second option would help more being able to just delete data for a project

**Comment by IThundxr** [comment]
Or mark the time as unknown

**Comment by muety** [comment]
> Or mark the time as unknown

What do you mean by mark the time as unknown?

**Comment by IThundxr** [comment]
> > Or mark the time as unknown
> 
> 
> 
> What do you mean by mark the time as unknown?

On my instance a bunch of my hours coding show up as "unknown" basically not linked to any language or project

**Comment by muety** [comment]
And you would wanna exclude them from being counted in your total coding time?

**Comment by IThundxr** [comment]
> And you would wanna exclude them from being counted in your total coding time?

Well personally I'd like them to counted in the total time but maybe other people might want it to be toggleable
