### ISSUE TITLE
Question: Data Analysis

### ISSUE THREAD

**Issue by ethanleifer** [muety/wakapi#491]
Hi!

I am looking into building some data models to understand different things about my coding time. For example:

Some initial questions include: 
- My most productive hour of the day
- cumulative time spent in each entity/repo/lang/branch over time

And I am looking to create more visuals based on this data

I am having trouble finding the logic for the aggregation of heartbeats. Could you point me toward a specific file or function?

**Comment by muety** [comment]
Check the _How are durations calculated?_ section of the FAQ. Hope that helps!

Cumulative time spent per repo, etc., you can probably get right from Wakapi's endpoints.
