### ISSUE TITLE
Version tag missing/wrong

### ISSUE THREAD

**Issue by Skillkiller** [muety/wakapi#495]
**Describe the bug**
On the home page, in the lower left corner, you can see the current version number. Here is a screenshot of the [wakapi.dev](https://wakapi.dev/) server.
![grafik](https://github.com/muety/wakapi/assets/18444809/667a04e2-965f-4d04-9975-caf566bc560c)

For the Docker images with the tags following tags, this version number is wrong on the web page:
- 2
- 2.7
- 2.7.0
- (latest) - Depending on the point of view whether this is a dev version or not

These versions have the following version number on the home page:
![grafik](https://github.com/muety/wakapi/assets/18444809/4b782bfa-2523-46b9-a043-66fc94b53781)

To check, I tested a few more older tags and they each showed the version number as expected:
- [x] 2.6
- [x] 2.5
- [x] 2.4

**System information**
Please provide information on:
* Wakapi version: `2.7.0`
* Operating system
    * If Linux: which distro?
    * If Docker: `ghcr.io/muety/wakapi:2`
* Database: `mysql`

**Comment by YC** [comment]
Thanks for the report.
This is due to this image being built manually. 
See #476

**Comment by muety** [comment]
Version number should be shown as expected again once the next release image is out.
