### ISSUE TITLE
Question: new to wakapi, found that the badge was not shown properly

### ISSUE THREAD

**Issue by shinyypig** [muety/wakapi#498]
I ran wakapi according to `Option 2: Quick-run a release` in README.md. Everything works fine, except that the badge was not shown properly:

<img width="376" alt="image" src="https://github.com/muety/wakapi/assets/30233673/8a997e79-d631-4387-9fc4-c1467d6a210f">

When I open the badge in a new tab, it says:

> requested time range too broad

However, the url is `https://wakapi.xxxxx.xxx/api/badge/shinyypig/interval:today/project:矩阵之美-xxx`

No matter whether I set the time interval to day, week, or something else, it cannot be displayed correctly.

Is it normal? Do I just need to wait for a while?

p.s. I have imported my data from Wakatime ever since I created my account.

**Comment by muety** [comment]
Please go to _Settings -> Permissions_ and under _Public Data_, set the _Time Interval_ to a number in days greater or equal to what your badges requires. Also, I think you'll have to at least enable data sharing for projects as well. See if that helps.

**Comment by shinyypig** [comment]
Solved! Thank you very much for your help.

This project is truly helpful.

**Comment by muety** [comment]
I'm glad you like it! :-)
