### ISSUE TITLE
'unknown' language (JSX)

### ISSUE THREAD

**Issue by dawnerd** [muety/wakapi#50]
Is there any way to add new languages in? Currently shows about half of my time as unknown.

I see the alias feature has a language option but I'm not sure what the values for that would be (or if it even works the way I think)

Awesome project btw!

**Comment by muety** [comment]
Hi @dawnerd, thanks for the feedback. What you could to is modify your `config.ini` and add a new line with `jsx = JSX` to the `[languages]` section. This tells Wakapi to consider every file with a `.jsx` ending to be of `JSX` language. Alternatively you could also write `jsx = React` or so. 

I'm going to include this a default in the next release, just like I already did with `Vue`.

**Comment by dawnerd** [comment]
omg that was so obvious, that's a nice way to do it!
