### ISSUE TITLE
Import from Wakatime fails when heartbeats data dump already exists

### ISSUE THREAD

**Issue by mvolfik** [muety/wakapi#502]
**Describe the bug**

I created my instance of wakapi, but restarted the instance during the import, which probably interrupted the data import. Now when I try to start it again, the UI says the import is being started, but in server log I can see that Wakatime refused to create the data dump with 400 Bad Request response. When I try to create the dump from wakatime frontend, I get the same error, with more detail: `Wait for your current export to expire before creating another.`

Wakapi should therefore list current data dumps before attempting to create a new one.

**System information**
* Wakapi version: latest docker image (2.8.1)

**Comment by muety** [comment]
Fair point, will fix!

**Comment by muety** [comment]
Done! I'll add in a couple of other small changes in the coming days before pushing out a new release, if someone minds?

**Comment by mvolfik** [comment]
thanks for the fix! no prob, I built the image from git for now
