### ISSUE TITLE
Wakatime import fails with status 400

### ISSUE THREAD

**Issue by AsterisMono** [muety/wakapi#506]
**Describe the bug**
Wakatime import fails with status 400, reproduce rate 5/5.
![image](https://github.com/muety/wakapi/assets/54884471/f66eec5b-400e-4a37-9908-38950e3f5e64)

**System information**
Please provide information on:
* Wakapi version: 2.8.1
* Operating system: Ubuntu 22.10 x86_64
* Database: SQLite

What's interesting is that the same API key _works fine_ on [wakapi.dev](https://wakapi.dev/), the offical instance.

**Comment by muety** [comment]
Interesting :thinking:. Could you do me a favor and post the result of running the following command shortly after you attempted an import?

```bash
curl https://wakatime.com/api/v1/users/current/data_dumps -H "Authorization: Basic $(echo '<your_api_key_here>' | base64)"
```

(you may want to redact parts of the actual download URLs returned, if there are any)

**Comment by AsterisMono** [comment]
Sure, here you are:
```
root@Momoi:~# curl https://wakatime.com/api/v1/users/current/data_dumps -H "Authorization: Basic $(echo '<API-KEY>' | base64)"
{"data": [], "total": 0, "total_pages": 1}
```

### More Information on the environment
I'm using a [pre-built binary release](https://github.com/muety/wakapi/releases/tag/2.8.1), and have set up a systemd service for autostart and keep-alive:
```
root@Momoi:~# cat /etc/systemd/system/wakapi.service 
[Unit]
Description=Wakapi
StartLimitIntervalSec=400
StartLimitBurst=3

[Service]
Type=simple

# Assuming Wakapi executable is under /opt/wakapi and config file at /etc
# Feel free to change this
WorkingDirectory=/opt/wakapi
ExecStart=/opt/wakapi/wakapi -config /etc/wakapi.yml

# sudo groupadd wakapi
# sudo useradd -g wakapi wakapi
User=wakapi
Group=wakapi
RuntimeDirectory=wakapi  # creates /run/wakapi, useful to place your socket file there

Restart=on-failure
RestartSec=90

# Security hardening
PrivateTmp=true
PrivateUsers=true
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
PrivateDevices=true
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ProtectClock=true
RestrictSUIDSGID=true
ProtectHostname=true
ProtectProc=invisible

[Install]
WantedBy=multi-user.target
```

The instance is hosted on a DigitalOcean Droplet located in `SGP1`.

**Comment by muety** [comment]
Glad to hear! I'll add some more detailed logging, to better debug issues like this next time.
