### ISSUE TITLE
Infer stats endpoint default range from user settings

### ISSUE THREAD

**Issue by judemont** [muety/wakapi#508]
I'm looking for code time statistics for the year, but I can only get them for the week.

Github-readme-stats link :   https://github-readme-stats.vercel.app/api/wakatime?username=judemont&api_domain=wakapi.dev

**Comment by muety** [comment]
Wakapi returns last week by default, if no `range` param is specified. The proper way to go about this would be to add the option to specify a `range` param in [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) tool. I'd propose to file an issue upstream.

**Comment by judemont** [comment]
Ok, thanks
