### ISSUE TITLE
UI controls for filtering

### ISSUE THREAD

**Issue by hinricht** [muety/wakapi#511]
Hi, 

first of all thanks so much for this great project :heart: 

My usecase is: I configured my personal Laptop and my work Laptop to use the same wakapi account, in the hope that I would easily be able to filter by hostname (i.e. I'd like to know how many hours I *worked* even if I used my personal Laptop in the remaining spare time).
Is this possible already (then I haven't found it) ? Or is the best practice to use two separate accounts (If possible I'd prefer one account).

**Comment by muety** [comment]
Hi @hinricht, glad to hear you like Wakapi! What you can do is get your coding stats aggregated per machine, if that helps?

![grafik](https://github.com/muety/wakapi/assets/8978843/0fea0e11-6e76-4e6a-ab23-f81884cd0fb3)

**Comment by hinricht** [comment]
Oh nice, I didn't notice the Machines tab !
That's already good to have, however it would be great to filter all stats (like Projects) by Machine name.

Btw, I also have a portion of "unknown" like you have, what is that or how can I trobleshoot what's causing it ?

**Comment by muety** [comment]
I'll add this as a feature request! The API (e.g. [summaries endpoint](https://wakapi.dev/swagger-ui/swagger-ui/index.html#/wakatime/get-wakatime-summaries)) supports various filters (including by machine) already. There's only no UI for this, yet. 

What you could also do is work with project labels, but still not quite what you're looking for, I think.
