### ISSUE TITLE
Microsoft Edge Brower Plugin displays unknown in the panel

### ISSUE THREAD

**Issue by erruicoders** [muety/wakapi#516]
When I installed a new plugin developed for Microsoft Edge Brower and finish After configuring the configuration, I found that the Wakapi I deployed with Docker will not be displayed like Chrome, and it displays unknown. I don’t know why.
![image](https://github.com/wakatime/browser-wakatime/assets/75353639/c07123cc-a331-4f39-bcd9-22971621d9c5)
![image](https://github.com/wakatime/browser-wakatime/assets/75353639/df7e6bf8-c06b-4672-9714-600399b8b4d4)
![image](https://github.com/wakatime/browser-wakatime/assets/75353639/1c60c4b4-29aa-43b8-b9ec-42da95555bfe)
![image](https://github.com/wakatime/browser-wakatime/assets/75353639/07689ab0-61af-45ee-8f55-e1acf48543ea)

**Comment by muety** [comment]
Project and language will always be "unknown" for web browsing (because how to tell what "project" or in what "language" are you working then). Editor should be sth. like "Edge", though. That's a bug. I'll fix it soon.

**Comment by fromage9747** [comment]
@erruicoders How did you get it to login?  Whenever I click on login, it takes me to wakatime.  The extension will log time to my wakapi but I can't get it to display my current time from the browser plugin because I can't get it to login to my wakapi.
