### ISSUE TITLE
Fantastic Job

### ISSUE THREAD

**Issue by jeff-hykin** [muety/wakapi#518]
I just wanted to say, I've dabbled in a lot of self hosted stuff, OwnTracks, NextCloud, Discourse, Mastodon, IPFS, etc and basically all of them are huge pain to setup, even after a ton of dev experience.

Wakapi took me 30sec and was absolutely painless thanks to the readme layout. Thank you for making it awesome!

**Comment by muety** [comment]
Hi @jeff-hykin, thanks a lot! I'm super happy to hear that you're having a good experience with Wakapi 😊. Simplicity was a primary goal for Wakapi, including the initial setup. 

Let us know whenever you see any potential improvements, etc.
