### ISSUE TITLE
Syntax error in 1_imprint_content.sql with postgres

### ISSUE THREAD

**Issue by bialad** [muety/wakapi#52]
I've deployed your project to my homelab today, but got stuck a while on boot with at postgres database.

The error points to `key`, like the migration tool can't read that string.

I had to comment out the contents of 1_imprint_content.sql and apply the migration manually to be able to bootstrap the database. After doing this everything seems to work.

You don't seem to use postgres yourself, but just something to consider.

**Comment by muety** [comment]
Hi, thanks for that report! Do you have a more specific error or stack trace for me?

Pull requests are always welcome, but otherwise I'll take a look into this as soon as possible.

**Comment by muety** [comment]
Fixed it :slightly_smiling_face:. Hopefully nothing else was broken, but we'll see. Maintaining support for three different databases is harder than one might think.
