### ISSUE TITLE
Unable to retrieve data via the wakatime api

### ISSUE THREAD

**Issue by swiftwind0405** [muety/wakapi#520]
I deployed it on my own server using Docker. When I call this API (/api/compat/wakatime/v1/users/current/stats/last_30_days), it doesn't return any data, as shown in the following image:

<img width="902" alt="image" src="https://github.com/muety/wakapi/assets/4001228/bc1ed5b8-5b16-4770-8447-13e258ccf2f5">

However, when I access it on the web, it works fine:

<img width="1336" alt="image" src="https://github.com/muety/wakapi/assets/4001228/c9882b56-1702-4809-a36c-35ef040a8d4e">

Could you please let me know if I am accessing the API incorrectly?

**Comment by muety** [comment]
Are you sending an authorized request (including `Authorization` header) or an anonymous one? The endpoint you're using allows for public, unauthorized access, but in that case, will only return as much data as you gave permissions to. So possible solutions include:

- Send authentication along with the request (i.e. "log in")
- Permit public data access for at least 30 days for the entity types you want to retrieve

![image](https://github.com/muety/wakapi/assets/8978843/2186830d-f974-408a-8465-c38fdfeb9e69)

You might also want to look into the [`/summary`](https://wakapi.dev/swagger-ui/index.html#/summary/get-summary) endpoint as an alternative (also requires authentication).

**Comment by muety** [comment]
Hope that helps?

**Comment by swiftwind0405** [comment]
THX. It helps me a lot!
