### ISSUE TITLE
Sharing stats

### ISSUE THREAD

**Issue by grxx** [muety/wakapi#529]
Hi! Is it possible to share our statistics? For example like in Umami where you can generate a link to all your stats and just share it https://analytics.gra.so/share/8Apo2x8UeJEQTwA4/graso

**Comment by muety** [comment]
Hi @grxx, you cannot share all your statistics comprehensively. However, you can share some aspects in the form of [Readme Stats Cards](https://github.com/muety/wakapi#github-readme-stats-integrations) or [Readme Metrics](https://github.com/muety/wakapi#github-readme-metrics-integration) as SVGs. Hope that helps?
