### ISSUE TITLE
Support Trusted Header Authentication

### ISSUE THREAD

**Issue by rfvgyhn** [muety/wakapi#534]
I host wakapi behind a reverse proxy that uses Authelia for SSO. It would be great if wakapi supported trusted headers to automatically login.

An example project that supports this is Navidrome. When it sees the header `Remote-User` and the proxy's IP is whitelisted, the user is auto logged in and if the user doesn't exist, it is automatically created.

https://www.authelia.com/integration/trusted-header-sso/introduction/
https://www.navidrome.org/docs/usage/security/#reverse-proxy-authentication
https://github.com/navidrome/navidrome/pull/1152

**Comment by muety** [comment]
Very interesting concept! I'll add support for this type of authentication to Wakapi. But I will refrain from automated user creation, if you don't mind - it would require too many changes for little added value imo.

**Comment by muety** [comment]
Discussion about setting up Wakapi trusted header auth with Authentik and Apache 2 mod_auth_openidc at https://github.com/muety/wakapi/discussions/644.
