### ISSUE TITLE
Graph summary is very wrong?

### ISSUE THREAD

**Issue by Atakku** [muety/wakapi#535]
**Describe the bug**
It seems that the graph comparison for week/month/etc is very bugged and only shows a small fraction of the real time

When clicked on project, it shows the real time
![image](https://github.com/muety/wakapi/assets/57140941/fa3e6ecf-b18a-47a8-bf11-619ef6eb2002)

But while out in the main dashboard it shows completely different time
![image](https://github.com/muety/wakapi/assets/57140941/d0e58d42-64eb-4604-a084-d200f4d99cda)

**System information**
Please provide information on:
* Wakapi version 2.9.1
* Operating system
    * If Docker: which image and tag?
    ghcr.io/muety/wakapi:latest
* Database (SQLite, MySQL, ... ?)
PostgreSQL

**Comment by muety** [comment]
Can you try to go to _Settings -> Danger Zone_, do _Regenerate summaries_ and see if the problem persists?

**Comment by muety** [comment]
Any updates on this?

**Comment by Atakku** [comment]
Sorry for the late reply, I actually did regenerate summaries, and that screenshot was after the fact

**Comment by Atakku** [comment]
Although the issue does seem to be gone now

**Comment by muety** [comment]
Very strange! From your feeling, which of the two above numbers is more realistic? 

I'll close this issue for now, as there's not much we can do at this point. But if you observe something similar again, please come back and report it here. Also, preferably try to do some preliminary investigation to see if these discrepancies only occur for certain projects, certain time intervals. etc.

**Comment by Atakku** [comment]
it seems that the issue is back hmmmm
![image](https://github.com/muety/wakapi/assets/57140941/9310f29a-7bdd-4d98-8ec3-ca9e23173e65)
![image](https://github.com/muety/wakapi/assets/57140941/b03e3b6a-bee3-45e4-bb28-00d60d704015)

**Comment by muety** [comment]
Super weird! Would you mind sending me a dump of your database? Only if you don't think it contains any sensitive data! I know that's a lot to ask for, but would help me with debugging a lot.

**Comment by muety** [comment]
Never mind, I found and fixed the bug! Turned out the project-specific summary was too high on average due to an error in the calculation logic. Will push out a new release soon. Thanks for reporting this!
