### ISSUE TITLE
Per project public stats

### ISSUE THREAD

**Issue by GioPan04** [muety/wakapi#540]
Right now you can share all project stats by enabling the permission in the settings.

For privacy purposes, it would be better if you could enable stats sharing per project, like WakaTime's badges.

**Comment by GioPan04** [comment]
The only temp fix I found is to create a label per project and then enable label's permission. But it's not the best and intuitive solution...

**Comment by muety** [comment]
Hi @GioPan04, thanks for this feature request! I see how more fine-grained control over sharing permissions would be helpful to users. However, Wakapi continuously struggles with the trade-off between feature richness and complexity. One of my primary goals with the project is to keep things as simple as possible, so I'm always trying to balance between the potential added value of a change vs. it's complexity on code level. In this (rather niche) case, where there exists a workaround - even though it's not super convenient to the user - I'd probably argue in favor of less additional logic in the code. Sorry!
