### ISSUE TITLE
Disallow spaces in usernames

### ISSUE THREAD

**Issue by jsbrain** [muety/wakapi#541]
**Describe the bug**
In case the username has a space (e.g. 'Bob Jones'), a request to `/compat/wakatime/v1/users/{user}/stats/{range}` won't work. Other api endpoints do work, not sure if the bug only exists on this route or on others as well.

<img width="487" alt="Screenshot 2023-10-24 at 15 38 42" src="https://github.com/muety/wakapi/assets/20225909/695de854-2d93-47a4-b222-2a942a7a0119">

**System information**
Please provide information on:
* Wakapi version: 2.9.2
* Operating system
    * Docker: newest
* Database: postgres

**Comment by jsbrain** [comment]
Ok I actually changed the username in the db to remove the space. Still the same error, even for 'today' date range. So I guess the bug is caused by something else ...

**Comment by muety** [comment]
Thanks for reporting this! I think spaces in usernames are generally a bad idea, I'll probably disallow to have them. 

Your error message, however, seems to relate to a permissions issue. Make sure your "Settings -> Permissions" settings allow to request the respective `{range}`.

**Comment by jsbrain** [comment]
Yeah I literally just realized that, after checking the differences between users in the database. Probably missed that setting after some update.

Classic operator error, sorry for the confusion :D

**Comment by muety** [comment]
Wait, how were you able to create a user with a name containing a white space? There is a [check](https://github.com/muety/wakapi/blob/329e16e419d48fb233dd71b24bd1096321bb8ae1/models/user.go#L191) in place (since Feb '23) to prevent this :thinking:.

**Comment by jsbrain** [comment]
@muety I'm running wakapi since the very early days 😀 

Amazing project, thanks a ton!
