### ISSUE TITLE
Request: Map files to a project

### ISSUE THREAD

**Issue by fusion44** [muety/wakapi#543]
Can I map single files to a project? I can map (alias) projects to a project but haven't found an option to do that for files. I have several files that belong to an actual project, but count toward "unknown" project. I forgot to setup the `.wakatime-project` file for these projects when starting out.

Thank you!

**Comment by muety** [comment]
Hi @fusion44, unfortunately, this is neither currently supported, nor planned in the future. With a self-hosted instance, you could accomplish this with a quick database query. Or, if you're using Wakapi.dev, I can offer to perform this one-time replacements for you, if you send me an e-mail with the according information.

**Comment by fusion44** [comment]
I'm using a self hosted instance. I'll look into it. Thank you!

**Comment by muety** [comment]
It will probably be something like:
```sql
update heartbeats set project = 'foo' where entity like ''%/foo%.js and user = 'your-user';
```

Followed by a _Regenerate summaries_ process triggered on the _Settings_ page.

**Comment by gingerbeardman** [comment]
@fusion44 did you have any success with this approach?

**Comment by fusion44** [comment]
@gingerbeardman Sorry, I've never tried it. Ultimately the amount of time affected didn't matter in the grand scheme of things.
