### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by seigieu** [muety/wakapi#544]
I ran import form Wakatime. One user imported OK. Second user had problem.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe85533]

goroutine 1512322 [running]:
github.com/muety/wakapi/services/imports.(*WakatimeDumpImporter).Import(0xc0004f2f20, 0xc0013665a0, {0xc00115bd60?, 0xe85251?, 0x0?}, {0xc000c191a0?, 0x1171e72?, 0x237c1c0?})
	/src/services/imports/wakatime_dump.go:44 +0x253
github.com/muety/wakapi/services/imports.(*WakatimeDumpImporter).ImportAll(0xc0011c9470?, 0x29?)
	/src/services/imports/wakatime_dump.go:152 +0x45
github.com/muety/wakapi/services/imports.(*WakatimeImporter).ImportAll(0xc00115bf48, 0xc0013665a0)
	/src/services/imports/wakatime.go:27 +0xb5
github.com/muety/wakapi/routes.(*SettingsHandler).actionImportWakatime.func1(0xc0013665a0)
	/src/routes/settings.go:532 +0x185
created by github.com/muety/wakapi/routes.(*SettingsHandler).actionImportWakatime
	/src/routes/settings.go:521 +0x42d
```

A clear and concise description of what the bug is. Please briefly describe how to reproduce the bug as well as _expected_ vs. _actual_ behavior. Optionally include screenshots and server logs, if helpful.

**System information**
Please provide information on:
* Wakapi version: 2.9.2
* Operating system
    * If Docker: ghcr.io/muety/wakapi:latest
* Database: SQLite

Found similar issue at #428 but that one seems to be fixed last year

**Comment by muety** [comment]
Hi @seigieu, thanks for reporting this! I fixed the nil pointer error. However, that error occurred only as a consequence to even another error (something related to the HTTP connection to WakaTime), so it will probably not actually fix your import, unless it was only some temporary problem with the WakaTime API or so.

The change will be included in the next release. If you want to use it right away, you'll have to build your own binary or Docker image from source, unfortunately, sorry.
