### ISSUE TITLE
Summary API response different from WakaTime

### ISSUE THREAD

**Issue by GioPan04** [muety/wakapi#545]
**Describe the bug**
In the `/api/compat/wakatime/v1/users/current/summaries` api endpoint there is a typo: `cumulative_total` (from wakatime) is `cummulative_total` (in wakapi).

Example output:
### wakapi
```json
{
"data":[...],
"end":"2023-10-08T23:59:58.999999999+02:00",
"start":"2023-10-01T00:00:00+02:00",
"cummulative_total":{"decimal":"4.05","digital":"4:3","seconds":14590,"text":"4 hrs 3 mins"}
}
```

### wakatime
```json
{
  "cumulative_total": {
    "decimal": "3.25",
    "digital": "3:15",
    "seconds": 11738.112193,
    "text": "3 hrs 15 mins"
  },
  "daily_average": {
    "days_including_holidays": 8,
    "days_minus_holidays": 2,
    "holidays": 6,
    "seconds": 5869,
    "seconds_including_other_language": 5869,
    "text": "1 hr 37 mins",
    "text_including_other_language": "1 hr 37 mins"
  },
  "data": [...],
  "end": "2023-11-08T22:59:59Z",
  "start": "2023-10-31T23:00:00Z"
}
```

**System information**
Please provide information on:
* Wakapi version: v2.9.2 
* Operating system: not relevant
* Database: not relevant

**Comment by GioPan04** [comment]
I don't know if I shout put it here but in the summary API the `daily_average` object is not implemented.

**Comment by muety** [comment]
Very good spot! Will fix this as soon as possible.

Regarding the `daily_average`: yes, Wakapi is currently far from 100 % API compatibility with WakaTime. So far, we only implemented what we thought was useful, what users requested or what was anyways trivial to implement. If you need `daily_average` section, I'm happy to add it! I'm only wondering what the `seconds_including_other_language` is about and how it differs from `seconds`? :thinking:

**Comment by GioPan04** [comment]
Reading from [WakaTime API docs](https://wakatime.com/developers#summaries) it seems like that `seconds` doesn't include unrecognized languages but `seconds_including_other_language` does.

**Comment by GioPan04** [comment]
Just tried, works like a charm!
Thank you!
