### ISSUE TITLE
Implement `best_day` property for stats compat endpoint

### ISSUE THREAD

**Issue by muety** [muety/wakapi#548]
See https://wakatime.com/developers/#stats. 

Requested by @GioPan04 in #546.

**Comment by muety** [comment]
I looked into this. Our currently data model does not trivially support to get the best day for a given summary, because at summary-level date information about individual heartbeats had already been aggregated. We could adapt the summary computation logic to determine the best day on the go. But then we'd also have to account for pre-computed, cached summaries retroactively. Tbh. I don't think having this additional property in the stats endpoint is worth the effort, sorry. @GioPan04 Fyi.

**Comment by GioPan04** [comment]
Okay, I see the issue. Thank you for the update anyway.
