### ISSUE TITLE
Disable Import

### ISSUE THREAD

**Issue by cfouche3005** [muety/wakapi#552]
Does setting WAKAPI_IMPORT_BATCH_SIZE to 0 disable the import from wakatime (or another wakapi instances), or is it possible to disable import while retaining the the forward to wakatime or other wakapi instances

**Comment by muety** [comment]
Hi @cfouche3005, I checked the code and no, `WAKAPI_IMPORT_BATCH_SIZE=0` will not disable the import. But I'll change it in a way that it will, because seems sensible to me. Will be pushed later today.
