### ISSUE TITLE
/api/compat/wakatime/v1/users/INVALID/all_time_since_today results in 401?

### ISSUE THREAD

**Issue by Subtixx** [muety/wakapi#555]
**Describe the bug**
The API endpoint `/api/compat/wakatime/v1/users/INVALID/all_time_since_today` returns a 401 when the user `INVALID` not exists. However it should return 404 in my opinion

**System information**
Please provide information on:
* Wakapi version:
  * v2.9.1 @ postgres
* Operating system
  * Docker: ghcr.io/muety/wakapi:latest
* Database: Postgres

**Comment by muety** [comment]
I don't know how WakaTime behaves in this case, but this is actually intended. It's a security best practice to possibly not reveal much information about what users are existing in the system, so an attacker can't just randomly iterate user names. Consequently, an unauthorized request and a request for a non-existing users should look the same from the outside. That said, I'm quite certain that we probably don't always strictly follow that rule in all places of Wakapi.

**Comment by Subtixx** [comment]
Sounds reasonably, thanks for the explanation!
