### ISSUE TITLE
Retrieve single project in compat API

### ISSUE THREAD

**Issue by GioPan04** [muety/wakapi#562]
Currently there isn't a valid way to retrieve a single project with the projects api. The only way is to use `/api/compat/wakatime/v1/users/current/projects?q=<project name/id>` and taking the first result.

If I have two projects "test" and "test1" and I call `/api/compat/wakatime/v1/users/current/projects?q=test` there is a possibility that project  "test1" will be first and "test" second. WakaTime has a dedicated endpoint: `api/v1/users/current/projects/<project name/id>` (for some reason is not documented in their docs).

**Comment by muety** [comment]
Let's add it!

**Comment by muety** [comment]
New version about to be released still this weekend.
