### ISSUE TITLE
Rank missing in `/api/metrics`

### ISSUE THREAD

**Issue by BreizhHardware** [muety/wakapi#566]
Hi, I wank to connect my wakapi using wakatime exporter but when I read the data in my grafana everything is display properly except for the rank, it seems that the wakatime_rank is not in the /api/metrics anymore. I wanted to know if this was intentional or not.
![image](https://github.com/muety/wakapi/assets/72651575/2ce03654-af5e-40b8-8e7b-8c6ccc11fb9a)
![image](https://github.com/muety/wakapi/assets/72651575/0fb39281-a8ca-4719-b0db-01a4c056b364)

**Comment by muety** [comment]
Hi @BreizhHardware, we only implemented ranks very recently (#182) and didn't include them in the metrics, yet. I can add this as a feature request, if you're interested (with low prio, though).

**Comment by BreizhHardware** [comment]
This could be very nice if you implement this

**Comment by muety** [comment]
Requires #554 (see [`leader.go`](https://github.com/MacroPower/wakatime_exporter/blob/master/collector/leader.go)).
