### ISSUE TITLE
Better config reading errors

### ISSUE THREAD

**Issue by shyim** [muety/wakapi#567]
**Describe the bug**

For some reason, my container is not starting. I have no idea what is wrong.

```
2023-11-28T08:38:19.367090791Z [ERROR] failed to read config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tcp://1...` into int
panic: failed to read config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tcp://1...` into int

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x4000040080?, {0xca34fc?, 0xca34fc?}, {0x40004f7890?, 0x40004f7890?, 0x1?})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:59 +0x6c
github.com/emvi/logbuch.(*Logger).Fatal(0x4000040080, {0xca34fc, 0x19}, {0x40004f7890, 0x1, 0x1})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x74
github.com/emvi/logbuch.Fatal(...)
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/config.Load({0xc8e47e, 0xa}, {0xc8862e, 0x6})
        /src/config/config.go:405 +0x134
main.main()
        /src/main.go:119 +0x154

```

I would like if the errors is much more verbose.

**Comment by muety** [comment]
This is the `panic` that is logged from the YAML parser, there's no way to change that.

**Comment by bboysoulcn** [comment]
"I'm encountering the same error as you, and I'm not sure where the problem lies."

**Comment by shyim** [comment]
Do you use Kubernetes? For me was the problem that my service name was `wakapi` and kubernetes produces so environment variables like `WAKAPI_PORT` and this conflicts

**Comment by muety** [comment]
The error message sounds like you're passing a connection string (e.g. `tcp://127.0.0.1:1234`) to a config variable that is supposed to be a string. The error message doesn't say which variable, but could well be `WAKAPI_PORT`, for example.

**Comment by bboysoulcn** [comment]
> Do you use Kubernetes? For me was the problem that my service name was `wakapi` and kubernetes produces so environment variables like `WAKAPI_PORT` and this conflicts

Yes, thank you. The situation was as you described, and it has now been resolved.

**Comment by bboysoulcn** [comment]
> The error message sounds like you're passing a connection string (e.g. `tcp://127.0.0.1:1234`) to a config variable that is supposed to be an integer. The error message doesn't say which variable, but could well be `WAKAPI_PORT`, for example.

Great project, thank you.
