### ISSUE TITLE
Configurable leaderboard time scope

### ISSUE THREAD

**Issue by BreizhHardware** [muety/wakapi#568]
Hi I wanted to know if it is possible to add a settings in wakapi as admin to set the leaderboard delay, I mean having a leaderboard over 1 year or somthing like that.
Thank by advance

![image](https://github.com/muety/wakapi/assets/72651575/86724125-304d-4c3d-9f56-26ecf7633231)

**Comment by muety** [comment]
Hi @BreizhHardware, no, that's currently not supported. But I'll add it as a low-prio feature request.

**Comment by BreizhHardware** [comment]
Thanks a lot for your reactivity =)

**Comment by muety** [comment]
Check the README on how to configure leaderboard interval. New version about to be released still this weekend.
