### ISSUE TITLE
Recognize Neovim editor as Vim

### ISSUE THREAD

**Issue by baddate** [muety/wakapi#578]
**Describe the bug**
I use Neovim to edit md files, but the editor diagram displayed on the web page is Vim.

here is the log line:
```
{"caller":"pkg/api/heartbeat.go:52","file":"/home/xxx/test.md","func":"api.(*Client)","is_write":true,"level":"debug","message":"heartbeats: [{\"branch\":\"theme/vite\",\"category\":\"coding\",\"entity\":\"/home/xxx/test.md\",\"type\":\"file\",\"is_write\":true,\"language\":\"Markdown\",\"lines\":517,\"project\":\"myblog\",\"project_root_count\":5,\"time\":1702688519,\"user_agent\":\"wakatime/v1.86.5 (linux-6.6.6-arch1-1-unknown) go1.21.3 neovim/801 vim-wakatime/11.1.1\"}]","now":"2023-12-16T09:02:45+08:00","os/arch":"linux/amd64","plugin":"neovim/801 vim-wakatime/11.1.1","time":1702688519,"version":"v1.86.5"}

```
screenshot:
![image](https://github.com/muety/wakapi/assets/37013819/9c306759-09de-4c6d-bd77-064a5588f252)

**System information**
Please provide information on:
* Wakapi version: 2.10.0
* Operating system: ArchLinux
* Database: PGSQL
* Editor: Neovim

**Comment by muety** [comment]
Fixed this. However, seems like in some cases (like my own), the neovim plugin will still intentionally set `vim` as an editor, see [here](https://github.com/wakatime/vim-wakatime/blob/master/plugin/wakatime.vim#L553-L556). Are you using WakaTime as well and if yes, which editor is shown there?

**Comment by baddate** [comment]
No, I use Wakapi's data forward feature to do that, which is very convenient:) And I sought a new [issue](https://github.com/wakatime/vim-wakatime/issues/175) from vim-wakatime today, maybe it's a bug with the vim-wakatime plugin?
