### ISSUE TITLE
the data is not completely synced

### ISSUE THREAD

**Issue by lookwake** [muety/wakapi#587]
**Describe the bug**
importing data from wakatime.com by integrations feature, it lost some data.

imported: 430hrs 25mins
![image](https://github.com/muety/wakapi/assets/155813928/02da64bf-e57d-4125-879a-418803c25ada)

origin: 580hrs 20mins
![image](https://github.com/muety/wakapi/assets/155813928/b982e319-92d3-440d-b360-33149fcf4482)

**System information**
Please provide information on:
* Wakapi version `2.10.2`
* Operating system
    Docker: image with `latest` tag
* Database MariaDB

**Comment by muety** [comment]
The different arises from the fact that Wakapi estimates total coding differently from WakaTime, i.e. has a different heuristic for interpolating between heartbeats. This had been discussed a couple of time before, e.g. see https://github.com/muety/wakapi/issues/488#issuecomment-1554165730, https://github.com/muety/wakapi/issues/334#issuecomment-1062014189 and the _How are durations calculated?_ part of our [FAQs](https://github.com/muety/wakapi#-faqs). There's no way to accurately report coding time and the "truth" will probably be somewhere between Wakapi's and WakaTime's estimates.
