### ISSUE TITLE
[languages chart] show other languages merged as “other”

### ISSUE THREAD

**Issue by tippfehlr** [muety/wakapi#588]
Right now, unless the number of languages displayed is set to the max, the percentage of languages is wrong.

**This would suggest I only coded in Typescript:**
![image](https://github.com/muety/wakapi/assets/46620049/bb7b366d-7ee6-4070-8416-38908709a7ee)

**But in reality, Typescript is less than half of my time coding.**
![image](https://github.com/muety/wakapi/assets/46620049/e4f08946-e7ee-4da2-b057-fd32f80322fc)

**Proposed change:**
merge other languages into “other”
![Screenshot_20240106_125349](https://github.com/muety/wakapi/assets/46620049/b5c228f9-5fbe-4c51-b3ff-ebf3bfbcb67d)

**Comment by muety** [comment]
Hi @tippfehlr, thanks for bringing this up. But, frankly, I don't see much of a benefit in the solution you proposed. The way I interpret this is: when decrementing the number of languages shown (e.g. to 5), you're saying "give me my top 5 languages" and among those top five, every language has its respective percentage, regardless of the overall, global coding time. If yet opt to only show one language, you're requesting your "top 1 languages", and among those, TypeScript has a share of 100 %.

**Comment by tippfehlr** [comment]
Sure, but I don't get the reason to show the percentage of the top language in relation to only the top two languages.

Maybe a switch next to the languages number that toggles this on or off? (eg. relative to total)

**Comment by tippfehlr** [comment]
I would like to implement this and learn go a bit on the way, and I guess this wouldn't be too hard. What do you think?

**Comment by muety** [comment]
> Sure, but I don't get the reason to show the percentage of the top language in relation to only the top two languages.

Fair point, but I don't get the reason for showing some languages in comparison to "other" vs. showing them in comparison to the actual languages. The only "benefit" would be the pie chart looking less "busy", or am I missing something here?

**Comment by tippfehlr** [comment]
> The only "benefit" would be the pie chart looking less "busy"

This, and especially the text to the right.

I think having the option to keep them in one column (but still relative to all) might be good.

**Comment by muety** [comment]
Definitely agree that there should be a hint indicating that there are more languages to show, perhaps alongside a (very small and subtle) _show all_ button or icon. But would like to keep the "filtering" mechanism as is.

**Comment by tippfehlr** [comment]
Thanks <3
