### ISSUE TITLE
When using Trust header authentication, the homepage shows Not logged in

### ISSUE THREAD

**Issue by IvanLi-CN** [muety/wakapi#589]
**Describe the bug**

When I pass the Remote-User header correctly, the user is displayed correctly when accessing the summary page (wakapi.example.com/summary). 

<img width="1380" alt="image" src="https://github.com/muety/wakapi/assets/30215105/b193cb31-4541-42a0-a23d-b1da6a85df43">

When accessing the home page (wakapi.example.com), the status of not logged in is displayed. 

<img width="1095" alt="image" src="https://github.com/muety/wakapi/assets/30215105/0ec56570-63a2-49d4-a6bc-911d113a06bb">

I think we should be able to display it as logged in on the homepage, otherwise someone will spend two hours like me thinking about why it doesn't work. 😭 

**System information**
Please provide information on:
* Wakapi version `2.10.2`
* Operating system ghcr.io/muety/wakapi:latest for 2024-01-06
* Database SQLite

**Comment by muety** [comment]
Will fix this!
