### ISSUE TITLE
Error when requesting using api key

### ISSUE THREAD

**Issue by heitoke** [muety/wakapi#595]
curl -X 'GET' \
  'https://wakapi.dev/api/compat/wakatime/v1/users/current' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <Token>'
  
  Token: 0d4c5f9c-0000-0000-0000-....
  
  When I make a request to the API, it writes to me that there is a 401 error, but I do not understand why...

**Comment by muety** [comment]
Are you passing your token in base64 encoding after the `Basic ` prefix as part of the `Authorization` header?

**Comment by heitoke** [comment]
I'm sorry, I'm just a fool and didn't read what needs to be encoded... I'm sorry again...
