### ISSUE TITLE
404 on activity chart

### ISSUE THREAD

**Issue by hesstobi** [muety/wakapi#596]
**Describe the bug**
Under activity, there should be  chart showing my activity over the last year. Actual is see only "404 page not found". Opening the provided link also returns a 404 Error.

![image](https://github.com/muety/wakapi/assets/929957/3b002cf7-2709-464b-b887-de0468635f08)

**System information**
Please provide information on:
* Wakapi version: on https://wakapi.dev  v.2.10.3

P.S. Thank you for the great project.

**Comment by muety** [comment]
Very strange. Are the other charts displaying fine? And do you see your username and avatar in the top right corner? Also, can you please share the full link to the activity chart?

**Comment by hesstobi** [comment]
Yes the other charts are displaying fine. Also I see the username and the avatar.

The full link is https://wakapi.dev/api/activity/chart/tobias.hess.svg

**Comment by muety** [comment]
Interesting, this looks like a routing issue to be, probably caused by the fact that your username contains a dot (`.`). Will investigate deeper and fix this. Thanks for reporting.

**Comment by hesstobi** [comment]
This is still not working in version 2.10.4

![image](https://github.com/muety/wakapi/assets/929957/bf07b9d3-3a87-49b0-b3af-ae558fbbce91)

When I test the URL of the svg, I get a 404 error.

**Comment by muety** [comment]
I could have sworn it worked :thinking: Also see #599. Will look into this again, sorry!

**Comment by muety** [comment]
Looks like you deleted your user account on wakapi.dev on `2024-01-26T16:50`? You shouldn't even be able to log in anymore? Can you please contact me via e-mail to debug this together offline?

**Comment by muety** [comment]
Fixed (again)! Sorry for that.

**Comment by muety** [comment]
I see. For self-hosted the fix will be available with the next release. Funny fact: all users whose username either contained a dot or ended with the letters "s", "v" or "g" were affected.
