### ISSUE TITLE
Activity chart loading indefinitely

### ISSUE THREAD

**Issue by bestlinuxgamers** [muety/wakapi#599]
The activity chart is not displayed. Instead, only the text "Loading activity chart ..." appears.

**System information**
* Wakapi version `2.10.4`
* Operating system
    * If Linux: which distro? `Ubuntu 22.04.3 LTS`
    * If Docker: which image and tag? `ghcr.io/muety/wakapi:2.10.4`
* Database `Postgres`

![grafik](https://github.com/muety/wakapi/assets/52172848/a3cfe31f-485a-48ec-baf9-aa6c0952314b)

Console Log:
`[wakapi]   | 2024-01-30T05:20:17.720464191Z [INFO ] [request] status=404, method=GET, uri=/api/activity/chart/name.svg?dark&noattr, duration=480.402µs, bytes=0, addr=10.89.0.3:56658, user=name`

**Comment by muety** [comment]
Could you provide the full URL of the activity chart as well your username, please? That would help me debug this.

**Comment by bestlinuxgamers** [comment]
My username is `bestlinuxgamers` and the full non-generic error is:
`[INFO ] [request] status=404, method=GET, uri=/api/activity/chart/bestlinuxgamers.svg?dark&noattr, duration=458.502µs, bytes=0, addr=10.89.0.3:59678, user=bestlinuxgamers`

**Comment by muety** [comment]
Very strange, honestly I have no idea how this comes about. Can you please check if there are any errors in the browser console? Also, can you check if restarting the server or using a different browser helps? Are the summary charts displayed properly?

**Comment by bestlinuxgamers** [comment]
There is only the 404 error from trying to load the chart in the browser console. On Google Chrome (instead of Firefox) there is the same issue and the error in the browser console. I've restarted the docker container multiple times and my whole host server too. It didn't make a difference. The charts are not displayed properly (see #600).

**Comment by muety** [comment]
Found and fixed the issue. Was my bad, sorry :man_facepalming:. Fix will be available with next release.
