### ISSUE TITLE
Make aggregation schedule interval configurable

### ISSUE THREAD

**Issue by muety** [muety/wakapi#60]
https://sonarcloud.io/project/issues?id=muety_wakapi&issues=AXUOqv33u1Oc5-RXBON1&open=AXUOqv33u1Oc5-RXBON1

**Comment by Amirhossein2000** [comment]
Hi, I want to work on this.
Which field in config.default.yml?
Only day and hour?

> https://github.com/muety/wakapi/blob/master/services/aggregation.go#L61
This line?

**Comment by muety** [comment]
Very cool!

Well, obviously it would be cool to be able to specify an arbitrary expression supported by gocron. However, some parts of the current logic rely on the assumption that an aggregation is generated exactly once per day. So yes, in the first step — until aggregation logic is refactored — it's essentially just about configuring the time of day.
