### ISSUE TITLE
Unknown language don't count in the leaderboard

### ISSUE THREAD

**Issue by BreizhHardware** [muety/wakapi#606]
Hello, after a little while with wakapi I have see something that don't work as expected, it didn't count the unknown language (such as Blender in this case) in the leaderboard.
Expected comportment : count unknown language in the leaderboard

**Comment by muety** [comment]
Could you provide more information, please? What are some exemplary file names that weren't counted? Is the count correct in the projects- or editors chart or is the coding time from those files missing entirely?

**Comment by BreizhHardware** [comment]
When I work on figma or on blender (here the 7h38 of unknown language), it didn't show up in the leaderboard (image 2), if we do the maths we can see that the time missing is 7h38, so it is the unknown language time that isn't count in the leaderboard.

![image](https://github.com/muety/wakapi/assets/72651575/79cd6044-6fe1-4c36-8770-37ca9f6293b5)
![image](https://github.com/muety/wakapi/assets/72651575/9471f18c-95a4-4e78-be1b-304300e6f801)

**Comment by muety** [comment]
Sorry for my late reply and sorry for the confusion. I misread your question and didn't realize we're talking about the leaderboard, but instead thought there's some issue with the dashboard. 

For the leaderboard, stats for unknown languages are actually included on purpose, see: https://github.com/muety/wakapi/blob/9a9f645562bf6d0b3207b3b213a4bcd5911147d9/services/leaderboard.go#L238.

Main reason is to exclude "noise", especially web browsing (ok, there would be more sophisticated ways to explicitly filter out browsing data, while still keeping every other _unknown_ heartbeats, but this was easiest tbh.). I wanted the leaderboard to focus on actual coding only. However, you could probably bypass this by defining an explicit language mapping (_Settings -> Data -> Language Mapping_), e.g. put "Blender" for `.blend` files or so. 

I see how this decision to exclude all unknown data might be a bit frustrating in your case. But I'd rather want to keep the current behavior as is.

In fact, while investigating this issue, I found a bug that apparently causes unknown languages to still be shown in the language-specific leaderboard (https://wakapi.dev/leaderboard?by=language). Will fix this for consistency.
