### ISSUE TITLE
Hourly breakdown

### ISSUE THREAD

**Issue by Atlasfreak** [muety/wakapi#609]
It would be nice if you could get an hourly breakdown of a specific day. For a greater timespan a percentage graph "you often work at 3 a clock" could be used to get a time distribution when you work most often.

**Comment by muety** [comment]
Hi @Atlasfreak, thanks for this suggestion. This has already been requested as a feature several times, see #101. Will look into it as soon as I can get some time to work on Wakapi more intensely again.
