### ISSUE TITLE
Difference between today and other filters

### ISSUE THREAD

**Issue by mlunax** [muety/wakapi#61]
When I filter stats by "today" I have this day information but this same information is not in equivalent with other filters(like "this month", "all time" etc)
Api ver: v1.12.1 (by bottom of main page) 
`/summary?interval=today`
![image](https://user-images.githubusercontent.com/11018865/95667659-5d511a80-0b69-11eb-9e54-53c1081e99ea.png)
`/summary?interval=any`
![image](https://user-images.githubusercontent.com/11018865/95667668-75289e80-0b69-11eb-87ea-f8f7b1040e61.png)

**Comment by muety** [comment]
Hi, thanks for bringing this up! The aggregation logic is quite complex and I wouldn't be surprised if it contained minor bugs. However, the total time should definitely not be smaller than today's time :thinking:.

I'd like to investigate further, but I couldn't reproduce this scenario with test data. Is it possible that you provide me with a database dump or so?

**Comment by mlunax** [comment]
Okay, I will prepare database and I will send dump.
Here or some other way?

**Comment by muety** [comment]
Just send me an e-mail to ferdinand@muetsch.io. Thanks!

**Comment by muety** [comment]
Quick update: there seems to be at least two different issues right now. One is a discrepancy between the total time returned by using `&recompute=true` vs. using pre-generated summaries. The second seems to be a discrepancy between data stored in SQLite and MySQL, which is most likely related to the way timestamps are represented in the database. Fixing these critical bugs will require non-trivial investigation and refactoring. I'll keep you posted. Sorry!

**Comment by mlunax** [comment]
I want to add, before I forgot, I changed timestamp/timezone after generate the database. I use docker ver so it was easy (mount the /etc/localtime).

**Comment by muety** [comment]
Alright, I discovered and fixed several bugs. Your issue should be resolved now. However, you will have to delete all summaries from your database to let them be re-generated again. Simply run `DELETE FROM summaries WHERE 1;`.

**Comment by mlunax** [comment]
The next thing: 
`summary?interval=7_days`
![image](https://user-images.githubusercontent.com/11018865/97172780-d10d3d00-178f-11eb-99b9-4a63c6c36516.png)
`summary?interval=any` or `summary?interval=30_days` or more
![image](https://user-images.githubusercontent.com/11018865/97172846-eda97500-178f-11eb-8b04-a3ec638b24d9.png)
