### ISSUE TITLE
Add WakaTime integration to setup instructions

### ISSUE THREAD

**Issue by alanhamlett** [muety/wakapi#611]
I'm noticing people aren't aware of the WakaTime integration that sends data to both Wakapi and WakaTime simultaneously. When they find out, there's already some inconsistency between the two. Should instructions for syncing data to WakaTime be added to the setup instructions?

<img width="641" alt="Screenshot 2024-02-20 at 7 20 13 PM" src="https://github.com/muety/wakapi/assets/522344/0f817712-a9fe-4989-b737-49a54c161cdb">

**Comment by muety** [comment]
Sure, I'll add a subtle hint to let new users know that feature exists.

**Comment by Zubayer204** [comment]
@alanhamlett Would you mind sharing how can I achieve this? I was looking for this exact solution but couldn't find any. As far as I know, we can have one URL (api_url) in the wakatime.cfg file.

**Comment by muety** [comment]
You can configure Wakapi to forward all incoming heartbeats to WakaTime as well. 

![image](https://github.com/muety/wakapi/assets/8978843/18fccc22-a87c-4a2d-98cc-9e06a87adad1)

**Comment by Zubayer204** [comment]
That is an awesome feature to have, thank you!

**Comment by rohitkrishna094** [comment]
I think its better to add default wakatime api url in the input box as placeholder or perhaps on the left side. I had to spend a lot of time finding that out. It was in the docs of wakatime but I didnt know where to look immediately and then stumbled here where muety posted the screenshot.

![image](https://github.com/user-attachments/assets/105b365b-bb26-49f0-9651-15a1e8dba04d)

**Comment by muety** [comment]
> I think its better to add default wakatime api url in the input box as placeholder 

What do you mean by that?
