### ISSUE TITLE
Sync past heartbeats to WakaTime

### ISSUE THREAD

**Issue by alanhamlett** [muety/wakapi#612]
Ability to sync heartbeats to WakaTime. Currently you can only download from WakaTime, so just need to add the other direction.

Work towards this was started but not finished in #87.

**Comment by muety** [comment]
Wakapi features the option to relay / clone incoming heartbeats, but there currently is ability to also copy _past_ heartbeats. What would be the recommended way to accomplish this is an efficient manner on WakaTime's end? Is there an import-endpoint or something?

**Comment by alanhamlett** [comment]
The [POST Heartbeats](https://wakatime.com/developers/#heartbeats) endpoint is currently the only way, but it only allows heartbeats from the last 180 days.

**Comment by muety** [comment]
I see, so it's only party suitable for data imports. I'm not exactly sure how many people would use this feature. I'd assume the usual way is to export from WakaTime to Wakapi instead of vice versa.
