### ISSUE TITLE
Feature to invite users

### ISSUE THREAD

**Issue by ErlandssonA** [muety/wakapi#624]
It would be amazing to have a feature where you could invite users to signup when signups are disabled. This way you can both give a way to your friends to track their statistics and also "compete" with your friends.

You could do this by enabling signups but if you were to do that other people could also signup.

**Comment by muety** [comment]
Great idea! Will add this as a feature request.

**Comment by muety** [comment]
Easiest would be to wait for the next release (probably some time next week). Otherwise you could also build and run your own Docker image from source.

**Comment by muety** [comment]
Still found two minor issues (as usual when I push code late at night), which I want to correct later today.

**Comment by ErlandssonA** [comment]
Awesome! I will wait for the next release because I am very new to docker and don't want to mess anything up on my "production server" xD

Again, thank you very much!

**Comment by ErlandssonA** [comment]
No worries at all!

**Comment by muety** [comment]
Available now!
