### ISSUE TITLE
Clean up dead user accounts for GDPR compliance

### ISSUE THREAD

**Issue by muety** [muety/wakapi#629]
Automatically delete users who don't have any data and didn't log in within a year. Additionally (perhaps in a second step), send out deletion notices to users who _do_ have data, but didn't log in within a year and also delete them after some grace period.

**Comment by muety** [comment]
Only implemented clean up for inactive users (>= 12 months by default) who don't have data. Didn't implement deletion of users _with_ data, yet.

**Comment by kiprasmel** [comment]
hmmm idk about the auto-deletion of inactive users, does not sound good. especially for self-hosted instances. maybe could be an opt-in via ENV var or something, instead of opt-out?

**Comment by muety** [comment]
Fair point, will change this with the next release.

**Comment by muety** [comment]
Actually, I found a bug with the latest release. Please **do not** set `WAKAPI_MAX_INACTIVE_MONTHS` to `-1`. Will push a fix in a second.

**Comment by kiprasmel** [comment]
@muety any reason why you've made this opt-out instead of opt-in? again, since many people will want to self-host, this is an easy thing to miss and could end up being really annoying..
thanks

**Comment by muety** [comment]
It's opt-out (default value is -1), only forgot to update README.

**Comment by kiprasmel** [comment]
sweet, thanks
