### ISSUE TITLE
Difference between today and other filters

### ISSUE THREAD

**Issue by mlunax** [muety/wakapi#63]
The next thing: 
`summary?interval=7_days`
![image](https://user-images.githubusercontent.com/11018865/97172780-d10d3d00-178f-11eb-99b9-4a63c6c36516.png)
`summary?interval=any` or `summary?interval=30_days` or more
![image](https://user-images.githubusercontent.com/11018865/97172846-eda97500-178f-11eb-8b04-a3ec638b24d9.png)

_Originally posted by @mlunax in https://github.com/muety/wakapi/issues/61#issuecomment-716517493_

**Comment by mlunax** [comment]
After again re-drop it has regenerate correctly.
And question: is this order a bug or a feature?
![image](https://user-images.githubusercontent.com/11018865/97234439-17d75300-17e1-11eb-8532-0a7094d2b538.png)

**Comment by muety** [comment]
I'll investigate. Hopefully I can reproduce the problem. Do you still have a dump from before you regenerated the statistics?

And what do you mean with bug or feature? In the screenshot snippet everything looks alright.

**Comment by mlunax** [comment]
I think you change the order.
I have and I can send to you at the email.

**Comment by muety** [comment]
Unfortunately, I can't reproduce the problem with the database dump you sent me. For `interval=7_days` I'm getting 8:xx hours and for `interval=any` it's 19:xx hours.

What version are you using?

**Comment by mlunax** [comment]
v1.12.5
After dump the summaries it works good.

**Comment by muety** [comment]
Please observe if the problem occurs again over time.
