### ISSUE TITLE
Category breakdown

### ISSUE THREAD

**Issue by edersilva78** [muety/wakapi#630]
It would be great to have some insights about the categories (coding, building, browsing, debugging) 
Breakdown present on the dashboard, such as the Languages, Editors
And maybe as an stacked chart (or overlay) on projects, branchs.

Congrats, loving Wakapi

**Comment by muety** [comment]
Thanks! Adding this as a feature request.

**Comment by muety** [comment]
I envision something like this.

![wakapi_categories](https://github.com/muety/wakapi/assets/8978843/2f6a83ad-ee4a-4017-b65a-36ce68dd6fad)

Currently, we have these categories on wakapi.dev (sorted by number of heartbeats):

| category | count |
| :--- | :--- |
| coding | 31430873 |
| debugging | 1178351 |
| building | 448608 |
| browsing | 269062 |
| learning | 8051 |
| writing docs | 7455 |
| Designing | 4090 |
| Manual Testing | 3013 |
| running tests | 2309 |
| meeting | 433 |
| code reviewing | 430 |
| Writing Tests | 427 |
| Planning | 117 |
| researching | 1 |

**Comment by edersilva78** [comment]
Amazing. Maybe have this breakdown for an individual project/branch.

**Comment by muety** [comment]
Sorry, it's been super busy lately. Didn't forget about this, though!
