### ISSUE TITLE
new accounts

### ISSUE THREAD

**Issue by JuanPabloDiaz** [muety/wakapi#631]
**Are you is currently allowing new user registrations?**

- in the login page, the sign-up button is grayed out
- in the signup page, the create account button is greyed out

**Comment by muety** [comment]
As stated on the front page, user registrations are currently disabled on wakapi.dev. If you want, I can send you an invite code (a feature that was implemented literally yesterday, #624) in the meantime, though.

**Comment by JuanPabloDiaz** [comment]
Could you please send me an invitation.

Thank you @muety
