### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by muety** [muety/wakapi#632]
Any ideas, why the build is failing, @YC? It works perfectly fine locally. :thinking: 

https://github.com/muety/wakapi/actions/runs/8493215002/job/23267048840

**Comment by muety** [comment]
Looks like it's the `linux/arm/v7` build that is failing.

**Comment by muety** [comment]
Probably related to https://github.com/duke-git/lancet/issues/207. I think we can temporarily skip `armv7` releases until this is fixed, since most people are probably running Wakapi on `amd64` and `arm64`.

What do you think would be the cleanest way to provide Docker images for those platforms for `2.11.0` without having to push a new tag?

**Comment by YC** [comment]
For traceability, I think the best method is to hard code the tag in the pipeline definition and manually trigger it. 
This will require a merge to `main`, followed by a revert after the publish. 

I'm currently testing in:
https://github.com/YC/wakapi/actions/runs/8493918515/job/23268493429
