### ISSUE TITLE
/leaderboard and /projects broken for logged in users after update

### ISSUE THREAD

**Issue by edersilva78** [muety/wakapi#634]
**Issues**

Self-hosted, docker. I just updated to the latest docker image.

/leaderboard and /projects pages are empty for logged in users. 
They work normally for public users accessing the site.

![image](https://github.com/muety/wakapi/assets/7780778/cd7fd948-4859-4ffc-8f3e-c37f0cb40aa7)

The "user" button is also missing the "Logout" link.
And clicking on "show api" does not work. Probably due to alignment?
![image](https://github.com/muety/wakapi/assets/7780778/e79ffa2c-a369-4aea-8b35-aa74044066a5)

**System information**
* Wakapi version: just updated to v2.11.0 @ sqlite3
* Operating system
    * If Docker: ghcr.io/muety/wakapi:latest
* Database: SQLite

**Comment by muety** [comment]
Thanks for spotting this! Looks like parts of the template are not being rendered et properly. Tests didn't find this, because responses are `200`. Will fix this soon and add some content checks to the tests as well. Sorry for the inconveniences.

**Comment by edersilva78** [comment]
No problem, @muety 
I'm happy to help. And thank you for you commitment.

**Comment by muety** [comment]
New release coming after latest version has been running successfully on wakapi.dev for a bit.
