### ISSUE TITLE
Postgres port of `aggregate_durations.sql`

### ISSUE THREAD

**Issue by cwilby** [muety/wakapi#639]
While reading the code to understand how durations worked, I noticed in https://github.com/muety/wakapi/blob/master/services/duration.go#L32-L34 that the `aggregate_durations.sql` script couldn't be used due to MySQL-specific functions.

I built a Metabase dashboard which required a SQL-only solution, so I thought I'd offer a translation that worked for me in PostgreSQL in case @muety finds it useful.

```sql
SELECT project, language, editor, operating_system, machine, branch, SUM(GREATEST(1, diff)) as 'sum'
FROM (
       SELECT project, language, editor, operating_system, machine, branch, EXTRACT(EPOCH FROM LEAST(time - LAG(time) OVER w, INTERVAL '2 minutes')) as diff
       FROM heartbeats
       WHERE user_id = 'n1try'
       WINDOW w AS (ORDER BY time)
) s2
WHERE diff IS NOT NULL
GROUP BY project, language, editor, operating_system, machine, branch;
```

**Comment by muety** [comment]
Wow, thanks a lot! Added the script to the codebase. Also, if you want to share your journey of visualizing Wakapi data in Metabase, feel free to submit a blog post, code repo, etc. if you want :nerd_face:.

**Comment by cwilby** [comment]
I may do that!  Until then - the idea was to see how many minutes I worked on average in any given hour, and compare it to today.

Mostly out of interest (but also for sport ¯\\_(ツ)_/¯) - to see when/how often I'm writing software within a roughly 8 hour workday. 

<img width="1020" alt="image" src="https://github.com/muety/wakapi/assets/13686317/35631f47-8370-49b4-8875-cd2ffc1d3938">
