### ISSUE TITLE
Updating docker image tags

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#64]
Hi again, it would be great if you could look into building the [docker-hub image](https://hub.docker.com/r/n1try/wakapi/tags) automatically to keep the `latest` tag up to date with the `master` branch.

I think it is possible to do so via docker-hub's repository settings. Otherwise, it would be pretty trivial (for me at least) to set up a pipeline that build and push the image to the `latest` tag when there is something new on the `master` branch. If you want to go farther in the subject, it's also possible to trigger pipeline jobs based on changes in a specific file or even tagged commits. This could help with building and pushing different tags that matches wakapi's current version on docker-hub.

**Comment by muety** [comment]
Hi @notarock, thanks for the feedback! Right now, the setup is as follows:

I commit every new feature or bug fix directly to `master`. As a consequence, `master` can not be considered a stable branch. This may seem a bit counterintuitive, but as I'm mostly the only developer, this workflow is way easier for me than working with actual feature branches. After a change was committed, I test it for a few days on my own instance. Once I am confident, that it's mostly free of bugs, I do the following steps:
1. Create a Git tag
2. Create a release on GitHub from it
3. Merge master into `stable`

DockerHub is configured to always automatically build the `stable` branch. This way, people relying on the Docker image can be more or less sure, that their version is stable, compared to master, which, in this case, is more experimental. 

Besides from using feature branches – which I don't want to for now – an alternative would be to replace the state of `master` by a `dev` branch and replace `stable` by `master` in turn. This way, `master` continually holds a functioning version and DockerHub could build from `master`. But actually I am quite happy with the current solution. The only thing that we could indeed change is configure DockerHub to automatically build from tags, so we can eliminate the additional step of having a `stable` branch. 

What do you think? Are you ok with this, as now you know that a new image is built for every version that I consider "good"?

**Comment by notarock** [comment]
I had no idea about the `stable` branch: eyes:. Having a `stable` and a `master` branch is fine, there's no reasons to change that workflow IMO, but maybe it would be great to have a second tag on dockerhub that explicitly builds from `master`? I could use it on my own instance and report back anything I find, maybe even help with fixing bugs and such. LMK what you think, I'm closing this issue because my main concern has been addressed for now. Thanks for the detailed answer BTW
