### ISSUE TITLE
Use relative file paths for individual file coding time

### ISSUE THREAD

**Issue by JohnnyJTH** [muety/wakapi#643]
In the screenshots below, the same file is registered twice, which makes sense, but I wonder if it is possible to deduplicate. 
![image](https://github.com/muety/wakapi/assets/64006750/d1f6d0a9-415c-4484-9323-a2a3637271ac)
![image](https://github.com/muety/wakapi/assets/64006750/5c071688-8f92-4a8b-9259-82a66db40d7f)
It's basically just me coding in the same project on different machines, with different file system structures.

**Comment by muety** [comment]
Hi @JohnnyJTH, under _Settings -> Data_ you can specify "Aliases", where you could map the entity `C:/dev/folder1/file1.txt` to `C:/dev/folder2/file1.txt`. However, you'd have to do this for every individual file, which is probably impractical. We have a feature planned, where these aliases can also be regexes or at least wildcard-like patterns (see #607), but I can't give you an ETA for that feature, yet.

**Comment by JohnnyJTH** [comment]
> Hi @JohnnyJTH, under _Settings -> Data_ you can specify "Aliases", where you could map the entity `C:/dev/folder1/file1.txt` to `C:/dev/folder2/file1.txt`. However, you'd have to do this for every individual file, which is probably impractical. We have a feature planned, where these aliases can also be regexes or at least wildcard-like patterns (see #607), but I can't give you an ETA for that feature, yet.

All right, that will definitely satisfy my needs.
Just wondering why the program doesn't try to find the project root, at least if that part is the same on both machines.

**Comment by muety** [comment]
Well, how could it tell what the "project root" is?
