### ISSUE TITLE
Java is detected as two different languages

### ISSUE THREAD

**Issue by filiptrplan** [muety/wakapi#647]
**Describe the bug**
Java is detected as two different languages. One is "JAVA" and the other one is "Java".

**System information**
Please provide information on:
* Wakapi version: v2.11.1
* Operating system: ghcr.io/muety/wakapi:latest
* Database (SQLite, MySQL, ... ?): sqlite
* IDE: IntelliJ IDEA

![image](https://github.com/muety/wakapi/assets/8643457/e92940ec-61c7-4961-be0f-4a1a6424ecb2)

**Comment by muety** [comment]
"Java" vs. "JAVA" depends on the IDE / editor you're using. This was asked several times before (e.g. in #373). Please use aliases (see #234) to work around this.
