### ISSUE TITLE
Add the endpoint for github-readme-stats

### ISSUE THREAD

**Issue by mlunax** [muety/wakapi#65]
I would like to see an endpoint like `api/v1/users/${username}/stats/last_7_days?is_including_today=true` in wakatime.
The github-readme-stats use this endpoint.

PS. I was trying to make this by myself but I cannot understand your permission (to endpoints) system.

**Comment by muety** [comment]
I'll take a look!

**Comment by muety** [comment]
I requested [#608](https://github.com/anuraghazra/github-readme-stats/issues/608) as it's a prerequisite for this feature. Also, an elaborate concept for #36 needs to come first.

**Comment by mlunax** [comment]
I done the kind of working version with changed api address but I need your help with enpoint (#36)

**Comment by muety** [comment]
The required change has just been [merged](https://github.com/anuraghazra/github-readme-stats/pull/620#event-4254288234) upstream, so we can proceed here. I'll take a look these days 🙂.
