### ISSUE TITLE
Printer-friendly dashboard styling

### ISSUE THREAD

**Issue by punyflash** [muety/wakapi#650]
Would be nice to have the ability to print stats page without additional styling by pressing single button

**Comment by muety** [comment]
How do you picture these PDF reports look like? How would you like to differ them from what you currently get by simply printing the dashboard page to PDF?

**Comment by punyflash** [comment]
Currently, when you just print a page, the markup is broken — you can barely read anything there
[Wakapi – Coding Statistics.pdf](https://github.com/user-attachments/files/15568946/Wakapi.Coding.Statistics.pdf)

**Comment by muety** [comment]
Would love to accept PRs for this! [This](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Printing) might be relevant.
