### ISSUE TITLE
Not Wakatime compatible API

### ISSUE THREAD

**Issue by Aruseiso** [muety/wakapi#653]
/compat/wakatime/v1/users/{user}/projects has parameter "q" - the query filter. In Wakatime this is an optional parameter, but here it is required.

**Comment by muety** [comment]
Thanks for the hint! I'm on vacation right now, but will fix this as soon as I'm back.

**Comment by muety** [comment]
Just checked: the parameter is in fact not required, only API docs were incorrect.
