### ISSUE TITLE
How can i export all my data? I want to selfhost it in the future.

### ISSUE THREAD

**Issue by danielmosss** [muety/wakapi#654]
Hey, i was wondering if i could export all my data on wakapi.dev?
I want to selfhost it and whould like to take all my data that i have gathered using wakapi.dev to import in my selfhosted wakapi.

**Comment by muety** [comment]
You can connect your local Wakapi instance (_Settings_ -> _Integrations_) to Wakapi using your API key and then use the import feature.

**Comment by IaVashik** [comment]
Wdym lol? 

> You can connect your local Wakapi instance (_Settings_ -> _Integrations_) to Wakapi using your API key and then use the import feature.

Wdym? Connect local wakapi to wakapi? Using the import feature for export data?? What?

**Comment by danielmosss** [comment]
Yes, to get the data from online wakapi.dev to my own localhost version. 
Im now selfhosting wakapi, with all my data that i gathered using the first half year with wakapi.dev

**Comment by muety** [comment]
You can also use the download script mentioned in https://github.com/muety/wakapi/issues/666#issuecomment-2293962646.

**Comment by danielmosss** [comment]
Aha nice work. the import featured worked flawlessly. had no problems.
