### ISSUE TITLE
Feature request: Porting to OpenBSD

### ISSUE THREAD

**Issue by samarulmeu** [muety/wakapi#656]
I  tried to compiled from source on OpenBSD 7.5 and I got this errors

Using `go build -o wakapi`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17e1308]

goroutine 1 [running]:
modernc.org/libc.(*TLS).setErrno(0x2532f80?, {0x2a8ea0?, 0x72ff00?})
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/etc.go:192 +0xa8
modernc.org/libc.Xmalloc(0x0, 0x340320?)
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/mem.go:39 +0xc5
modernc.org/libc.init()
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/libc_openbsd.go:49 +0x3b6
```

or `go install`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x178b6c8]

goroutine 1 [running]:
modernc.org/libc.(*TLS).setErrno(0x24dd380?, {0x2a8ea0?, 0x6d81a0?})
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/etc.go:192 +0xa8
modernc.org/libc.Xmalloc(0x0, 0x340320?)
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/mem.go:39 +0xc5
modernc.org/libc.init()
        /home/user/go/pkg/mod/modernc.org/libc@v1.49.0/libc_openbsd.go:49 +0x3b6
```

Any hint on what should I do or can be done to port it on OpenBSD?

**Comment by muety** [comment]
Hi @samarulmeu, thanks for reporting this. I've never worked with BSD and have little knowledge about how it differs from Linux, so can't really help a lot on this end. There seems to be an issue with the Go port of libc for OpenBSD, see [cznic/libc#34](https://gitlab.com/cznic/libc/-/issues/34). There's also a [discussion](https://gitlab.com/cznic/libc/-/issues/11) around OpenBSD support in the upstream repo. Perhaps you can find some useful insights there? 

Even though this probably isn't anything that could be fixed on our end, I'd love to stay in the loop. Keep us posted if you get Wakapi to work on OpenBSD :nerd_face:

**Comment by samarulmeu** [comment]
So this is my update as I finally managed to get it working on OpenBSD. 

These are the steps I followed. (Take into account I am not a go specialist so what I write might be wrong ;) )

First you need to upgrade go libraries with `go get -u` (I tested on 7.5, it will be interesting to see if you need this upgrade in current)

After that, when you try to do a `go build -o wakapi` you get this error 

```
# github.com/muety/wakapi/services/mail
services/mail/smtp.go:46:14: c.StartTLS undefined (type *smtp.Client has no field or method StartTLS)
```

What I did was to comment the lines 46-53 from `services/mail/smtp.go` compiled and I got the executable and the server run. I'm sure there will be no mail functionality but for running locally will be ok I think. The problem might be in  the OpenBSD mail implementation. 

So, we might still dig further or/and add a installation instruction for OpenBSD users.

**Comment by muety** [comment]
Thanks for sharing your insights! The error is unrelated to OpenBSD and goes back to breaking changes in an upstream library, see #657. So in essence, it seems like running Wakapi on OpenBSD is nothing more but a matter of upgrading to latest dependency versions. I'll push an updated version soon!
