### ISSUE TITLE
Is there wakatime like dashboard which shows weekly graph?

### ISSUE THREAD

**Issue by rohitkrishna094** [muety/wakapi#662]
On original wakatime, it has couple of charts like this

![image](https://github.com/user-attachments/assets/417d921f-6c2b-430c-b314-40007542c9f1)
![image](https://github.com/user-attachments/assets/9ecd9e73-2d09-4d86-ae65-199402f086fe)

Does wakapi.dev have something like this or is there a way to turn it on?

**Comment by muety** [comment]
Duplicate of #157, #338.

Will hopefully get to implementing this soon! I'm planning a Wakapi deep work session some time soon.
