### ISSUE TITLE
How can I manually add coding activity to Wakapi using external tools like Postman?

### ISSUE THREAD

**Issue by AkipTsaqif** [muety/wakapi#663]
My question is basically how can i do it? I'm using self hosted Wakapi but unable to hit any api listed in the swagger-ui using Postman. All i get is always 401 unauthorized even though i already added the authorization header in this format: `Basic [my-api-key]`

**Comment by muety** [comment]
As stated in the docs, you'll need to pass the base64-hashed API key, not the plain one. See for example [here](    http.headers.update({'Authorization': f'Basic {encoded_key}'})).
