### ISSUE TITLE
cannot unmarshal array into Go value of type models.Heartbeat

### ISSUE THREAD

**Issue by alanhamlett** [muety/wakapi#688]
I'm seeing a 400 error response from `https://wakapi.dev/api/compat/wakatime/v1/users/current/heartbeats.bulk`:

```
json: cannot unmarshal array into Go value of type models.Heartbeat
```

When sending JSON payload:

```json
[
  {
    "branch":"<<LAST_BRANCH>>",
    "entity":"https://wakapi.dev",
    "id":"f3647f89-e255-4dd1-8fcd-e20ba8f1709b",
    "project":"<<LAST_PROJECT>>",
    "time":"1728422364.044",
    "type":"domain",
    "userAgent":"Chrome/129.0.0.0 mac_x86-64 chrome-wakatime/4.0.6"
  }
]
```

Might be from `time` being a string instead of number. The WakaTime API accepts both types, but we prefer string to avoid any [floating point](https://en.wikipedia.org/wiki/Floating-point_arithmetic) accuracy errors.

Or, it could be the `id` or `userAgent` attributes, which might not be known by wakapi.

Lastly, it could be `"type": "domain"`, but I assume wakapi should support that because it's been used by the browser extension for many years already.

**System information**
* Wakapi version: cloud
* Operating system: Chrome browser extension

**Comment by muety** [comment]
It's both, the `id` field and `time` field being strings, while Wakapi expects numbers for both. Relates to #682. Not entirely sure how to best go about this. Generally, having to support multiple data types (in case of `time`) for the same field name is a bit painful imo and doesn't go very well with statically typed code. I'll probably have to introduce separate view models and add a bunch of hacks here and there. Will have a look soon.

**Comment by muety** [comment]
@alanhamlett Can you give a few hints about what has changed on the plugin's end to cause these failures? Did the payload of heartbeats sent to the API change? Can you point me to the relevant commits in the plugin's codebase, please?

**Comment by muety** [comment]
To be honest, rather than putting long-winded hacks in place on Wakapi's heartbeats endpoint, I'd prefer to make the plugin follow the payload format specified in the [docs](https://wakatime.com/developers/#heartbeats), where `time` is a float and `id` is not included. What do you think? I can do a PR if desired.

**Comment by alanhamlett** [comment]
Sure, I'll fix that in the browser extension.

**Comment by alanhamlett** [comment]
https://github.com/wakatime/browser-wakatime/commit/1031ad02790fb570d537e046dd38098387444650

**Comment by muety** [comment]
Thanks! 👍 Pushed a fix to Wakapi in the meanwhile well. Actually, sending `time` as strings has been fine and Wakapi will ignore incoming `id` in the latest version.

**Comment by alanhamlett** [comment]
Ok, I'll revert my browser-wakatime change then. 👍
