### ISSUE TITLE
Configuration loading errors are not logged properly due to a dependency on Config being loaded

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#689]
**Describe the bug**

I was moving my wakapi instance from one host to a different one and had some issues with the config.yaml/environment variables not getting loaded properly. I was constantly getting this error:
```
Waiting for database to come up
wait-for-it.sh: waiting 60 seconds for database-host:5432
wait-for-it.sh: database-host:5432 is available after 0 seconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeb99b1]
goroutine 1 [running]:
github.com/muety/wakapi/config.(*Config).IsDev(...)
	/src/config/config.go:228
github.com/muety/wakapi/config.Log()
	/src/config/sentry.go:31 +0x31
github.com/muety/wakapi/config.Load({0x1258116, 0xa}, {0x1254209, 0x7})
	/src/config/config.go:474 +0xf0
main.main()
	/src/main.go:122 +0x138
```

After diving into the code to figure out what was going on, I found out that the Log() function has a dependency on the Config to be properly loaded, as it fetches it using Get() and verify which environment is being used: 
https://github.com/muety/wakapi/blob/2568fbd39bd48b6a8d566c7b9ed8dcefafa28430/config/sentry.go#L25-L33

In a case where configor fails to load the configuration, this will always results in a nil pointer dereference. 

https://github.com/muety/wakapi/blob/2568fbd39bd48b6a8d566c7b9ed8dcefafa28430/config/config.go#L471-L475

After activating `CONFIGOR_DEBUG_MODE` I now get this debug log, which is actually helpful:
```
Loading configuration for struct `serverConfig`'s field `Port` from env WAKAPI_PORT...
Failed to load configuration from [config.yml], got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `tcp://1...` into int
Configuration:
  &config.Config{ ... }}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeb99b1]
goroutine 1 [running]:
github.com/muety/wakapi/config.(*Config).IsDev(...)
	/src/config/config.go:228
github.com/muety/wakapi/config.Log()
	/src/config/sentry.go:31 +0x31
github.com/muety/wakapi/config.Load({0x1258116, 0xa}, {0x1254209, 0x7})
	/src/config/config.go:474 +0xf0
main.main()
	/src/main.go:122 +0x138
...
```

**System information**
Please provide information on:
* Wakapi version : `latest` / `2.12.0`
* Operating system
    * If Linux: which distro? `Nixos` `k3s`
    * If Docker: which image and tag? `ghcr.io/muety/wakapi:latest`
* Database (SQLite, MySQL, ... ?) `postgresql`

**Comment by muety** [comment]
Without having looked deeper into this yet, it appears to me that you're trying to set a connection string as the `WAKAPI_PORT`. Could you please show the relevant parts of your config, please?

I agree that we should provide more useful error messages in case of config loading failure though.

**Comment by notarock** [comment]
I solved the configuration problem, I had `WAKAPI_PORT` set to a bogus value of `tcp:10.x.x.x` and now my setup is up and running 😄

As for the error message, I am not too familiar with the error thrown by the configor package but I think replacing the `Log().Fatal` for `log.Fatal` should allow us to at least print that info properly. I'll see if that works and open a PR
