### ISSUE TITLE
Browsers heartbeats looks like not accepted anymore

### ISSUE THREAD

**Issue by Bashev** [muety/wakapi#690]
**Describe the bug**
Wakatime Browser extensions was updated recently, and after that they are probably sent different request which are not accepted by wakapi anymore.  

```
192.168.200.1 - - [14/Oct/2024:23:26:45 +0300] "OPTIONS /api/compat/wakatime/v1/users/current/heartbeats.bulk?api_key=XXXXX HTTP/2.0" 405 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"
192.168.200.1 - - [14/Oct/2024:23:26:49 +0300] "OPTIONS /api/compat/wakatime/v1/users/current/heartbeats?api_key=XXXXX HTTP/1.1" 405 0 "-" "-" "-"
```

**System information**
Please provide information on:
* Wakapi version: *2.12.1*
* Operating system
    * If Linux: which distro? *Rocky Linux*
    * If Docker: which image and tag? *No.*
* Database (SQLite, MySQL, ... ?) *MySQL*

**Comment by muety** [comment]
Will your data show up on Wakapi nevertheless? 

**Example preflight request (`OPTIONS`):** 
[wakapi_browser_preflight_example.json](https://github.com/user-attachments/files/17369764/wakapi_browser_preflight_example.json)

**Comment by muety** [comment]
Also, relates to #688.

**Comment by Bashev** [comment]
I have no data in wakapi which is related to browsers tracking. I i not expect anything else, because server responds with `405 method not allowed.`

I also had an assumption this is related to #688 but after update to 2.12.1 it's still the same and this is the reason for this issue.

**Comment by muety** [comment]
Can you please show your browser plugin configuration settings? Also, which browser are you using?

**Comment by Bashev** [comment]
Chrome, Firefox

![image](https://github.com/user-attachments/assets/ba329f65-af3d-410e-a61f-b7b7b2ea0c14)

**Comment by muety** [comment]
Can you please check if https://github.com/muety/wakapi/commit/40e01c1b01c001df777468ff08a2bbdd1b1aabe0 resolved the issue? Strangely, everything seems to work fine for wakapi.dev, as well as for my local instance - even before that change.

**Comment by libukai** [comment]
I have the same issue.
