### ISSUE TITLE
Inconsistent time format from `api/compat/wakatime/v1/users/{users}/stats/all_time`

### ISSUE THREAD

**Issue by pjyi2147** [muety/wakapi#698]
**Describe the bug**
A clear and concise description of what the bug is. Please briefly describe how to reproduce the bug as well as _expected_ vs. _actual_ behavior. Optionally include screenshots and server logs, if helpful.

I am using waka-readme with github actions to update my readme daily.

It keep giving me an error with inconsistent time format previously discussed in https://github.com/athul/waka-readme/issues/112

The formats with issue are:

```
2024-10-27T14:02:30.88807562-04:00  # RFC3339Nano
2024-09-30T02:13:54.428Z # RFC3339? ISO8601 with miliseconds?
```

you can take a look previous runs of my actions here: 
https://github.com/pjyi2147/pjyi2147/actions/runs/11542659933/job/32126127952
https://github.com/pjyi2147/pjyi2147/actions/runs/11428021776/job/31792859789

I am guessing the issue is coming from https://github.com/muety/wakapi/blob/master/models/compat/wakatime/v1/stats.go having time struct instead of string as in https://github.com/muety/wakapi/blob/master/models/compat/wakatime/v1/all_time.go. 

It seems like Go compiler selects whatever time format it pleases.

Workaround suggestion is to set `Start` and `End` struct parameter to string with specific time format - it will be great if we can select the time conversion format for api output through environment variable. 

Thanks for great work! I appreciate your work a lot.

**System information**
Please provide information on:
* Wakapi version: latest
* Operating system
    * If Linux: which distro? oracle linux
    * If Docker: which image and tag? ghcr.io/muety/wakapi:latest
* Database (SQLite, MySQL, ... ?) postgres

**Comment by muety** [comment]
Thanks for bringing this up. Will fix it asap!

**Comment by pjyi2147** [comment]
Hi, thanks for fixing the issue! Just one more thing, could you update your docker image so that I can have the fixed version? Thanks so much!

**Comment by muety** [comment]
New release (incl. updated Docker images) will be pushed soon. Wanna include a bunch of more changes in addition.
