### ISSUE TITLE
Top Project muety/wakapi ，Top Language is  unknown ？

### ISSUE THREAD

**Issue by openapphub** [muety/wakapi#699]
<img width="672" alt="image" src="https://github.com/user-attachments/assets/73d95ff0-1e0f-4e6c-b70a-e2ad075a031a">

**Comment by muety** [comment]
There are multiple causes for "unknown" language, e.g. heartbeats related to web browsing (using the browser plugin) or simply if the wakatime-cli can't guess the language of the file you're editing. This is likely not a bug of Wakapi and, if it was, it's impossible to further debug this if you just post a plain screenshot without any comments, sorry.
