### ISSUE TITLE
[Feature] Add periodical wakatime import data

### ISSUE THREAD

**Issue by JoniLieh** [muety/wakapi#701]
Thanks for your nice work!

Could you add a option to periodically import data from wakatime?

At https://wakapi.dev/settings#integrations > WakaTime
One can import data from their wakatime account, I'd like to have this happen regularly like every single hour or more.
So I can have everything in on wakapi.dev, and the data won't get lost like on wakatime.

I know I can change some url in .wakatime/.cfg but this is sometimes problematic with multiple devices and OS's

Example:
![Unbenannt](https://github.com/user-attachments/assets/dd6742cc-a53f-40aa-9b09-5321ef73618d)

**Comment by muety** [comment]
Thanks for your feature request! I'm not planning to implement this at the moment. However, there are two alternative options to consider: 

1. Use relay functionality. If you use Wakapi as your primary instance (by changing the `api_url` in your `.wakatime.cfg`, you can configure it (_Settings -> Integrations_) to forward your heartbeats to WakaTime. This way, you can use both services in parallel and have your data stored in both simultaneously.
2. Run this simple script as a cronjob to trigger periodical syncs:
    ```bash
    curl -XPOST https://wakakpi.dev/settings \
        -H "Authorization: Basic <your base64 api key>" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "action=import_wakatime&use_legacy_importer=false"
    ```

Note that Wakapi permits imports only every 24 hours at minimum.
