### ISSUE TITLE
Unable to start the compiled wakapi on Linux/windows with "dev" config

### ISSUE THREAD

**Issue by justin-jiajia** [muety/wakapi#703]
**Describe the bug**
I'm unable to start wakapi on Linux or windows with "dev" in config or without the `config.yml`.

I just downloaded the latest release [here](https://github.com/muety/wakapi/releases/download/2.12.1/wakapi_linux_amd64.zip). I could correctly run it. Then I changed the `env: production` into `env: dev` that would stop it from starting with the logs below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xeb9b71]

goroutine 1 [running]:
github.com/muety/wakapi/config.(*Config).IsDev(...)
        /home/runner/work/wakapi/wakapi/config/config.go:228
github.com/muety/wakapi/config.Log()
        /home/runner/work/wakapi/wakapi/config/sentry.go:31 +0x31
github.com/muety/wakapi/config.readColors()
        /home/runner/work/wakapi/wakapi/config/config.go:444 +0x126
github.com/muety/wakapi/config.Load({0x1258356, 0xa}, {0x1254449, 0x7})
        /home/runner/work/wakapi/wakapi/config/config.go:488 +0x319
main.main()
        /home/runner/work/wakapi/wakapi/main.go:122 +0x138
```

The same thing happened without the config file("dev"as default).

I have tested it on windows and the same thing happened.

However, I built and ran it on Github Codespaces and it ran as excepted.

**System information**
Please provide information on:
* Wakapi version: 2.12.1
* Operating system
    * If Linux: which distro?
```
justin-jiajia@jiajia:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by muety** [comment]
New release coming soon!
