### ISSUE TITLE
Address deprecation warnings on Release Action

### ISSUE THREAD

**Issue by YC** [muety/wakapi#704]
Noticed
```
The following actions use a deprecated Node.js version and will be forced to run on node20:
softprops/action-gh-release@v1, dev-drprasad/delete-older-releases@v0.3.2.
```
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

---

For `softprops/action-gh-release`, we can upgrade to v2. 
https://github.com/softprops/action-gh-release/blob/v2.0.9/action.yml#L64

For `dev-drprasad/delete-older-releases`, it looks like it's no longer maintained. 
@muety Was there a particular reason for introducing this step?

---

Apologies to those who are watching the project and receiving an empty email, I fat-fingered the Enter key...

**Comment by muety** [comment]
Thanks for bringing this up! For the `delete-older-releases` action: I included it simply to remove old clutter. It's not super important, but I'd still prefer if we could find a way to keep it in. Options include to (a) find an alternative on the marketplace, (b) create an own fork (:neutral_face:) and, in the worst case, (c) remove it.

**Comment by muety** [comment]
Do you wanna give it a go?

**Comment by YC** [comment]
I've addressed `softprops/action-gh-release`. 
I'm more in favor of keeping releases, for the history of past release notes and artifacts. 
An example where this documentation might help is when performing major version upgrades.

**Comment by muety** [comment]
Alright, then let's remove the delete-release task.

**Comment by YC** [comment]
FYI, I think the MSSQL tests are intermittently failing due to https://github.com/microsoft/mssql-docker/issues/895.
