### ISSUE TITLE
Possibility to send email without binding port 465 or 587 directly to Wakapi container?

### ISSUE THREAD

**Issue by che0one** [muety/wakapi#707]
Is it possible to send emails without exposing ports (e.g., 465 or 587) directly to a container running Wakapi? I noticed that many other applications, such as Authentik, Gitea, Bookstack, don't require binding external ports directly to the container. Instead, they can send emails seamlessly using an external SMTP host on those ports. But Wakapi with same settings cannot...
```
{
  "time": "2024-11-12T19:44:01.472471877Z",
  "level": "ERROR",
  "msg": "failed to send password reset mail",
  "userID": "username",
  "error": "dial tcp some_external_ip:465: i/o timeout"
}
```
Another strange issue is that some_external_ip is an Amazon IP address, but it is not the EC2 public IP, EC2 private IP, or container IP, SMTP server IP of any instance. 

```
      - WAKAPI_MAIL_ENABLED=true
      - WAKAPI_MAIL_PROVIDER=smtp
      - WAKAPI_MAIL_SENDER=Wakapi     
      - WAKAPI_MAIL_SMTP_HOST=smtp.example.com
      - WAKAPI_MAIL_SMTP_PORT=465
      - WAKAPI_MAIL_SMTP_USER=admin@example.com
      - WAKAPI_MAIL_SMTP_PASS=mail_password
      - WAKAPI_MAIL_SMTP_TLS=false
```
Also checked with multiple SMTP, self, Yandex, Google, Brevo

**Comment by muety** [comment]
You only need to expose ports for ingoing traffic to the container. Outgoing traffic is allowed from and to any port, unless you explicitly put some super strict Docker / firewall configuration in place.

Wakapi only exposes port 80 (HTTP) or 443 (HTTPS).

E-mail can be sent through any external SMTP server with it any further config. The I/O error you're getting must be due to some other cause and is most likely not related to Wakapi itself.

**Comment by muety** [comment]
#536 might be related.

**Comment by che0one** [comment]
A bit later on, I continued investigating the issue. Although the policies, configurations, firewall, and antivirus settings are quite strict, other applications run smoothly with the same settings.

**Comment by muety** [comment]
Another thing I noticed is you set `WAKAPI_MAIL_SMTP_TLS=false` even though port 465 is usually used for SMTP + TLS. Are you sure about that setting? 

Are you hosting your own SMTP server or using something like GMaill?

**Comment by che0one** [comment]
@muety 
After multiple tries it is finally works over Gmail smtp port 587 : 

- WAKAPI_MAIL_SMTP_TLS=false   works well
- WAKAPI_MAIL_SMTP_TLS=true    tls handshake error

<img width="640" alt="Screenshot 2024-11-14 at 02 52 11" src="https://github.com/user-attachments/assets/75d0844b-400e-45f8-af05-6e7adf2391b6">

Absolutely no idea how it works, why it works, better don't touch it... Thank you...
