### ISSUE TITLE
Properly configure DockerHub build

### ISSUE THREAD

**Issue by muety** [muety/wakapi#71]
* Configure DockerHub to build on new Git tags
* Tag newly built images with `latest` and their according Git tag
* Get rid of `stable` branch

**Comment by muety** [comment]
Automated build are triggered by new tags now. 

In addition, it would be helpful to give an image multiple tags. However, [this is not yet supported](https://windsock.io/automated-docker-image-builds-with-multiple-tags/) at the moment.

**Comment by bialad** [comment]
I don't know if this is what you intended here, but it would be nice to have the release tag on the image as well as the latest tag. For example n1try/wakapi:1.16.2.

I like this project, and run it in kubernetes which doesn't work well with images with only :latest tags. ;)

**Comment by muety** [comment]
@bialad Thanks for your feedback. Yes, this is pretty much what I meant by "is not yet supported". As far as I can see, DockerHub's automated build can't tag images with multiple tags, unfortunately. The only alternative I see right now is to manually build, tag and upload the images. But I might also be mistaken and there's a better way? :thinking:
