### ISSUE TITLE
Editors not recognized

### ISSUE THREAD

**Issue by crnobog69** [muety/wakapi#712]
I installed Wakapi and I am self-hosting it. VS Code and IntelliJ IDEA are recognized but Cursor and Micro are not. Is Curosor reconized as VS Code? Same is when `api_url` is `https://wakapi.dev/api`. Wakatime recognizes Cursor.

Wakapi(2.12.2)
Arch Linux

**Comment by crnobog69** [comment]
> Thanks for reporting. Can you please post the user agent (`user_agent` column inside `heartbeats` table in your database) of exemplary heartbeats sent for Cursor and Micro? Would help me debugging this a lot!

` "user_agent" varchar(255)

I used `sqlitebrowser` Browse Data on table 'heartbeats' and then under `user_agent` 

` wakatime/v1.105.0 (linux-6.11.9-zen1-1-zen-unknown) go1.23.3 intellijidea/2024.3 intellijidea-wakatime/15.0.3

` wakatime/v1.105.0 (linux-6.11.9-zen1-1-zen-unknown) go1.23.3 vscode/1.95.3 vscode-wakatime/24.8.0

this?

I am sorry, I don't use SQL so I am not sure what do you mean

**Comment by crnobog69** [comment]
and there is this 
wakatime/v1.105.0 (linux-6.11.8-zen1-2-zen-unknown) go1.23.3 cursor/1.93.1 vscode-wakatime/24.8.0

**Comment by muety** [comment]
Alright, had a look at this. Apparently, these are two different problems. _Cursor_ not being recognized as an editor was a bug on our end, which I just pushed a fix for. The _micro_ editor seems to work fine, though. However, make sure that you have version 1.0.6 of [micro-wakatime](https://github.com/wakatime/micro-wakatime) installed (need to use the "git clone" installation method), as 1.0.5 is not compatible anymore.

**Comment by muety** [comment]
Opened an upstream PR to update micro's wakatime plugin reference to the latest version, see https://github.com/micro-editor/plugin-channel/pull/110.
