### ISSUE TITLE
Evaluate switching to a time-series database

### ISSUE THREAD

**Issue by muety** [muety/wakapi#73]
Our `Heartbeat`s are pretty much exactly time-series data, so I wondered if using a TSDB might help store them more efficiently than using a traditional relational table in which every heartbeat is one row. But I am not sure how exactly a time-series database could help here. It certainly would add a lot of complexity to the code and to the setup / deployment, as we will then have to distinguish between two different data sources – one for heartbeats and one for everything else.

Does someone have practical experience with time-series databases and can explain some advantages with regard to Wakapi?

Options are: [InfluxDB](https://www.influxdata.com/), [OpenTSDB](http://opentsdb.net/), \<name yours here\>.

Are there maybe even "embedded" TSDBs, like what [bbolt](https://github.com/etcd-io/bbolt) is for key-value stores or what [H2](http://h2database.com/html/main.html) is for relational databases in the Java world?

**Comment by erclu** [comment]
Hi! recently found out your project and loving it so far.

I'd suggest using this time-series database:

https://www.timescale.com/

it's implemented as a PostgreSQL extension and has a [full sql interface](https://docs.timescale.com/latest/introduction), so considering that you already support postgres it should be easy to setup and require few (or possibly no) changes to the codebase.

I don't have any familiarity at all with Go so i wouldn't be able to actively contribute but if you're using gorm it should be possible to use a migration to invoke the function that creates the Timescale HyperTable directly from code:

https://docs.timescale.com/latest/using-timescaledb/hypertables

https://gorm.io/docs/migration.html

**Comment by muety** [comment]
TimescaleDB look very promising, thanks for bringing that up! However, I'm still wondering what a time-series database would actually get me? Is data going to be stored more efficiently or can queries be sped up, compared to using a classical index on a plain SQL database? The queries perfomed by Wakapi are mainly simple range queries like "give me all heartbeats between X and Y".

**Comment by erclu** [comment]
> I'm still wondering what a time-series database would actually get me? Is data going to be stored more efficiently or can queries be sped up, compared to using a classical index on a plain SQL database? 

I'd say the benefits are mostly a speedup in writing data:

![image](https://user-images.githubusercontent.com/30255227/100927975-ea6b7c80-34e5-11eb-9725-5d05cfd9299b.png)

ref: https://docs.timescale.com/latest/using-timescaledb/writing-data

the screenshot refers specifically to your use case which i believe is a lot of INSERTs which refer to recent timestamps

> The queries perfomed by Wakapi are mainly simple range queries like "give me all heartbeats between X and Y".

timescale and other timeseries dbs (i only used influxdb and timescale) provide some helper functions that can be invoked directly in the SQL query. i think some could be useful to you:

ref: https://docs.timescale.com/latest/using-timescaledb/reading-data

overall i'd say that it could be convenient to use timescale if only for the fact that switch to it is easy and gives you a lot of room to improve performance. The only thing you'd need to do is write the migration to be consumed by gorm, you don't even need to modify the model entities. The migration should run the query:

```SQL
SELECT * FROM create_hypertable('main_table', 'time_column_name');
```

**Comment by muety** [comment]
Thanks for all your input. I don't consider a time series database overly beneficial at the moment, so I'll close this issue for now.

**Comment by muety** [comment]
Took another peek into TimescaleDB today. I still consider the efforts it would take to migrate higher than the benefits we would get from it. However, if we decide to switch to a TSDB, Timescale would be the best option.

As Timescale still exposes normal relational tables to the outside, we wouldn't have to change our data model a lot, if at all. 

According to their [comparison](https://docs.timescale.com/latest/introduction/timescaledb-vs-postgres), the biggest advantage would probably be for range- and grouping queries, like the ones we have in the heartbeats repo. 

Switching to Timescale would require to drop support for SQLite and MySQL and make Postgres the mandatory choice.
