### ISSUE TITLE
File statistics

### ISSUE THREAD

**Issue by Syndamia** [muety/wakapi#80]
I would like to be able to get info for how long I've been working on a given file, not only on a given project. This is especially important for the "unknown" project.

**Comment by muety** [comment]
Great feature request. I'm thinking of adding another bar- or pie chart for this. However, the file statistics should be project-specific, otherwise, things would become too messy. There could be a drop-down to select a specific project for which file statistics are shown then.

**Comment by Syndamia** [comment]
> the file statistics should be project-specific [...] drop-down to select a specific project

Honestly, this is more than perfect. File statistics per project will be extremely useful but statistics for all files in general won't be that helpful, in my opinion.

**Comment by muety** [comment]
I'll add this feature to my project roadmap. But please be aware that this is a change of more than just a few lines of code, as a whole new [SummaryType](https://github.com/muety/wakapi/blob/143c80b7b4717cdb9e7f49f1bd485c80d3ed3b15/models/summary.go#L8) will have to be introduced, so it might take a bit.

**Comment by Syndamia** [comment]
No worries, I know how FOSS projects, developed by one guy go. Also, is the file data being collected right now (and just not displayed)?

**Comment by muety** [comment]
> is the file data being collected right now

Yes, every heartbeat send by the Wakatime CLI contains an `entity` field, which is the absolute file system path of the file subject to this heartbeat. This path is already used to try to infer unknown / custom languages from the file's ending.

**Comment by muety** [comment]
What would you like to be considered a "file"? 

A raw heartbeat looks like so:

```json
[
  {
    "time": 1610092483.0600193,
    "entity": "/home/ferdinand/dev/website-watcher-script/adapters/email.py",
    "type": "file",
    "category": null,
    "is_write": false,
    "project": "website-watcher",
    "branch": "master",
    "language": "Python",
    "dependencies": [],
    "lines": 77,
    "lineno": null,
    "cursorpos": null,
    "user_agent": "wakatime/13.0.7 (Linux-5.9.16-200.fc33.x86_64-x86_64-with-glibc2.4) Python3.8.0.final.0 vscode/1.50.1 vscode-wakatime/5.0.0"
  }
]
```

Probably it would be cool to have a file path relative to the project root, i.e. `adapters/email.py` in this case. Unfortunately, we only have the entire, absolute file paths. That is, if you're working on the same file of the same project on two different machines, they files are no necessarily considered the same unless the whole absolute file path is identical, too. 

Would this still be acceptable for you? Or do you have any further ideas?

**Comment by Syndamia** [comment]
Oh, this will be more than enough! The only thing that comes to mind, is that in WakaTime, it shows just the file name and when you hover over it, the full path is shown:
![Peek 2021-01-08 10-03](https://user-images.githubusercontent.com/46843671/103989687-c19b6e80-5198-11eb-88a4-acbe2a60fc51.gif)
But even if you don't implement that, it won't be a big deal!

**Comment by hypervtechnics** [comment]
This would be great. Just a question: How would editing the same project on different machines would be handled? Especially when the project is in a different path?

**Comment by hypervtechnics** [comment]
Well the only thing doable for me is taking the project field of the heartbeat into account. This would mean comparing filepaths from the right and summarizing heartbeats when they have the same project. Although this would cause issues when you e.g. have the same filename in multiple directories as we don't have a project path.

**Comment by muety** [comment]
> Although this would cause issues when you e.g. have the same filename in multiple directories as we don't have a project path

Yes, right, the project name is not necessarily an infix of the file's path. You could well have a project called `webapp` located at `~/dev/web-app-frontend`. That has to be kept in mind.

**Comment by hypervtechnics** [comment]
Another why I could imagine is additionally taking the machine field into account. Then grouping by project is possible as the project path is available (calculatable by evaluating all file paths + project + machine and taking the path beginning equal for all file paths). Although this would cause issues with the WSL as the machine name is the same but a different file system and therefore other paths might be used. But I think thats okay, as one might solve this using (project maps)?

**Comment by muety** [comment]
I thought about this again and decided that Wakapi is not going to implement file statistics. Sorry for all shattered hopes.
