### ISSUE TITLE
Configurable how many top statistics to show

### ISSUE THREAD

**Issue by Syndamia** [muety/wakapi#81]
Currently all statistics show top 10 of something (top 10 project, top 10 languages, ...), I would like to be able to change that. Also, it would be even better if I could set it depending on the statistic, e.g. choosing top 20 languages and top 5 projects at the same time, through the ui.

**Comment by muety** [comment]
Thanks for the feedback! This should be done quite easily and would make a convenient improvement. I'll look into it soon!
