### ISSUE TITLE
Ability to import/export or sync heartbeats from official wakatime api

### ISSUE THREAD

**Issue by alanhamlett** [muety/wakapi#87]
Along with #28, this would make using wakapi together with official WakaTime seamless. Two requirements:

* Deduplicate heartbeats between the two services (See code example)
* Need a way to bypass WakaTime's heartbeat validation, which blocks writing heartbeats older than 180 days

To deduplicate heartbeats, we can ofc use `heartbeat.id` but also should check if the heartbeat's attributes are the same. Here's a code snippet from the WakaTime backend:

```python
def is_duplicate_heartbeat(heartbeat_a, heartbeat_b):
    return (heartbeat_a.entity == heartbeat_b.entity and
            heartbeat_a.type == heartbeat_b.type and
            heartbeat_a.project == heartbeat_b.project and
            heartbeat_a.branch == heartbeat_b.branch and
            heartbeat_a.language == heartbeat_b.language and
            heartbeat_a.time == heartbeat_b.time)
```

**Comment by muety** [comment]
Great idea! Something similar was already requested before, see #72. However, last time I looked into this, there either was no ability to get raw heartbeats out of Wakatime or I simply missed it. Looks like the [heartbeats resource](https://wakatime.com/developers#heartbeats) is the way to go here.

**Comment by muety** [comment]
@alanhamlett I'm currently working in this, however, one thing that I'm missing is an API endpoint to resolve `machine_name_id`s to actual machine names, analogously to `user_agent_id`.

**Comment by alanhamlett** [comment]
@muety you can use the [Machine Names endpoint](https://wakatime.com/developers/#machine_names) to list all, or just one by id, for ex: `/api/v1/users/current/machine_names/:machine_name_id`

The docs were missing that endpoint, but I've added it now.

**Comment by muety** [comment]
Thanks, I'll adapt the import later!
I would recommend all users to wait with their import until this next update.

**Comment by alanhamlett** [comment]
Related, we've opened the API for all date ranges. You can import Heartbeats for non-Premium users back until their account was created. Dates before the user was created will just always return an empty array.

Only the dashboard now limits date range queries, not the API 😄

**Comment by alanhamlett** [comment]
We recently added a `type` param to the data dumps api:
https://wakatime.com/developers/#data_dumps

Using `type` of `heartbeats` allows exporting all raw heartbeats for an account over all time. The heartbeats api is better for syncing, but just wanted to point out another option for backing up all heartbeats.

**Comment by muety** [comment]
Awesome, thanks for that hint!
